package apextest

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Immutable owned sources from admitted legacy successor and control packets.
func TestRunC5LegacyAdmitted(t *testing.T) {
	home := os.Getenv("GLADE_DATAWEAVE_APEX_TEST_HOME")
	if home == "" {
		t.Fatal("legacy DataWeave checks require an explicitly installed toolchain in GLADE_DATAWEAVE_APEX_TEST_HOME")
	}
	t.Setenv("GLADE_HOME", home)
	t.Run("c5-legacy-successor-bulk-runtime65-corrected-v1", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNested65Proof.cls"), "@IsTest\nprivate class GladeLegacyNested65Proof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        Account account = new Account(Name = 'Acme');\n        insert account;\n        insert new Contact(AccountId = account.Id, LastName = 'Child');\n        List<Account> rows = [SELECT Id, (SELECT Id FROM Contacts) FROM Account WHERE Id = :account.Id];\n        try {\n        \tDataWeave.Script.createScript('records').execute(new Map<String,Object>{'records' => rows});\n        \tSystem.assert(false, 'expected DataWeaveScriptException');\n        } catch (Exception ex) {\n        \tAssert.isInstanceOfType(ex, DataWeaveScriptException.class);\n        }\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNested65Proof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/records.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/records.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDivisionProof.cls"), "@IsTest\nprivate class GladeLegacyDivisionProof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        try {\n        \tDataWeave.Script.createScript('error').execute(new Map<String,Object>());\n        \tSystem.assert(false, 'expected DataWeaveScriptException');\n        } catch (Exception ex) {\n        \tAssert.isInstanceOfType(ex, DataWeaveScriptException.class);\n        \tSystem.assert(ex.getMessage().startsWith('Division by zero'));\n        }\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDivisionProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/error.dwl"), "%dw 2.0 \noutput application/json\n--- \n1/0")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/error.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyMultipleProof.cls"), "@IsTest\nprivate class GladeLegacyMultipleProof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        String products = '[ { \"type\": \"book\", \"price\": 30, \"properties\": { \"title\": \"Everyday Italian\", \"author\": [ \"Giada De Laurentiis\" ], \"year\": 2005 } } ]';\n        String attributes = '{ \"publishedAfter\": 2004 }';\n        String exchangeRates = '{ \"USD\": [ {\"currency\": \"EUR\", \"ratio\":0.92}, {\"currency\": \"ARS\", \"ratio\":8.76} ]}';\n        String output = DataWeave.Script.createScript('multipleInputs')\n        \t.execute(new Map<String,Object>{'products' => products, 'attributes' => attributes, 'exchangeRates' => exchangeRates})\n        \t.getValueAsString();\n        System.assert(output.contains('<author>Giada De Laurentiis</author>'));\n        System.assert(output.contains('<price currency=\"ARS\">262.8</price>'));\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyMultipleProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/multipleInputs.dwl"), "%dw 2.0 \n// This example is taken from:\n// https://docs.mulesoft.com/dataweave/2.5/dataweave-cookbook-reference-multiple-inputs\n// More on DataWeave formats:\n// https://docs.mulesoft.com/dataweave/2.5/dataweave-formats\ninput products application/json\ninput attributes application/json\ninput exchangeRates application/json\noutput application/xml\n--- \nbooks: {\n    (products filter ($.properties.year > attributes.publishedAfter) map  (item)   ->  {\n        book @(year: item.properties.year): {\n            (exchangeRates.USD map {\n                price @(currency: $.currency): $.ratio * item.price\n            }),\n            title: item.properties.title,\n            authors: { (item.properties.author map {\n                author: $\n            }) }\n        }\n    } )\n}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/multipleInputs.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRecipesOriginalProof.cls"), "@IsTest\nprivate class GladeLegacyRecipesOriginalProof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        String csv = 'FirstName,LastName,Email\\nAda,Lovelace,ada@example.test\\nGrace,Hopper,grace@example.test';\n        String contactsCsv = 'first_name,last_name,email\\nAda,Lovelace,ada@example.test\\nGrace,Hopper,grace@example.test';\n        DataWeave.Result contactsResult = DataWeave.Script.createScript('csvToContacts').execute(new Map<String,Object>{'records' => contactsCsv});\n        List<Contact> contacts = (List<Contact>)contactsResult.getValue();\n        System.assertEquals(2, contacts.size());\n        System.assertEquals('Ada', contacts.get(0).FirstName);\n        System.assertEquals('Hopper', contacts.get(1).LastName);\n        \n        String jsonText = DataWeave.Script.createScript('csvToJsonBasic').execute(new Map<String,Object>{'payload' => csv}).getValueAsString();\n        System.assert(jsonText.contains('\"FirstName\": \"Ada\",'));\n        List<Object> jsonList = (List<Object>)JSON.deserializeUntyped(jsonText);\n        System.assertEquals(2, jsonList.size());\n        Map<String,Object> first = (Map<String,Object>)jsonList.get(0);\n        System.assertEquals('Ada', first.get('FirstName'));\n        \n        String snake = 'first_name,last_name,email\\nAbel,Maclead,a.m@demo.org';\n        List<Contact> snakeContacts = (List<Contact>)DataWeave.Script.createScript('csvToContacts').execute(new Map<String,Object>{'records' => snake}).getValue();\n        System.assertEquals('Abel', snakeContacts.get(0).FirstName);\n        List<Contact> jsonContacts = (List<Contact>)DataWeave.Script.createScript('jsonToContacts').execute(new Map<String,Object>{'records' => '[{\"first_name\":\"Abel\",\"last_name\":\"Maclead\",\"email\":\"a.m@demo.org\"}]'}).getValue();\n        System.assertEquals('Maclead', jsonContacts.get(0).LastName);\n        \n        String renamedJSON = DataWeave.Script.createScript('csvToJsonWithFieldRenaming').execute(new Map<String,Object>{'payload' => 'first_name,last_name,company,address\\nAbel,Maclead,Acme,Street'}).getValueAsString();\n        List<Object> renamedList = (List<Object>)JSON.deserializeUntyped(renamedJSON);\n        Map<String,Object> renamed = (Map<String,Object>)renamedList.get(0);\n        System.assertEquals('Abel', renamed.get('FirstName'));\n        System.assertEquals('Street', renamed.get('MailingStreet'));\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRecipesOriginalProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToContacts.dwl"), "%dw 2.0\ninput records application/csv\noutput application/apex\n---\nrecords map(record) -> {\n    FirstName: record.first_name,\n    LastName: record.last_name,\n    Email: record.email\n} as Object {class: \"Contact\"}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToContacts.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonToContacts.dwl"), "%dw 2.0\ninput records application/json\noutput application/apex\n---\nrecords map(record) -> {\n    FirstName: record.first_name,\n    LastName: record.last_name,\n    Email: record.email\n} as Object {class: \"Contact\"}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonToContacts.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToJsonBasic.dwl"), "%dw 2.0 \ninput payload application/csv\noutput application/json\n--- \npayload")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToJsonBasic.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToJsonWithFieldRenaming.dwl"), "%dw 2.0 \ninput payload application/csv\noutput application/json\nfun renameKey(key: Key) = key match {\n    case \"first_name\" -> \"FirstName\"\n    case \"last_name\" -> \"LastName\"\n    case \"company\" -> \"Company\"\n    case \"phone1\" -> \"HomePhone\"\n    case \"phone\" -> \"Phone\"\n    case \"email\" -> \"Email\"\n    case \"date\" -> \"DateofBirth\"\n    case \"address\" -> \"MailingStreet\"\n    case \"city\" -> \"MailingCity\"\n    case \"county\" -> \"MailingCountry\"\n    case \"state\" -> \"MailingState\"\n    case \"zip\" -> \"MailingPostalCode\"\n    else -> (key)\n}\n--- \npayload map (contact) ->\ncontact mapObject (value, key) -> {\n    (renameKey(key)) : value\n}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/csvToJsonWithFieldRenaming.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierStringProof.cls"), "@IsTest\nprivate class GladeLegacyCarrierStringProof {\n    @IsTest static void isolatesOriginalCarrierAssertion() {\n        DataWeave.Script script = DataWeave.Script.createScript('helloWorld');\n        DataWeave.Result result = script.execute(new Map<String,Object>());\n        System.assertEquals('\"Hello World\"', result.getValueAsString());\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierStringProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl"), "%dw 2.0\n--- \nlog(\"Hello World\")")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRecordsListProof.cls"), "@IsTest\nprivate class GladeLegacyRecordsListProof {\n    @IsTest static void preservesOriginalStringListProjection() {\n        Map<String,Object> inputs = new Map<String,Object>{'records' => new List<String>{'a', 'b'}};\n        DataWeave.Result projected = DataWeave.Script.createScript('records').execute(inputs);\n        List<Object> values = (List<Object>)projected.getValue();\n        System.assertEquals(2, values.size());\n        System.assertEquals('a', values[0]);\n        System.assertEquals('b', values[1]);\n        \n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRecordsListProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNamespaceControlProof.cls"), "@IsTest\nprivate class GladeLegacyNamespaceControlProof {\n    @IsTest static void observesExplicitNamespaceWithValidExecuteSignature() {\n        Boolean caught = false;\n        try {\n            dataweave.Script namespaced = dataweave.Script.createScript('localNs', 'helloWorld');\n            namespaced.execute(new Map<String,Object>());\n            System.assert(false, 'Absent namespace must not resolve the unnamespaced resource');\n        } catch (System.NoDataFoundException error) {\n            caught = true;\n            System.assertEquals('System.NoDataFoundException', error.getTypeName());\n            System.assertEquals('Could not find DataWeave script helloWorld', error.getMessage());\n        }\n        System.assertEquals(true, caught);\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNamespaceControlProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDateSetupControlProof.cls"), "@IsTest\nprivate class GladeLegacyDateSetupControlProof {\n    @IsTest static void retainsExactFormattingWithPersistedCreatedDate() {\n        \n        Contact contact = new Contact(FirstName = 'John', LastName = 'Doe');\n        insert contact;\n        Test.setCreatedDate(contact.Id, Datetime.newInstanceGMT(2026, 5, 2, 12, 0, 0));\n        contact = [SELECT FirstName, LastName, CreatedDate FROM Contact WHERE Id = :contact.Id];\n        String jsonText = DataWeave.Script.createScript('jsonDateFormat')\n        \t.execute(new Map<String,Object>{'records' => new List<Contact>{contact}})\n        \t.getValueAsString();\n        String expected =\n        \t'{\\n' +\n        \t'  \"users\": [\\n' +\n        \t'    {\\n' +\n        \t'      \"firstName\": \"John\",\\n' +\n        \t'      \"lastName\": \"Doe\",\\n' +\n        \t'      \"createdDate\": \"12:00:00 PM, May 02, 2026\"\\n' +\n        \t'    }\\n' +\n        \t'  ]\\n' +\n        \t'}';\n        System.assertEquals(expected, jsonText);\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDateSetupControlProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonDateFormat.dwl"), "%dw 2.0\ninput records application/java\noutput application/json\n--- \n{\n    users: records map(record) -> {\n        firstName: record.FirstName,\n        lastName: record.LastName,\n        // https://docs.mulesoft.com/dataweave/2.4/dataweave-cookbook-format-dates\n        createdDate: (record.CreatedDate >> \"UTC\") as String {format: \"hh:mm:ss a, MMMM dd, uuuu\"} \n    }\n}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonDateFormat.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvCapitalizedProof.cls"), "@IsTest\nprivate class GladeLegacyCsvCapitalizedProof {\n    @IsTest static void preservesOriginalRecipeBlock() {\n        \n        String csv = 'first_name,last_name,email\\nAda,Lovelace,ada@example.test\\nGrace,Hopper,grace@example.test';\n        DataWeave.Result contactsResult = DataWeave.Script.createScript('csvToContacts').execute(new Map<String,Object>{'records' => csv});\n        List<Contact> contacts = (List<Contact>)contactsResult.getValue();\n        System.assertEquals(2, contacts.size());\n        System.assertEquals('Ada', contacts.get(0).FirstName);\n        System.assertEquals('Hopper', contacts.get(1).LastName);\n        \n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvCapitalizedProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvJsonProof.cls"), "@IsTest\nprivate class GladeLegacyCsvJsonProof {\n    @IsTest static void preservesOriginalRecipeBlock() {\n        \n        String csv = 'FirstName,LastName,Email\\nAda,Lovelace,ada@example.test\\nGrace,Hopper,grace@example.test';\n        String jsonText = DataWeave.Script.createScript('csvToJsonBasic').execute(new Map<String,Object>{'payload' => csv}).getValueAsString();\n        System.assert(jsonText.contains('\"FirstName\": \"Ada\",'));\n        List<Object> jsonList = (List<Object>)JSON.deserializeUntyped(jsonText);\n        System.assertEquals(2, jsonList.size());\n        Map<String,Object> first = (Map<String,Object>)jsonList.get(0);\n        System.assertEquals('Ada', first.get('FirstName'));\n        \n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvJsonProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvSnakeJsonProof.cls"), "@IsTest\nprivate class GladeLegacyCsvSnakeJsonProof {\n    @IsTest static void preservesOriginalRecipeBlock() {\n        String snake = 'first_name,last_name,email\\nAbel,Maclead,a.m@demo.org';\n        List<Contact> snakeContacts = (List<Contact>)DataWeave.Script.createScript('csvToContacts').execute(new Map<String,Object>{'records' => snake}).getValue();\n        System.assertEquals('Abel', snakeContacts.get(0).FirstName);\n        List<Contact> jsonContacts = (List<Contact>)DataWeave.Script.createScript('jsonToContacts').execute(new Map<String,Object>{'records' => '[{\"first_name\":\"Abel\",\"last_name\":\"Maclead\",\"email\":\"a.m@demo.org\"}]'}).getValue();\n        System.assertEquals('Maclead', jsonContacts.get(0).LastName);\n        \n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvSnakeJsonProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvRenamingProof.cls"), "@IsTest\nprivate class GladeLegacyCsvRenamingProof {\n    @IsTest static void preservesOriginalRecipeBlock() {\n        String renamedJSON = DataWeave.Script.createScript('csvToJsonWithFieldRenaming').execute(new Map<String,Object>{'payload' => 'first_name,last_name,company,address\\nAbel,Maclead,Acme,Street'}).getValueAsString();\n        List<Object> renamedList = (List<Object>)JSON.deserializeUntyped(renamedJSON);\n        Map<String,Object> renamed = (Map<String,Object>)renamedList.get(0);\n        System.assertEquals('Abel', renamed.get('FirstName'));\n        System.assertEquals('Street', renamed.get('MailingStreet'));\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCsvRenamingProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 12 || got.Passed != 12 {
			data, _ := json.Marshal(run)
			t.Fatalf("admitted legacy contract failed: %s", data)
		}
	})
	t.Run("c5-legacy-successor-nested66-runtime-error-v1", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNested66Proof.cls"), "@IsTest\nprivate class GladeLegacyNested66Proof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        Account account = new Account(Name = 'Acme');\n        insert account;\n        insert new Contact(AccountId = account.Id, LastName = 'Child');\n        List<Account> rows = [SELECT Id, (SELECT Id FROM Contacts) FROM Account WHERE Id = :account.Id];\n        Boolean caught = false;\n        try {\n        DataWeave.Result result = DataWeave.Script.createScript('records').execute(new Map<String,Object>{'records' => rows});\n        List<Account> transformed = (List<Account>) result.getValue();\n        System.assertEquals(1, transformed[0].Contacts.size());\n        System.assert(false, 'Expected API66 nested relation writer rejection');\n        } catch (System.DataWeaveScriptException error) {\n            caught = true;\n            System.assertEquals('System.DataWeaveScriptException', error.getTypeName());\n            System.assertEquals('Invalid type: \\\"Map_Wrapper\\\", while writing application/apex at records.', error.getMessage());\n        }\n        System.assertEquals(true, caught);\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyNested66Proof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/records.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/records.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"66.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 {
			data, _ := json.Marshal(run)
			t.Fatalf("admitted legacy contract failed: %s", data)
		}
	})
	t.Run("c5-legacy-successor-runner-runtime65-corrected-v1", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRunnerOriginalProof.cls"), "@IsTest\nprivate class GladeLegacyRunnerOriginalProof {\n    @IsTest static void staticResourceExecuteReturnsScriptOutput() {\n        \n            System.assertEquals('Hello World', DataWeaveHarness.staticInvocation());\n          \n    }\n    @IsTest static void dynamicCreateScriptThrowsScriptException() {\n        \n            try {\n              DataWeaveHarness.dynamicError();\n              System.assert(false, 'expected exception');\n            } catch (Exception ex) {\n              System.assertEquals('System.DataWeaveScriptException', ex.getTypeName());\n              System.assert(ex.getMessage().startsWith('Division by zero'));\n            }\n          \n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyRunnerOriginalProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/DataWeaveHarness.cls"), "\npublic class DataWeaveHarness {\n  public static String staticInvocation() {\n    DataWeave.Script script = new DataWeaveScriptResource.helloWorld();\n    return script.execute(new Map<String, Object>()).getValueAsString();\n  }\n\n  public static void dynamicError() {\n    DataWeave.Script script = DataWeave.Script.createScript('error');\n    script.execute(new Map<String, Object>());\n  }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/DataWeaveHarness.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl"), "%dw 2.0\noutput text/plain\n---\n\"Hello World\"")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/error.dwl"), "%dw 2.0 \noutput application/json\n--- \n1/0")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/error.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 2 || got.Passed != 2 {
			data, _ := json.Marshal(run)
			t.Fatalf("admitted legacy contract failed: %s", data)
		}
	})
	t.Run("c5-legacy-excel", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyExcelProof.cls"), "@IsTest\nprivate class GladeLegacyExcelProof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        try {\n        \tDataWeave.Script.createScript('excelOutputError').execute(new Map<String,Object>{'records' => new List<Contact>{new Contact(FirstName = 'John', LastName = 'Doe')}});\n        \tSystem.assert(false, 'expected DataWeaveScriptException');\n        } catch (Exception ex) {\n        \tAssert.isInstanceOfType(ex, DataWeaveScriptException.class);\n        \tSystem.assert(ex.getMessage().contains('application/xlsx'));\n        }\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyExcelProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/excelOutputError.dwl"), "%dw 2.0 \ninput records application/java\n// Excel Format support https://docs.mulesoft.com/dataweave/2.4/dataweave-formats-excel\n// Note that Excel is not currently supported for DW in Apex\noutput application/xlsx\n--- \nrecords")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/excelOutputError.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 {
			data, _ := json.Marshal(run)
			t.Fatalf("admitted legacy contract failed: %s", data)
		}
	})
	t.Run("c5-legacy-carrier-noargs", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierNoargsProof.cls"), "@IsTest\nprivate class GladeLegacyCarrierNoargsProof {\n    @IsTest static void isolatesOriginalCarrierAssertion() {\n        DataWeave.Script script = DataWeave.Script.createScript('helloWorld');\n        DataWeave.Result result = script.execute(new Map<String,Object>());\n        System.assertEquals('\"Hello World\"', script.execute().getValueAsString());\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierNoargsProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl"), "%dw 2.0\n--- \nlog(\"Hello World\")")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 {
			data, _ := json.Marshal(run)
			t.Fatalf("admitted legacy contract failed: %s", data)
		}
	})
}

func TestRunC5LegacyRejected(t *testing.T) {
	t.Run("c5-legacy-carrier-field", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierFieldProof.cls"), "@IsTest\nprivate class GladeLegacyCarrierFieldProof {\n    @IsTest static void isolatesOriginalCarrierAssertion() {\n        DataWeave.Script script = DataWeave.Script.createScript('helloWorld');\n        DataWeave.Result result = script.execute(new Map<String,Object>());\n        System.assertEquals('\"Hello World\"', (String)result.valueAsString);\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierFieldProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl"), "%dw 2.0\n--- \nlog(\"Hello World\")")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.CompileErrors != 1 || got.Passed != 0 || got.Failed != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("Salesforce-rejected construct executed or was lost: %s", data)
		}
		if problem := firstRunProblem(run); !strings.Contains(problem, "valueAsString") {
			t.Fatalf("unrelated compile error: %s", problem)
		}
	})
	t.Run("c5-legacy-carrier-mime", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierMimeProof.cls"), "@IsTest\nprivate class GladeLegacyCarrierMimeProof {\n    @IsTest static void isolatesOriginalCarrierAssertion() {\n        DataWeave.Script script = DataWeave.Script.createScript('helloWorld');\n        DataWeave.Result result = script.execute(new Map<String,Object>());\n        System.assertEquals('text/plain', result.getMimeType());\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyCarrierMimeProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl"), "%dw 2.0\n--- \nlog(\"Hello World\")")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/helloWorld.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.CompileErrors != 1 || got.Passed != 0 || got.Failed != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("Salesforce-rejected construct executed or was lost: %s", data)
		}
		if problem := firstRunProblem(run); !strings.Contains(problem, "getMimeType") {
			t.Fatalf("unrelated compile error: %s", problem)
		}
	})
	t.Run("c5-legacy-date-original", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDateOriginalProof.cls"), "@IsTest\nprivate class GladeLegacyDateOriginalProof {\n    @IsTest static void preservesOriginalAssertions() {\n        \n        Contact contact = new Contact(FirstName = 'John', LastName = 'Doe');\n        contact.CreatedDate = Datetime.newInstanceGMT(2026, 5, 2, 12, 0, 0);\n        String jsonText = DataWeave.Script.createScript('jsonDateFormat')\n        \t.execute(new Map<String,Object>{'records' => new List<Contact>{contact}})\n        \t.getValueAsString();\n        String expected =\n        \t'{\\n' +\n        \t'  \"users\": [\\n' +\n        \t'    {\\n' +\n        \t'      \"firstName\": \"John\",\\n' +\n        \t'      \"lastName\": \"Doe\",\\n' +\n        \t'      \"createdDate\": \"12:00:00 PM, May 02, 2026\"\\n' +\n        \t'    }\\n' +\n        \t'  ]\\n' +\n        \t'}';\n        System.assertEquals(expected, jsonText);\n    }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeLegacyDateOriginalProof.cls-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonDateFormat.dwl"), "%dw 2.0\ninput records application/java\noutput application/json\n--- \n{\n    users: records map(record) -> {\n        firstName: record.FirstName,\n        lastName: record.LastName,\n        // https://docs.mulesoft.com/dataweave/2.4/dataweave-cookbook-format-dates\n        createdDate: (record.CreatedDate >> \"UTC\") as String {format: \"hh:mm:ss a, MMMM dd, uuuu\"} \n    }\n}")
		writeFile(t, filepath.Join(root, "force-app/main/default/dw/jsonDateFormat.dwl-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<DataWeaveResource\n    xmlns=\"http://soap.sforce.com/2006/04/metadata\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n>\n    <content xsi:nil=\"true\" />\n    <apiVersion>62.0</apiVersion>\n    <isGlobal>false</isGlobal>\n    <isProtected>false</isProtected>\n</DataWeaveResource>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\n  \"sourceApiVersion\": \"65.0\",\n  \"packageDirectories\": [\n    {\n      \"path\": \"force-app\",\n      \"default\": true\n    }\n  ]\n}\n")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.CompileErrors != 1 || got.Passed != 0 || got.Failed != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("Salesforce-rejected construct executed or was lost: %s", data)
		}
		if problem := firstRunProblem(run); !strings.Contains(problem, "CreatedDate") {
			t.Fatalf("unrelated compile error: %s", problem)
		}
	})
}

func TestRunC5QueryProvenanceAdmitted(t *testing.T) {
	home := os.Getenv("GLADE_DATAWEAVE_APEX_TEST_HOME")
	if home == "" {
		t.Fatal("query provenance acceptance requires explicit installed DataWeave toolchain")
	}
	t.Setenv("GLADE_HOME", home)
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65identity.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65identity.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65ignore.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\n7\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65ignore.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65mapChildren.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords flatMap ((record) -> record.Contacts map ((child) -> child.LastName))\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery65mapChildren.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeQueryProvenance65.cls"), "@IsTest private class GladeQueryProvenance65 {\n@IsTest static void identityPreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; Boolean caught=false; try { Object output=DataWeave.Script.createScript('ownedQuery65identity').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assert(false,'Expected query relationship writer error'); } catch(System.DataWeaveScriptException error) { caught=true; System.assertEquals('System.DataWeaveScriptException',error.getTypeName()); } System.assertEquals(true,caught); }\n@IsTest static void ignorePreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; Object output=DataWeave.Script.createScript('ownedQuery65ignore').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assertEquals(7,output); }\n@IsTest static void mapChildrenPreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; List<Object> output=(List<Object>)DataWeave.Script.createScript('ownedQuery65mapChildren').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assertEquals(1,output.size()); System.assertEquals('Owned Child',output[0]); }\n}\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeQueryProvenance65.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>65.0</apiVersion><status>Active</status></ApexClass>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66identity.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66identity.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66ignore.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\n7\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66ignore.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66mapChildren.dwl"), "%dw 2.0\ninput records application/java\noutput application/apex\n---\nrecords flatMap ((record) -> record.Contacts map ((child) -> child.LastName))\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/dw/ownedQuery66mapChildren.dwl-meta.xml"), "<DataWeaveResource xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><isGlobal>false</isGlobal></DataWeaveResource>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeQueryProvenance66.cls"), "@IsTest private class GladeQueryProvenance66 {\n@IsTest static void identityPreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; Boolean caught=false; try { Object output=DataWeave.Script.createScript('ownedQuery66identity').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assert(false,'Expected query relationship writer error'); } catch(System.DataWeaveScriptException error) { caught=true; System.assertEquals('System.DataWeaveScriptException',error.getTypeName()); } System.assertEquals(true,caught); }\n@IsTest static void ignorePreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; Object output=DataWeave.Script.createScript('ownedQuery66ignore').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assertEquals(7,output); }\n@IsTest static void mapChildrenPreservesQueryContract() { Account parent = new Account(Name='Owned Parent'); insert parent; insert new Contact(AccountId=parent.Id,LastName='Owned Child'); List<Account> rows = [SELECT Id, Name, (SELECT Id, LastName FROM Contacts) FROM Account WHERE Id = :parent.Id]; List<Object> output=(List<Object>)DataWeave.Script.createScript('ownedQuery66mapChildren').execute(new Map<String,Object>{'records'=>rows}).getValue(); System.assertEquals(1,output.size()); System.assertEquals('Owned Child',output[0]); }\n}\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeQueryProvenance66.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><status>Active</status></ApexClass>\n")
	writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"66.0\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
	result := Run(loadTestIndex(t, root), Options{})
	if got := result.Summary(); got.Total != 6 || got.Passed != 6 || got.Failed != 0 || got.CompileErrors != 0 || got.Skipped != 0 {
		t.Fatalf("query provenance: %+v first=%s", result, firstRunProblem(result))
	}
}
