package apextest

import (
	"encoding/json"
	"path/filepath"
	"testing"
)

// Exact corrected API66 CMT query and row accounting proof admitted by SF162.
func TestCMTQueryLimitsAPI66Proof(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeCmtLimits66CorrectedProof.cls"), "@IsTest private class GladeCmtLimits66CorrectedProof {\n    @IsTest static void ordinaryProjectionPopulated() {\n        Integer queriesBefore = Limits.getQueries();\n        Integer rowsBefore = Limits.getQueryRows();\n        List<SObject> rows = Database.query('SELECT DeveloperName FROM LookupRollupSummary2__mdt WHERE DeveloperName = \\'GladeQueryLimitProbe\\'');\n        System.assertEquals(1, rows.size());\n        System.assertEquals(0, Limits.getQueries() - queriesBefore);\n        System.assertEquals(1, Limits.getQueryRows() - rowsBefore);\n    }\n    @IsTest static void ordinaryProjectionEmpty() {\n        Integer queriesBefore = Limits.getQueries();\n        Integer rowsBefore = Limits.getQueryRows();\n        List<SObject> rows = Database.query('SELECT DeveloperName FROM LookupRollupSummary2__mdt WHERE DeveloperName = \\'GladeMissingQueryLimitProbe\\'');\n        System.assertEquals(0, rows.size());\n        System.assertEquals(0, Limits.getQueries() - queriesBefore);\n        System.assertEquals(0, Limits.getQueryRows() - rowsBefore);\n    }\n    @IsTest static void longTextProjectionPopulated() {\n        Integer queriesBefore = Limits.getQueries();\n        Integer rowsBefore = Limits.getQueryRows();\n        List<SObject> rows = Database.query('SELECT DeveloperName, TestCode2__c, TestCodeParent__c FROM LookupRollupSummary2__mdt WHERE DeveloperName = \\'GladeQueryLimitProbe\\'');\n        System.assertEquals(1, rows.size());\n        System.assertEquals(1, Limits.getQueries() - queriesBefore);\n        System.assertEquals(1, Limits.getQueryRows() - rowsBefore);\n        System.assertEquals(300, ((String)rows[0].get('TestCode2__c')).length());\n        System.assertEquals('parent', rows[0].get('TestCodeParent__c'));\n    }\n    @IsTest static void longTextProjectionEmpty() {\n        Integer queriesBefore = Limits.getQueries();\n        Integer rowsBefore = Limits.getQueryRows();\n        List<SObject> rows = Database.query('SELECT DeveloperName, TestCode2__c, TestCodeParent__c FROM LookupRollupSummary2__mdt WHERE DeveloperName = \\'GladeMissingQueryLimitProbe\\'');\n        System.assertEquals(0, rows.size());\n        System.assertEquals(1, Limits.getQueries() - queriesBefore);\n        System.assertEquals(0, Limits.getQueryRows() - rowsBefore);\n    }\n}\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeCmtLimits66CorrectedProof.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>66.0</apiVersion><status>Active</status></ApexClass>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/LookupRollupSummary2__mdt/LookupRollupSummary2__mdt.object-meta.xml"), "<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><label>Lookup Rollup Summary</label><pluralLabel>Lookup Rollup Summaries</pluralLabel><visibility>Public</visibility></CustomObject>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/LookupRollupSummary2__mdt/fields/TestCode2__c.field-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n    <fullName>TestCode2__c</fullName>\n    <externalId>false</externalId>\n    <fieldManageability>DeveloperControlled</fieldManageability>\n    <inlineHelpText\n  >This tool utilises a dynamically generated Apex Trigger and by default a generated Apex Test. Use this field if instructed by a developer to replace the generated test code. See Wiki on GitHub.</inlineHelpText>\n    <label>Test Code (Child Object)</label>\n    <length>131072</length>\n    <type>LongTextArea</type>\n    <visibleLines>8</visibleLines>\n</CustomField>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/LookupRollupSummary2__mdt/fields/TestCodeParent__c.field-meta.xml"), "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n    <fullName>TestCodeParent__c</fullName>\n    <externalId>false</externalId>\n    <fieldManageability>SubscriberControlled</fieldManageability>\n    <inlineHelpText\n  >This tool utilises a dynamically generated Apex Trigger and by default a generated Apex Test. Use this field if instructed by a developer to replace the generated test code. See Wiki on GitHub. May not be required, observe Manage Child Trigger page.</inlineHelpText>\n    <label>Test Code (Parent Object)</label>\n    <length>131072</length>\n    <type>LongTextArea</type>\n    <visibleLines>8</visibleLines>\n</CustomField>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/customMetadata/LookupRollupSummary2.GladeQueryLimitProbe.md-meta.xml"), "<CustomMetadata xmlns=\"http://soap.sforce.com/2006/04/metadata\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><label>Glade Query Limit Probe</label><protected>false</protected><values><field>TestCode2__c</field><value xsi:type=\"xsd:string\">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</value></values><values><field>TestCodeParent__c</field><value xsi:type=\"xsd:string\">parent</value></values></CustomMetadata>\n")
	writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"66.0\", \"namespace\": \"\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
	run := Run(loadTestIndex(t, root), Options{NoDiskCache: true})
	data, _ := json.Marshal(run)
	t.Logf("report: %s", data)
	if got := run.Summary(); got.Total != 4 || got.Passed != 4 || got.Errors != 0 || got.Skipped != 0 {
		t.Fatalf("CMT proof: %s", data)
	}
}
