package apextest

import (
	"encoding/json"
	"path/filepath"
	"testing"
)

// Waves79/80/83 passed these API53 formula-field contracts.
// The blank-field successor controls Account.Type explicitly across orgs.
func TestRunNullValueFormulaContracts(t *testing.T) {
	t.Run("gladeaccountformula53-api53", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeAccountFormula53.cls"), "@IsTest private class GladeAccountFormula53 {\n @IsTest static void populatedParentValues(){\n  Account parent=new Account(Name='Owned formula parent');insert parent;\n  Contact child=new Contact(LastName='Owned formula child',AccountId=parent.Id);insert child;\n  List<String> expected=new List<String>{'One-to-One Individual','Household Account','Bucket Individual'};\n  for(String value:expected){\n   parent.SYSTEM_AccountType__c=value;update parent;\n   Contact queried=[SELECT Organization_Type__c,Account.SYSTEM_AccountType__c FROM Contact WHERE Id=:child.Id];\n   System.assertEquals(value,queried.Account.SYSTEM_AccountType__c,'stored parent value');\n   System.assertEquals(value,queried.Organization_Type__c,'original formula nonempty result');\n  }\n }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeAccountFormula53.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>53.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Account/fields/SYSTEM_AccountType__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n        <fullName>SYSTEM_AccountType__c</fullName>\n        <description>Hidden system field: do not change.  Updated by automatic processes.</description>\n        <externalId>false</externalId>\n        <inlineHelpText>Indicates which Account Model this account is for: Household Account, One-to-One, or Individual (bucket).</inlineHelpText>\n        <label>_SYSTEM: AccountType</label>\n        <length>100</length>\n        <required>false</required>\n        <trackFeedHistory>false</trackFeedHistory>\n        <type>Text</type>\n        <unique>false</unique>\n    </CustomField>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Contact/fields/Organization_Type__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n        <fullName>Organization_Type__c</fullName>\n        <description>Formula: In order of preference, the SYSTEM_AccountType field, the Account Type field, and \"Organization\".</description>\n        <externalId>false</externalId>\n        <formula>NULLVALUE(IF( Account.SYSTEM_AccountType__c==\"\", TEXT(Account.Type),Account.SYSTEM_AccountType__c),\"Organization\" )</formula>\n        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>\n        <inlineHelpText>Formula: In order of preference, the SYSTEM_AccountType field, the Account Type field, and \"Organization\".</inlineHelpText>\n        <label>Organization Type</label>\n        <required>false</required>\n        <type>Text</type>\n        <unique>false</unique>\n    </CustomField>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"53.0\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 || got.Skipped != 0 || got.Failed != 0 || got.Errors != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("NULLVALUE contracts failed: %s", data)
		}
	})
	t.Run("account-formula-blank-exact-api53", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeAccountFormulaBlank53.cls"), "@IsTest private class GladeAccountFormulaBlank53 {\n private static void observe(List<Object> rows,String phase,Contact child){\n  Contact queried=[SELECT Organization_Type__c,AccountId,Account.SYSTEM_AccountType__c,Account.Type FROM Contact WHERE Id=:child.Id];\n  rows.add(new Map<String,Object>{'phase'=>phase,'hasParent'=>queried.AccountId!=null,'parentText'=>queried.Account==null?null:queried.Account.SYSTEM_AccountType__c,'parentType'=>queried.Account==null?null:queried.Account.Type,'result'=>queried.Organization_Type__c});\n }\n @IsTest static void blankAndTypeFallback(){\n  List<Object> rows=new List<Object>();\n  Contact orphan=new Contact(LastName='Owned formula orphan');insert orphan;observe(rows,'no-parent',orphan);\n  Account parent=new Account(Name='Owned formula parent');insert parent;\n  Contact child=new Contact(LastName='Owned formula child',AccountId=parent.Id);insert child;observe(rows,'null-parent-fields',child);\n  parent.SYSTEM_AccountType__c='';update parent;observe(rows,'empty-parent-text',child);\n  String selectedType;\n  for(Schema.PicklistEntry entry:Account.Type.getDescribe().getPicklistValues())if(entry.isActive()&&entry.getValue()=='Prospect')selectedType=entry.getValue();\n  System.assertNotEquals(null,selectedType,'Active Account.Type Prospect prerequisite');\n  parent.Type=selectedType;update parent;observe(rows,'type-fallback',child);\n  System.assertEquals(4,rows.size(),'complete phases');\n  List<Object> expected=(List<Object>)JSON.deserializeUntyped('[{\"result\":null,\"parentType\":null,\"parentText\":null,\"hasParent\":false,\"phase\":\"no-parent\"},{\"result\":null,\"parentType\":null,\"parentText\":null,\"hasParent\":true,\"phase\":\"null-parent-fields\"},{\"result\":null,\"parentType\":null,\"parentText\":null,\"hasParent\":true,\"phase\":\"empty-parent-text\"},{\"result\":\"Prospect\",\"parentType\":\"Prospect\",\"parentText\":null,\"hasParent\":true,\"phase\":\"type-fallback\"}]');\n  for(Integer i=0;i<expected.size();i++){\n   Map<String,Object> want=(Map<String,Object>)expected[i];Map<String,Object> actual=(Map<String,Object>)rows[i];\n   String label='blank formula phase '+i;\n   System.assertEquals(want.keySet(),actual.keySet(),label+': complete fields');\n   for(String key:want.keySet())System.assertEquals(want.get(key),actual.get(key),label+': '+key);\n  }\n }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeAccountFormulaBlank53.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>53.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Account/fields/SYSTEM_AccountType__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n        <fullName>SYSTEM_AccountType__c</fullName>\n        <description>Hidden system field: do not change.  Updated by automatic processes.</description>\n        <externalId>false</externalId>\n        <inlineHelpText>Indicates which Account Model this account is for: Household Account, One-to-One, or Individual (bucket).</inlineHelpText>\n        <label>_SYSTEM: AccountType</label>\n        <length>100</length>\n        <required>false</required>\n        <trackFeedHistory>false</trackFeedHistory>\n        <type>Text</type>\n        <unique>false</unique>\n    </CustomField>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Contact/fields/Organization_Type__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\">\n        <fullName>Organization_Type__c</fullName>\n        <description>Formula: In order of preference, the SYSTEM_AccountType field, the Account Type field, and \"Organization\".</description>\n        <externalId>false</externalId>\n        <formula>NULLVALUE(IF( Account.SYSTEM_AccountType__c==\"\", TEXT(Account.Type),Account.SYSTEM_AccountType__c),\"Organization\" )</formula>\n        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>\n        <inlineHelpText>Formula: In order of preference, the SYSTEM_AccountType field, the Account Type field, and \"Organization\".</inlineHelpText>\n        <label>Organization Type</label>\n        <required>false</required>\n        <type>Text</type>\n        <unique>false</unique>\n    </CustomField>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"53.0\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 || got.Skipped != 0 || got.Failed != 0 || got.Errors != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("NULLVALUE contracts failed: %s", data)
		}
	})
	t.Run("numeric-nullvalue-fallback-api53", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeNumericNullValue53.cls"), "@IsTest private class GladeNumericNullValue53 {\n private static void assertStored(Id rowId,Decimal expectedInput,Decimal expectedResult){\n  Account row=[SELECT GladeNullInput53__c,GladeNullResult53__c FROM Account WHERE Id=:rowId];\n  System.assertEquals(expectedInput,row.GladeNullInput53__c,'stored numeric input');\n  System.assertEquals(expectedResult,row.GladeNullResult53__c,'NULLVALUE BlankAsBlank result');\n }\n @IsTest static void numericNullZeroAndNonzero(){\n  Account row=new Account(Name='Owned numeric NULLVALUE',GladeNullInput53__c=null);insert row;\n  assertStored(row.Id,null,47);\n  row.GladeNullInput53__c=0;update row;assertStored(row.Id,0,0);\n  row.GladeNullInput53__c=12.5;update row;assertStored(row.Id,12.5,12.5);\n }\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeNumericNullValue53.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>53.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Account/fields/GladeNullInput53__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>GladeNullInput53__c</fullName><label>Glade Null Input</label><type>Number</type><precision>18</precision><scale>2</scale><required>false</required></CustomField>\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/objects/Account/fields/GladeNullResult53__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>GladeNullResult53__c</fullName><label>Glade Null Result</label><type>Number</type><precision>18</precision><scale>2</scale><formula>NULLVALUE(GladeNullInput53__c,47)</formula><formulaTreatBlanksAs>BlankAsBlank</formulaTreatBlanksAs></CustomField>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"53.0\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 1 || got.Passed != 1 || got.Skipped != 0 || got.Failed != 0 || got.Errors != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("NULLVALUE contracts failed: %s", data)
		}
	})
}
