package apextest

import (
	"encoding/json"
	"path/filepath"
	"testing"
)

// Exact accepted field-assignment packets; namespace behavior is not proven.
func TestPricebookEntryAssignmentOriginalVersions(t *testing.T) {
	t.Run("glade-pricebook-entry-create-assignment-original-versions-assignment-error", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37.cls"), "@IsTest private class GladePricebookAssign37 {\nprivate static PricebookEntry makeEntry() {\n Product2 product = new Product2(Name='proof product', IsActive=true); insert product;\n PricebookEntry pbe = new PricebookEntry();\n pbe.UnitPrice = 10; pbe.IsActive = true; pbe.UseStandardPrice = false;\n pbe.Pricebook2Id = Test.getStandardPricebookId(); pbe.Product2Id = product.Id;\n insert pbe; return pbe;\n}\n@IsTest static void transientAssignmentInsert() {\n PricebookEntry pbe=makeEntry();\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice,IsActive,UseStandardPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n System.assertEquals(true,saved.IsActive); System.assertEquals(false,saved.UseStandardPrice);\n}\n@IsTest static void changedPricebookUpdateRejected() {\n PricebookEntry pbe=makeEntry(); Pricebook2 other=new Pricebook2(Name='other book',IsActive=true); insert other;\n Boolean rejected=false; try { pbe.Pricebook2Id=other.Id; } catch(SObjectException e) { rejected=true; System.assertEquals('System.SObjectException',e.getTypeName()); System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage()); } System.assertEquals(true,rejected); System.assertEquals(Test.getStandardPricebookId(),pbe.Pricebook2Id);\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n}\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>37.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"43.0\", \"namespace\": \"\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 2 || got.Passed != 2 || got.Failed != 0 || got.Errors != 0 || got.Skipped != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("assignment proof: %s", data)
		}
	})
	t.Run("glade-pricebook-entry-create-assignment-original-versions-api52-project64-assignment-error", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign52.cls"), "@IsTest private class GladePricebookAssign52 {\nprivate static PricebookEntry makeEntry() {\n Product2 product = new Product2(Name='proof product', IsActive=true); insert product;\n PricebookEntry pbe = new PricebookEntry();\n pbe.UnitPrice = 10; pbe.IsActive = true; pbe.UseStandardPrice = false;\n pbe.Pricebook2Id = Test.getStandardPricebookId(); pbe.Product2Id = product.Id;\n insert pbe; return pbe;\n}\n@IsTest static void transientAssignmentInsert() {\n PricebookEntry pbe=makeEntry();\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice,IsActive,UseStandardPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n System.assertEquals(true,saved.IsActive); System.assertEquals(false,saved.UseStandardPrice);\n}\n@IsTest static void changedPricebookUpdateRejected() {\n PricebookEntry pbe=makeEntry(); Pricebook2 other=new Pricebook2(Name='other book',IsActive=true); insert other;\n Boolean rejected=false; try { pbe.Pricebook2Id=other.Id; } catch(SObjectException e) { rejected=true; System.assertEquals('System.SObjectException',e.getTypeName()); System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage()); } System.assertEquals(true,rejected); System.assertEquals(Test.getStandardPricebookId(),pbe.Pricebook2Id);\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n}\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign52.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>52.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"64.0\", \"namespace\": \"proofpkg\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 2 || got.Passed != 2 || got.Failed != 0 || got.Errors != 0 || got.Skipped != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("assignment proof: %s", data)
		}
	})
	t.Run("glade-pricebook-entry-create-assignment-original-versions-api37-package44-assignment-error", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37Pkg44.cls"), "@IsTest private class GladePricebookAssign37Pkg44 {\nprivate static PricebookEntry makeEntry() {\n Product2 product = new Product2(Name='proof product', IsActive=true); insert product;\n PricebookEntry pbe = new PricebookEntry();\n pbe.UnitPrice = 10; pbe.IsActive = true; pbe.UseStandardPrice = false;\n pbe.Pricebook2Id = Test.getStandardPricebookId(); pbe.Product2Id = product.Id;\n insert pbe; return pbe;\n}\n@IsTest static void transientAssignmentInsert() {\n PricebookEntry pbe=makeEntry();\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice,IsActive,UseStandardPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n System.assertEquals(true,saved.IsActive); System.assertEquals(false,saved.UseStandardPrice);\n}\n@IsTest static void changedPricebookUpdateRejected() {\n PricebookEntry pbe=makeEntry(); Pricebook2 other=new Pricebook2(Name='other book',IsActive=true); insert other;\n Boolean rejected=false; try { pbe.Pricebook2Id=other.Id; } catch(SObjectException e) { rejected=true; System.assertEquals('System.SObjectException',e.getTypeName()); System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage()); } System.assertEquals(true,rejected); System.assertEquals(Test.getStandardPricebookId(),pbe.Pricebook2Id);\n PricebookEntry saved=[SELECT Pricebook2Id,Product2Id,UnitPrice FROM PricebookEntry WHERE Id=:pbe.Id];\n System.assertEquals(Test.getStandardPricebookId(),saved.Pricebook2Id);\n System.assertEquals(pbe.Product2Id,saved.Product2Id); System.assertEquals(10,saved.UnitPrice);\n}\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37Pkg44.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>37.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"44.0\", \"namespace\": \"\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 2 || got.Passed != 2 || got.Failed != 0 || got.Errors != 0 || got.Skipped != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("assignment proof: %s", data)
		}
	})
}

// Exact API37/52 sparse, synthetic-ID, and queried receiver contracts.
func TestPricebookEntryAssignmentIDStatesOriginalVersions(t *testing.T) {
	t.Run("glade-pricebook-assignment-id-state-api37", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37State.cls"), "@IsTest private class GladePricebookAssign37State {\nprivate static PricebookEntry makeEntry() {\n Product2 product = new Product2(Name='proof product', IsActive=true); insert product;\n PricebookEntry pbe = new PricebookEntry();\n pbe.UnitPrice = 10; pbe.IsActive = true; pbe.UseStandardPrice = false;\n pbe.Pricebook2Id = Test.getStandardPricebookId(); pbe.Product2Id = product.Id;\n insert pbe; return pbe;\n}\n@IsTest static void sparseExistingId(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=new PricebookEntry(Id=saved.Id);Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n@IsTest static void fakeId(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=new PricebookEntry(Id=(Id)'01u000000000001');Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n@IsTest static void queriedRecord(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=[SELECT Id,Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id];Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign37State.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>37.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"43.0\", \"namespace\": \"\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 3 || got.Passed != 3 || got.Failed != 0 || got.Errors != 0 || got.Skipped != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("assignment state proof: %s", data)
		}
	})
	t.Run("glade-pricebook-assignment-id-state-api52", func(t *testing.T) {
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign52State.cls"), "@IsTest private class GladePricebookAssign52State {\nprivate static PricebookEntry makeEntry() {\n Product2 product = new Product2(Name='proof product', IsActive=true); insert product;\n PricebookEntry pbe = new PricebookEntry();\n pbe.UnitPrice = 10; pbe.IsActive = true; pbe.UseStandardPrice = false;\n pbe.Pricebook2Id = Test.getStandardPricebookId(); pbe.Product2Id = product.Id;\n insert pbe; return pbe;\n}\n@IsTest static void sparseExistingId(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=new PricebookEntry(Id=saved.Id);Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n@IsTest static void fakeId(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=new PricebookEntry(Id=(Id)'01u000000000001');Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n@IsTest static void queriedRecord(){PricebookEntry saved=makeEntry(); Pricebook2 other=new Pricebook2(Name='other',IsActive=true);insert other;PricebookEntry row=[SELECT Id,Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id];Id previous=row.Pricebook2Id;Boolean rejected=false;try{row.Pricebook2Id=other.Id;}catch(SObjectException e){rejected=true;System.assertEquals('Field is not writeable: PricebookEntry.Pricebook2Id',e.getMessage());}System.assertEquals(true,rejected);System.assertEquals(previous,row.Pricebook2Id);System.assertEquals(Test.getStandardPricebookId(),[SELECT Pricebook2Id FROM PricebookEntry WHERE Id=:saved.Id].Pricebook2Id);}\n}\n")
		writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladePricebookAssign52State.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>52.0</apiVersion><status>Active</status></ApexClass>\n")
		writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"64.0\", \"namespace\": \"proofpkg\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
		run := Run(loadTestIndex(t, root), Options{})
		if got := run.Summary(); got.Total != 3 || got.Passed != 3 || got.Failed != 0 || got.Errors != 0 || got.Skipped != 0 {
			data, _ := json.Marshal(run)
			t.Fatalf("assignment state proof: %s", data)
		}
	})
}
