package apextest

import (
	"encoding/json"
	"path/filepath"
	"testing"
)

// Original four API53 relationship projection discriminators; source and metadata unchanged.
func TestRunRelationshipProjectionCaseContracts(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/GladeCaseObject53__mdt/GladeCaseObject53__mdt.object-meta.xml"), "<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><label>Case Object</label><pluralLabel>Case Objects</pluralLabel><visibility>Public</visibility></CustomObject>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/GladeCaseField53__mdt/GladeCaseField53__mdt.object-meta.xml"), "<CustomObject xmlns=\"http://soap.sforce.com/2006/04/metadata\"><label>Case Field</label><pluralLabel>Case Fields</pluralLabel><visibility>Public</visibility></CustomObject>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/GladeCaseObject53__mdt/fields/Object_API_Name__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Object_API_Name__c</fullName><label>Object API Name</label><type>Text</type><length>80</length><fieldManageability>DeveloperControlled</fieldManageability></CustomField>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/GladeCaseObject53__mdt/fields/Legacy_Data_Import_Object_Name__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Legacy_Data_Import_Object_Name__c</fullName><label>Legacy Data Import Object Name</label><type>Text</type><length>80</length><fieldManageability>DeveloperControlled</fieldManageability></CustomField>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/objects/GladeCaseField53__mdt/fields/Target_Object_Mapping__c.field-meta.xml"), "<CustomField xmlns=\"http://soap.sforce.com/2006/04/metadata\"><fullName>Target_Object_Mapping__c</fullName><label>Target Object Mapping</label><type>MetadataRelationship</type><referenceTo>GladeCaseObject53__mdt</referenceTo><relationshipLabel>Case Fields</relationshipLabel><relationshipName>Case_Fields</relationshipName><required>true</required><fieldManageability>DeveloperControlled</fieldManageability></CustomField>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/customMetadata/GladeCaseObject53.Parent.md-meta.xml"), "<CustomMetadata xmlns=\"http://soap.sforce.com/2006/04/metadata\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><label>Parent</label><protected>false</protected><values><field>Object_API_Name__c</field><value xsi:type=\"xsd:string\">Account</value></values><values><field>Legacy_Data_Import_Object_Name__c</field><value xsi:type=\"xsd:string\">Account1</value></values></CustomMetadata>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/customMetadata/GladeCaseField53.Child.md-meta.xml"), "<CustomMetadata xmlns=\"http://soap.sforce.com/2006/04/metadata\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"><label>Child</label><protected>false</protected><values><field>Target_Object_Mapping__c</field><value xsi:type=\"xsd:string\">Parent</value></values></CustomMetadata>\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeCaseProjection53.cls"), "@IsTest private class GladeCaseProjection53 {\n private static void checkValues(GladeCaseField53__mdt row) {\n  System.assertEquals('Account',row.Target_Object_Mapping__r.Object_API_Name__c);\n  System.assertEquals('Account1',row.Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c);\n  System.assertEquals('Parent',row.Target_Object_Mapping__r.DeveloperName);\n }\n @IsTest static void metadataCanonicalCase() {\n  GladeCaseField53__mdt row=[SELECT Target_Object_Mapping__r.Object_API_Name__c,Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c,Target_Object_Mapping__r.DeveloperName FROM GladeCaseField53__mdt WHERE DeveloperName='Child'];\n  checkValues(row);\n }\n @IsTest static void metadataMixedProjectionCase() {\n  GladeCaseField53__mdt row=[SELECT Target_Object_Mapping__r.Object_API_Name__c,Target_Object_Mapping__r.DeveloperName,Target_OBject_Mapping__r.Legacy_Data_Import_Object_Name__c FROM GladeCaseField53__mdt WHERE DeveloperName='Child'];\n  checkValues(row);\n }\n @IsTest static void metadataMixedReverseAndWrite() {\n  GladeCaseField53__mdt row=[SELECT Target_OBject_Mapping__r.Legacy_Data_Import_Object_Name__c,Target_Object_Mapping__r.DeveloperName,Target_Object_Mapping__r.Object_API_Name__c FROM GladeCaseField53__mdt WHERE DeveloperName='Child'];\n  row.Target_Object_Mapping__r.Object_API_Name__c='Changed';\n  System.assertEquals('Changed',row.Target_OBject_Mapping__r.Object_API_Name__c);\n  System.assertEquals('Account1',row.Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c);\n  System.assertEquals('Parent',row.Target_Object_Mapping__r.DeveloperName);\n }\n @IsTest static void ordinaryMixedProjectionCase() {\n  Account parent=new Account(Name='Case Parent',Phone='555-case');insert parent;\n  Contact child=new Contact(LastName='Case Child',AccountId=parent.Id);insert child;\n  Contact row=[SELECT Account.Name,ACCount.Phone FROM Contact WHERE Id=:child.Id];\n  System.assertEquals('Case Parent',row.Account.Name);\n  System.assertEquals('555-case',row.Account.Phone);\n  row.Account.Name='Changed';\n  System.assertEquals('Changed',row.ACCount.Name);\n  System.assertEquals('555-case',row.Account.Phone);\n }\n}\n")
	writeFile(t, filepath.Join(root, "force-app/main/default/classes/GladeCaseProjection53.cls-meta.xml"), "<ApexClass xmlns=\"http://soap.sforce.com/2006/04/metadata\"><apiVersion>53.0</apiVersion><status>Active</status></ApexClass>\n")
	writeFile(t, filepath.Join(root, "sfdx-project.json"), "{\"sourceApiVersion\": \"53.0\", \"packageDirectories\": [{\"path\": \"force-app\", \"default\": true}]}")
	run := Run(loadTestIndex(t, root), Options{})
	if got := run.Summary(); got.Total != 4 || got.Passed != 4 || got.Skipped != 0 || got.Failed != 0 || got.Errors != 0 {
		data, _ := json.Marshal(run)
		t.Fatalf("relationship projection contracts failed: %s", data)
	}
}
