package capability

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
)

type StdlibEntry struct {
	Area   string `json:"area"`
	API    string `json:"api"`
	Status Status `json:"status"`
	Notes  string `json:"notes,omitempty"`
}

func StdlibMatrix() []StdlibEntry {
	entries := append([]StdlibEntry(nil), stdlibEntries...)
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Area == entries[j].Area {
			return entries[i].API < entries[j].API
		}
		return entries[i].Area < entries[j].Area
	})
	return entries
}

func WriteStdlibJSON(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(StdlibMatrix())
}

func WriteStdlibMarkdown(w io.Writer) error {
	if _, err := fmt.Fprintln(w, "# Standard Library Coverage"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nGenerated from `internal/capability`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nStatus values match the compatibility dashboard: `supported`, `partial`, `stub`, `unsupported`, and `unknown`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\n| Area | API | Status | Notes |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, entry := range StdlibMatrix() {
		if _, err := fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", entry.Area, entry.API, entry.Status, entry.Notes); err != nil {
			return err
		}
	}
	return nil
}

var stdlibEntries = []StdlibEntry{
	{Area: "Async", API: "AsyncApexJob / CronTrigger local records", Status: StatusPartial, Notes: "Test-context enqueue/drain creates deterministic local AsyncApexJob rows and CronTrigger rows for supported future, queueable, batch, and scheduled jobs; broader platform lifecycle fields are not modeled."},
	{Area: "Async", API: "AsyncInfo / AsyncOptions / finalizers", Status: StatusUnsupported, Notes: "Queueable stack metadata, AsyncOptions mutators/accessors and enqueue overloads, System.attachFinalizer, and FinalizerContext getters return explicit UnsupportedFeature diagnostics."},
	{Area: "Async", API: "BatchableContext.getJobId", Status: StatusPartial, Notes: "Returns the deterministic local AsyncApexJob Id while supported batch start/execute/finish methods drain under Test.stopTest."},
	{Area: "Async", API: "QueueableContext.getJobId", Status: StatusPartial, Notes: "Returns the deterministic local AsyncApexJob Id while supported queueables drain under Test.stopTest."},
	{Area: "Async", API: "SchedulableContext.getTriggerId", Status: StatusPartial, Notes: "Returns the deterministic local CronTrigger Id while supported scheduled jobs drain under Test.stopTest."},
	{Area: "ApexPages", API: "ApexPages.addMessage", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.currentPage", Status: StatusSupported, Notes: "Returns a deterministic local PageReference."},
	{Area: "ApexPages", API: "ApexPages.getMessages", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.Message", Status: StatusPartial, Notes: "Constructor plus severity, summary, and detail getters; no Visualforce rendering lifecycle."},
	{Area: "Approval", API: "Approval process APIs", Status: StatusUnsupported, Notes: "Approval namespace process, request, and lock helpers return explicit UnsupportedFeature diagnostics; approval workflow side effects are not locally modeled."},
	{Area: "Auth", API: "token/cloud APIs", Status: StatusUnsupported, Notes: "Auth namespace token, session, JWT, OAuth, and cloud calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Blob", API: "Blob.size", Status: StatusSupported, Notes: "Returns local Blob byte length."},
	{Area: "Blob", API: "Blob.toString", Status: StatusSupported, Notes: "Returns UTF-8 local Blob bytes as a string and rejects invalid UTF-8 data."},
	{Area: "Blob", API: "Blob.valueOf", Status: StatusSupported, Notes: "Stores the string bytes in a local Blob value."},
	{Area: "Crypto", API: "Crypto.areEqualConstantTime", Status: StatusSupported, Notes: "Constant-time local Blob equality comparison."},
	{Area: "Crypto", API: "Crypto.encrypt/decrypt/sign/verify", Status: StatusUnsupported, Notes: "Encrypt/decrypt, managed-IV variants, signing, verification, org key, keystore, certificate, and random key-generation surfaces return explicit UnsupportedFeature diagnostics; no fake local key material is modeled."},
	{Area: "Crypto", API: "Crypto.generateDigest", Status: StatusSupported, Notes: "MD5, SHA1, SHA-256, SHA-512, SHA3-256/384/512, with conservative algorithm normalization."},
	{Area: "Crypto", API: "Crypto.generateMac", Status: StatusSupported, Notes: "HMAC MD5, SHA1, SHA256, and SHA512 with local Blob keys and conservative algorithm normalization."},
	{Area: "Canvas", API: "Canvas namespace", Status: StatusUnsupported, Notes: "Canvas app integration calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Continuation", API: "Continuation", Status: StatusUnsupported, Notes: "Continuation construction and callback/response calls return explicit UnsupportedFeature diagnostics."},
	{Area: "List", API: "List.add", Status: StatusSupported, Notes: "Adds typed local values, including indexed insertion."},
	{Area: "List", API: "List.addAll", Status: StatusSupported, Notes: "Appends typed values from local List or Set values."},
	{Area: "List", API: "List.clear", Status: StatusSupported, Notes: "Removes all local list elements."},
	{Area: "List", API: "List.clone", Status: StatusSupported, Notes: "Copies the local list container; elements keep local value identity."},
	{Area: "List", API: "List.contains", Status: StatusSupported, Notes: "Checks local values, including null, using local value equality."},
	{Area: "List", API: "List.copyConstructor", Status: StatusSupported, Notes: "Copies values from a local List or Set constructor argument."},
	{Area: "List", API: "List.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "List", API: "List.get", Status: StatusSupported, Notes: "Indexed lookup with stable bounds errors."},
	{Area: "List", API: "List.indexOf", Status: StatusSupported, Notes: "Local equality search, including null elements, with -1 for misses."},
	{Area: "List", API: "List.isEmpty", Status: StatusSupported, Notes: "Checks local list length."},
	{Area: "List", API: "List.iterator", Status: StatusSupported, Notes: "Returns a deterministic snapshot Iterator for local List values."},
	{Area: "List", API: "List.remove", Status: StatusSupported, Notes: "Indexed removal returns the removed value."},
	{Area: "List", API: "List.set", Status: StatusSupported, Notes: "Indexed replacement with typed value coercion."},
	{Area: "List", API: "List.size", Status: StatusSupported, Notes: "Returns local list length."},
	{Area: "List", API: "List.sort", Status: StatusPartial, Notes: "Deterministic sort for local primitive comparable values; object/Comparable sorting returns an explicit unsupported error."},
	{Area: "LoggingLevel", API: "LoggingLevel.name", Status: StatusSupported, Notes: "Returns deterministic built-in enum member text."},
	{Area: "LoggingLevel", API: "LoggingLevel.ordinal", Status: StatusSupported, Notes: "Returns deterministic built-in enum order for the local logging level set."},
	{Area: "LoggingLevel", API: "LoggingLevel.toString", Status: StatusSupported, Notes: "Returns deterministic built-in enum member text."},
	{Area: "LoggingLevel", API: "LoggingLevel.values", Status: StatusSupported, Notes: "Returns NONE, ERROR, WARN, INFO, DEBUG, FINE, FINER, FINEST in deterministic order."},
	{Area: "Map", API: "Map.clear", Status: StatusSupported, Notes: "Removes all local map entries."},
	{Area: "Map", API: "Map.clone", Status: StatusSupported, Notes: "Copies the local map container; values keep local identity."},
	{Area: "Map", API: "Map.containsKey", Status: StatusSupported, Notes: "Checks local keys, including null keys, using deterministic key encoding."},
	{Area: "Map", API: "Map.containsValue", Status: StatusSupported, Notes: "Checks local values, including null values, using local value equality."},
	{Area: "Map", API: "Map.copyConstructor", Status: StatusSupported, Notes: "Copies entries from a local Map and supports Map<Id,SObject> construction from List<SObject> with non-null unique Ids."},
	{Area: "Map", API: "Map.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "Map", API: "Map.get", Status: StatusSupported, Notes: "Returns local value or null for missing keys."},
	{Area: "Map", API: "Map.isEmpty", Status: StatusSupported, Notes: "Checks local map size."},
	{Area: "Map", API: "Map.keySet", Status: StatusSupported, Notes: "Returns deterministic local key Set, preserving null keys."},
	{Area: "Map", API: "Map.put", Status: StatusSupported, Notes: "Stores typed local entries and returns the previous value."},
	{Area: "Map", API: "Map.putAll", Status: StatusSupported, Notes: "Copies local entries from another Map or SObject rows into Map<Id,SObject> by non-null unique Id."},
	{Area: "Map", API: "Map.remove", Status: StatusSupported, Notes: "Removes a key and returns its previous local value or null."},
	{Area: "Map", API: "Map.size", Status: StatusSupported, Notes: "Returns local map size."},
	{Area: "Map", API: "Map.toString", Status: StatusPartial, Notes: "Deterministic local entry string form; exact platform formatting may differ."},
	{Area: "Map", API: "Map.values", Status: StatusSupported, Notes: "Returns deterministic local values List."},
	{Area: "Set", API: "Set.add", Status: StatusSupported, Notes: "Adds typed local values and reports whether the Set changed."},
	{Area: "Set", API: "Set.addAll", Status: StatusSupported, Notes: "Adds typed values from local List or Set values."},
	{Area: "Set", API: "Set.clear", Status: StatusSupported, Notes: "Removes all local set elements."},
	{Area: "Set", API: "Set.clone", Status: StatusSupported, Notes: "Copies the local set container; elements keep local value identity."},
	{Area: "Set", API: "Set.contains", Status: StatusSupported, Notes: "Checks local values, including null, using local value equality."},
	{Area: "Set", API: "Set.containsAll", Status: StatusSupported, Notes: "Checks local List or Set membership."},
	{Area: "Set", API: "Set.copyConstructor", Status: StatusSupported, Notes: "Copies unique values from a local List or Set constructor argument."},
	{Area: "Set", API: "Set.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "Set", API: "Set.isEmpty", Status: StatusSupported, Notes: "Checks local set length."},
	{Area: "Set", API: "Set.iterator", Status: StatusSupported, Notes: "Returns a deterministic snapshot Iterator for local Set values."},
	{Area: "Set", API: "Set.remove", Status: StatusSupported, Notes: "Removes a local value, including null, and reports whether the Set changed."},
	{Area: "Set", API: "Set.removeAll", Status: StatusSupported, Notes: "Removes local List or Set members."},
	{Area: "Set", API: "Set.retainAll", Status: StatusSupported, Notes: "Retains only local List or Set members."},
	{Area: "Set", API: "Set.size", Status: StatusSupported, Notes: "Returns local set length."},
	{Area: "Search", API: "Search.* / SOSL FIND", Status: StatusUnsupported, Notes: "Cloud search and SOSL execution are not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "REST", API: "RestContext.request / RestContext.response", Status: StatusPartial, Notes: "VM-local static slots support RestRequest assignment and lazy RestResponse creation; no platform request lifecycle dispatch is modeled."},
	{Area: "REST", API: "RestRequest / RestResponse object shapes", Status: StatusPartial, Notes: "Local request/response objects expose URI/path/method/address, params, headers, Blob body, status, and add/get helper methods covered by compatibility fixtures; broader platform lifecycle remains unsupported."},
	{Area: "REST", API: "@RestResource local server dispatch", Status: StatusUnsupported, Notes: "Custom Apex REST dispatch returns a stable unsupported error from the local server."},
	{Area: "Database", API: "Database.convertLead", Status: StatusUnsupported, Notes: "Lead conversion returns an explicit UnsupportedFeature diagnostic until local lead/account/contact/opportunity side effects are modeled."},
	{Area: "Database", API: "Database.delete", Status: StatusSupported, Notes: "DML pipeline with DeleteResult id/success/errors accessors and structured status/message/fields details for supported SObjects."},
	{Area: "Database", API: "Database.emptyRecycleBin", Status: StatusPartial, Notes: "Permanently removes already-deleted local rows and returns EmptyRecycleBinResult id/success/errors accessors including active-row ENTITY_IS_NOT_IN_RECYCLE_BIN errors; retention policy and related platform recycle-bin behavior are not modeled."},
	{Area: "Database", API: "Database.getQueryLocator", Status: StatusPartial, Notes: "Supported SOQL only; executes eagerly for local batch scopes and exposes getQuery()/iterator() over the local snapshot."},
	{Area: "Database", API: "Database.insert", Status: StatusSupported, Notes: "DML pipeline with SaveResult id/success/errors accessors, structured required/duplicate/validation error details, and DmlException detail methods for supported SObjects."},
	{Area: "Database", API: "Database.lock / Database.unlock", Status: StatusPartial, Notes: "Toggles local storage row lock state and returns LockResult/UnlockResult id/success/errors accessors; ownership, wait timing, and transaction-scoped lock release are not modeled."},
	{Area: "Database", API: "Database.merge", Status: StatusPartial, Notes: "Local merge behavior for supported account/contact-style data, including MergeResult merged and updated-related ID accessors."},
	{Area: "Database", API: "Database.rollback", Status: StatusPartial, Notes: "Local org-state savepoint rollback; no external side effects."},
	{Area: "Database", API: "Database.setSavepoint", Status: StatusPartial, Notes: "Local org-state snapshots with later-savepoint invalidation."},
	{Area: "Database", API: "Database.undelete", Status: StatusPartial, Notes: "Soft-delete restoration for supported local records with UndeleteResult accessors, mixed-row result alignment, allOrNone rollback, ENTITY_IS_NOT_DELETED active-row errors, and ID/object mismatch errors."},
	{Area: "Database", API: "Database.update", Status: StatusSupported, Notes: "DML pipeline with SaveResult id/success/errors accessors and structured status/message/fields details for supported SObjects."},
	{Area: "Database", API: "Database.upsert", Status: StatusPartial, Notes: "Schema-backed external-ID matching with UpsertResult id/success/errors/isCreated accessors for supported local records."},
	{Area: "Data", API: "Custom metadata/custom settings getAll/getInstance", Status: StatusPartial, Notes: "Fixture-backed local __mdt and list custom setting static access supports namespace-stripped object/field names and read-only returned records; hierarchy merge behavior and Metadata API mutation are not modeled."},
	{Area: "Date", API: "Date.addDays", Status: StatusSupported, Notes: "Local Gregorian date arithmetic."},
	{Area: "Date", API: "Date.addMonths", Status: StatusPartial, Notes: "Local Gregorian arithmetic with month-end clamp; full Salesforce edge-case parity incomplete."},
	{Area: "Date", API: "Date.addYears", Status: StatusPartial, Notes: "Local Gregorian arithmetic with leap-day clamp; full Salesforce edge-case parity incomplete."},
	{Area: "Date", API: "Date.day", Status: StatusSupported, Notes: "Returns Gregorian day of month."},
	{Area: "Date", API: "Date.daysBetween", Status: StatusSupported, Notes: "Returns whole calendar days between local Date values."},
	{Area: "Date", API: "Date.month", Status: StatusSupported, Notes: "Returns Gregorian month number."},
	{Area: "Date", API: "Date.newInstance", Status: StatusSupported, Notes: "Validates date parts in the local year 1-9999 Gregorian slice."},
	{Area: "Date", API: "Date.today", Status: StatusPartial, Notes: "Deterministic VM clock date in UTC."},
	{Area: "Date", API: "Date.toEndOfMonth", Status: StatusSupported, Notes: "Returns last day of the Date value's month."},
	{Area: "Date", API: "Date.toStartOfMonth", Status: StatusSupported, Notes: "Returns first day of the Date value's month."},
	{Area: "Date", API: "Date.valueOf", Status: StatusSupported, Notes: "Parses strict yyyy-MM-dd strings plus yyyy-MM-dd time forms into local Date values with stable invalid-input errors."},
	{Area: "Date", API: "Date.year", Status: StatusSupported, Notes: "Returns Gregorian year."},
	{Area: "Datetime", API: "Datetime.addDays", Status: StatusPartial, Notes: "UTC-local arithmetic; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.addHours", Status: StatusSupported, Notes: "Adds whole hours to the UTC instant."},
	{Area: "Datetime", API: "Datetime.addMilliseconds", Status: StatusSupported, Notes: "Adds whole milliseconds to the UTC instant."},
	{Area: "Datetime", API: "Datetime.addMinutes", Status: StatusSupported, Notes: "Adds whole minutes to the UTC instant."},
	{Area: "Datetime", API: "Datetime.addMonths", Status: StatusPartial, Notes: "UTC-local arithmetic with month-end clamp; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.addSeconds", Status: StatusSupported, Notes: "Adds whole seconds to the UTC instant."},
	{Area: "Datetime", API: "Datetime.addYears", Status: StatusPartial, Notes: "UTC-local arithmetic with leap-day clamp; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.date", Status: StatusSupported, Notes: "Returns Date component in the deterministic current-user timezone slice: UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.dateGmt", Status: StatusSupported, Notes: "Returns the UTC Date component."},
	{Area: "Datetime", API: "Datetime.day", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.dayGmt", Status: StatusSupported, Notes: "Returns the UTC day component."},
	{Area: "Datetime", API: "Datetime.format", Status: StatusPartial, Notes: "Deterministic UTC/fixed-offset Java-pattern slice plus modeled named-zone DST formatting for America/Los_Angeles, America/New_York, America/Chicago, America/Denver, Europe/London, Europe/Berlin, Asia/Tokyo, and Australia/Sydney; format(pattern) and format() use the current user timezone inside that slice; locale-dependent pattern tokens return UnsupportedFeature."},
	{Area: "Datetime", API: "Datetime.formatGmt", Status: StatusPartial, Notes: "Deterministic UTC Java-pattern slice with stable token errors; locale-dependent pattern tokens return UnsupportedFeature rather than localized text."},
	{Area: "Datetime", API: "Datetime.hour", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.hourGmt", Status: StatusSupported, Notes: "Returns the UTC hour component."},
	{Area: "Datetime", API: "Datetime.millisecond", Status: StatusSupported, Notes: "Returns the millisecond component of the Datetime instant."},
	{Area: "Datetime", API: "Datetime.minute", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.minuteGmt", Status: StatusSupported, Notes: "Returns the UTC minute component."},
	{Area: "Datetime", API: "Datetime.month", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.monthGmt", Status: StatusSupported, Notes: "Returns the UTC month component."},
	{Area: "Datetime", API: "Datetime.newInstance", Status: StatusSupported, Notes: "Validates integer and Date+Time parts, constructing through the current user timezone for UTC, fixed offsets, and the modeled named-zone slice with deterministic DST gap/overlap handling."},
	{Area: "Datetime", API: "Datetime.newInstanceGmt", Status: StatusSupported, Notes: "Constructs a UTC Datetime from integer or Date+Time parts."},
	{Area: "Datetime", API: "Datetime.now", Status: StatusPartial, Notes: "Deterministic VM clock timestamp in UTC."},
	{Area: "Datetime", API: "Datetime.second", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.secondGmt", Status: StatusSupported, Notes: "Returns the UTC second component."},
	{Area: "Datetime", API: "Datetime.time", Status: StatusSupported, Notes: "Returns Time component in the deterministic current-user timezone slice: UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.timeGmt", Status: StatusSupported, Notes: "Returns the UTC Time component."},
	{Area: "Datetime", API: "Datetime.valueOf", Status: StatusSupported, Notes: "Parses supported strict datetime strings with stable invalid-input errors."},
	{Area: "Datetime", API: "Datetime.valueOfGmt", Status: StatusSupported, Notes: "Parses supported strict UTC/RFC3339 datetime strings with stable invalid-input errors."},
	{Area: "Datetime", API: "Datetime.year", Status: StatusSupported, Notes: "Current-user timezone component getter for UTC, fixed offsets, and modeled named zones; unsupported user zones return typed diagnostics."},
	{Area: "Datetime", API: "Datetime.yearGmt", Status: StatusSupported, Notes: "Returns the UTC year component."},
	{Area: "Decimal", API: "Decimal.abs", Status: StatusSupported, Notes: "Absolute value for local Decimal values."},
	{Area: "Decimal", API: "Decimal.doubleValue", Status: StatusSupported, Notes: "Returns local Decimal value."},
	{Area: "Decimal", API: "Decimal.format", Status: StatusPartial, Notes: "Simple deterministic finite numeric formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Decimal", API: "Decimal.intValue", Status: StatusSupported, Notes: "Truncates to 32-bit Integer with overflow checks."},
	{Area: "Decimal", API: "Decimal.longValue", Status: StatusSupported, Notes: "Truncates to local Long representation with overflow checks."},
	{Area: "Decimal", API: "Decimal.pow", Status: StatusSupported, Notes: "Power with Integer exponent for finite local Decimal results."},
	{Area: "Decimal", API: "Decimal.round", Status: StatusPartial, Notes: "Default half-up plus local RoundingMode subset; exact Decimal scale parity is not modeled."},
	{Area: "Decimal", API: "Decimal.setScale", Status: StatusPartial, Notes: "Supports local scale 0-15 with UP, DOWN, CEILING, FLOOR, HALF_UP, HALF_DOWN, HALF_EVEN, and UNNECESSARY."},
	{Area: "Decimal", API: "Decimal.valueOf", Status: StatusSupported, Notes: "Parses finite decimal strings and numeric values, including trimmed signed strings."},
	{Area: "Double", API: "Double.format", Status: StatusPartial, Notes: "Simple deterministic finite numeric formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Double", API: "Double.valueOf", Status: StatusSupported, Notes: "Parses finite decimal strings and numeric values into the local numeric representation, including trimmed signed strings."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Decode", Status: StatusSupported, Notes: "Blob-shaped local value with stable invalid-input errors."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Encode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertFromHex", Status: StatusSupported, Notes: "Blob-shaped local value with stable odd-length and invalid-input errors."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertToHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Status: StatusPartial, Notes: "Uses query unescape for bounded UTF-8 and ISO-8859-1 charset aliases; other charsets return UnsupportedFeature."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Status: StatusPartial, Notes: "Uses query escape for bounded UTF-8 and ISO-8859-1 charset aliases; other charsets return UnsupportedFeature."},
	{Area: "Exception", API: "Exception.getCause", Status: StatusPartial, Notes: "Returns the locally initialized cause value; repeat/self-cause platform edge rules are not modeled."},
	{Area: "Exception", API: "Built-in exception types", Status: StatusPartial, Notes: "Known public built-in exception tokens construct message-bearing local exceptions and assign to Exception; exact platform class catalog, line numbers, and stack text remain partial."},
	{Area: "Exception", API: "Exception.getLineNumber", Status: StatusPartial, Notes: "Returns deterministic local throw-site line metadata when available; otherwise 0."},
	{Area: "Exception", API: "Exception.getMessage", Status: StatusSupported, Notes: "Returns the local exception message."},
	{Area: "Exception", API: "Exception.getStackTraceString", Status: StatusPartial, Notes: "Returns the local VM stack trace captured at throw time when available."},
	{Area: "Exception", API: "Exception.getTypeName", Status: StatusSupported, Notes: "Returns the local exception type name without System namespace prefix."},
	{Area: "Exception", API: "Exception.initCause", Status: StatusPartial, Notes: "Stores a local Exception cause or null for later getCause calls."},
	{Area: "Exception", API: "Exception.toString", Status: StatusPartial, Notes: "Returns System-prefixed built-in exception text for local exception values."},
	{Area: "EventBus", API: "EventBus.publish", Status: StatusUnsupported, Notes: "Platform event publish and after-commit publish calls return explicit UnsupportedFeature diagnostics."},
	{Area: "FeatureManagement", API: "FeatureManagement.checkPermission", Status: StatusPartial, Notes: "Checks local runAs permission-list state."},
	{Area: "HTTP", API: "Http.send", Status: StatusPartial, Notes: "Mock-first local callouts with request validation and callout accounting; real network transport unsupported."},
	{Area: "HTTP", API: "HttpRequest", Status: StatusPartial, Notes: "Endpoint, method, case-insensitive headers, timeout validation/defaults, body, and blob body accessors."},
	{Area: "HTTP", API: "HttpResponse", Status: StatusPartial, Notes: "Status, status code, case-insensitive headers, body, and blob body accessors."},
	{Area: "JSON", API: "JSON.createGenerator", Status: StatusSupported, Notes: "Creates deterministic local JSONGenerator instances."},
	{Area: "JSON", API: "JSON.createParser", Status: StatusSupported, Notes: "Creates deterministic local JSONParser token streams and throws catchable JSONException for malformed JSON input."},
	{Area: "JSON", API: "JSON.deserialize", Status: StatusSupported, Notes: "Primitive, platform scalar, List, Set, nested Map<String,Object/value>, SObject, and registered or fixture source-backed Apex class shapes; catchable mapping errors for mismatched typed shapes and stable unsupported errors for unknown object targets."},
	{Area: "JSON", API: "JSON.deserializeStrict", Status: StatusSupported, Notes: "Rejects duplicate object fields and throws catchable JSONException for unknown fields on supported schema/class targets, including inherited and nested source-backed class fields."},
	{Area: "JSON", API: "JSON.deserializeUntyped", Status: StatusSupported, Notes: "Maps JSON into local primitive/list/map values with deterministic null and number handling, and throws catchable JSONException for malformed input."},
	{Area: "JSON", API: "JSONGenerator", Status: StatusSupported, Notes: "Object/array boundaries, field names, scalar string/number/Boolean/null, Date/Datetime/Time/Id/Blob, Object and validated raw value writers, getAsString, close, isClosed, and catchable JSONException for invalid nesting, pending fields, repeated roots, raw-value errors, and writes after close."},
	{Area: "JSON", API: "JSONParser", Status: StatusSupported, Notes: "Token navigation, current token/name/text, integer/long/decimal/double/Boolean/date/datetime/time/id/blob accessors, nextValue, skipChildren current-name state, clearCurrentToken, and catchable JSONException for wrong-token or malformed-input errors."},
	{Area: "JSON", API: "JSONToken", Status: StatusSupported, Notes: "Common parser token constants for object, array, field, string, number, Boolean, and null tokens."},
	{Area: "JSON", API: "JSON.serialize", Status: StatusSupported, Notes: "Compact output for supported primitive/list/set/map/object values, including suppressApexObjectNulls for object fields while preserving map/list nulls."},
	{Area: "JSON", API: "JSON.serializePretty", Status: StatusSupported, Notes: "Pretty output for supported primitive/list/set/map/object values with object-field null suppression and map/list null preservation."},
	{Area: "Iterator", API: "Iterator.hasNext", Status: StatusSupported, Notes: "Checks remaining elements in a local collection snapshot."},
	{Area: "Iterator", API: "Iterator.next", Status: StatusSupported, Notes: "Returns the next element from a local collection snapshot and raises NoSuchElementException when exhausted."},
	{Area: "Iterator", API: "Iterator.remove", Status: StatusUnsupported, Notes: "Returns an explicit UnsupportedFeature diagnostic; mutating collection iterators are not modeled."},
	{Area: "Id", API: "Id.getSObjectType", Status: StatusPartial, Notes: "Resolves local schema key prefixes and a bounded common standard prefix table to Schema.SObjectType tokens; unknown shape-valid prefixes return a stable error."},
	{Area: "Id", API: "Id.to15", Status: StatusSupported, Notes: "Converts validated 18-character IDs to their 15-character prefix."},
	{Area: "Id", API: "Id.to18", Status: StatusSupported, Notes: "Adds or preserves the documented 3-character checksum for validated IDs."},
	{Area: "Id", API: "Id.valueOf", Status: StatusSupported, Notes: "Validates 15-character IDs and strict 18-character checksum suffixes; restoreCasing rebuilds casing from checksum suffixes."},
	{Area: "Integer", API: "Integer.MAX_VALUE", Status: StatusSupported, Notes: "Exposes the public 32-bit Integer maximum constant."},
	{Area: "Integer", API: "Integer.MIN_VALUE", Status: StatusSupported, Notes: "Exposes the public 32-bit Integer minimum constant."},
	{Area: "Integer", API: "Integer.doubleValue", Status: StatusSupported, Notes: "Converts local Integer values to the local numeric representation."},
	{Area: "Integer", API: "Integer.format", Status: StatusPartial, Notes: "Simple deterministic base-10 formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Integer", API: "Integer.valueOf", Status: StatusSupported, Notes: "Parses integer strings and numeric values with 32-bit overflow checks, including trimmed signed strings."},
	{Area: "Limits", API: "Limits.get*", Status: StatusPartial, Notes: "SOQL, DML, heap, CPU, async, callout, and email counters; unmodeled documented getters return explicit unsupported diagnostics."},
	{Area: "Long", API: "Long.MAX_VALUE", Status: StatusSupported, Notes: "Exposes the public 64-bit Long maximum constant."},
	{Area: "Long", API: "Long.MIN_VALUE", Status: StatusSupported, Notes: "Exposes the public 64-bit Long minimum constant."},
	{Area: "Long", API: "Long.format", Status: StatusPartial, Notes: "Simple deterministic base-10 formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Long", API: "Long.valueOf", Status: StatusSupported, Notes: "Parses integer strings and numeric values with overflow checks, including trimmed signed strings."},
	{Area: "Math", API: "Math.E", Status: StatusSupported, Notes: "Euler's number from Go's deterministic math constant."},
	{Area: "Math", API: "Math.PI", Status: StatusSupported, Notes: "Pi from Go's deterministic math constant."},
	{Area: "Math", API: "Math.abs", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.acos", Status: StatusSupported, Notes: "Finite deterministic result for inputs in [-1, 1]."},
	{Area: "Math", API: "Math.asin", Status: StatusSupported, Notes: "Finite deterministic result for inputs in [-1, 1]."},
	{Area: "Math", API: "Math.atan", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.atan2", Status: StatusSupported, Notes: "Finite deterministic result for two numeric values."},
	{Area: "Math", API: "Math.ceil", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.cos", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.exp", Status: StatusSupported, Notes: "Finite deterministic result; overflow is reported."},
	{Area: "Math", API: "Math.floor", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.log", Status: StatusSupported, Notes: "Finite deterministic result for positive numeric values."},
	{Area: "Math", API: "Math.log10", Status: StatusSupported, Notes: "Finite deterministic result for positive numeric values."},
	{Area: "Math", API: "Math.max", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.min", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.mod", Status: StatusSupported, Notes: "Integer remainder and Decimal modulus with zero-divisor errors."},
	{Area: "Math", API: "Math.pow", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.round", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.roundToLong", Status: StatusSupported, Notes: "Rounds to local Long representation with overflow checks."},
	{Area: "Math", API: "Math.signum", Status: StatusSupported, Notes: "Returns -1, 0, or 1 for local numeric values."},
	{Area: "Math", API: "Math.sin", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.sqrt", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.tan", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Messaging", API: "Messaging.SingleEmailMessage", Status: StatusPartial, Notes: "Common setters only; no delivery transport."},
	{Area: "Messaging", API: "Messaging.SendEmailResult", Status: StatusPartial, Notes: "Local success result exposes isSuccess and getErrors getters."},
	{Area: "Messaging", API: "Messaging.sendEmail", Status: StatusPartial, Notes: "Single-list overload returns local SendEmailResult and increments email limits; transport/options/template surfaces are unsupported."},
	{Area: "Object", API: "Object.equals", Status: StatusSupported, Notes: "Uses local value equality for primitives, collections, platform scalars, and object identity."},
	{Area: "Object", API: "Object.hashCode", Status: StatusSupported, Notes: "Deterministic within local value equality; object identity hashes are request-local."},
	{Area: "Object", API: "Object.toString", Status: StatusSupported, Notes: "Returns local string forms for primitives, collections, platform scalars, and objects."},
	{Area: "PageReference", API: "PageReference", Status: StatusPartial, Notes: "Constructor, URL, redirect, parameters, headers, and string conversion basics; Visualforce rendering and PDF content remain explicit UnsupportedFeature seams."},
	{Area: "QuickAction", API: "QuickAction namespace", Status: StatusUnsupported, Notes: "Quick action UI calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Pattern", API: "Matcher.end", Status: StatusPartial, Notes: "Go regexp-backed group end positions, including -1 for optional unmatched groups and stable invalid-group errors."},
	{Area: "Pattern", API: "Matcher.find", Status: StatusPartial, Notes: "Go regexp-backed matching with captured groups, region bounds, find(start) reset behavior, and local anchoring/transparent bound handling."},
	{Area: "Pattern", API: "Matcher.group", Status: StatusPartial, Notes: "Go regexp-backed group access with stale match state cleared after failed find/matches/lookingAt calls."},
	{Area: "Pattern", API: "Matcher.groupCount", Status: StatusPartial, Notes: "Capturing group count from Go regexp."},
	{Area: "Pattern", API: "Matcher.lookingAt", Status: StatusPartial, Notes: "Beginning-of-region Go regexp match with local anchoring/transparent bounds."},
	{Area: "Pattern", API: "Matcher.matches", Status: StatusPartial, Notes: "Whole-region Go regexp match with local anchoring/transparent bounds."},
	{Area: "Pattern", API: "Matcher.region", Status: StatusPartial, Notes: "Bounds matching to a local rune-indexed region, including anchored-region and transparent word-boundary cases."},
	{Area: "Pattern", API: "Matcher.regionStart/regionEnd", Status: StatusPartial, Notes: "Returns local rune-indexed region bounds."},
	{Area: "Pattern", API: "Matcher.replaceAll", Status: StatusPartial, Notes: "Go regexp-backed replacement with region bounds, Java-style numeric capture parsing, escaped dollar/backslash handling, and named replacement references pinned unsupported."},
	{Area: "Pattern", API: "Matcher.replaceFirst", Status: StatusPartial, Notes: "Go regexp-backed first replacement with region bounds, Java-style numeric capture parsing, escaped dollar/backslash handling, and named replacement references pinned unsupported."},
	{Area: "Pattern", API: "Matcher.reset", Status: StatusPartial, Notes: "Clears local match state, resets the region to full input, and optionally replaces input."},
	{Area: "Pattern", API: "Matcher.appendReplacement/appendTail", Status: StatusUnsupported, Notes: "Java StringBuffer append-position semantics return explicit unsupported errors."},
	{Area: "Pattern", API: "Matcher.hasAnchoringBounds", Status: StatusPartial, Notes: "Local bounds flag defaults to true and drives region-vs-input anchor handling for Go-regexp matches."},
	{Area: "Pattern", API: "Matcher.hasTransparentBounds", Status: StatusPartial, Notes: "Local bounds flag defaults to false and drives opaque-vs-full-input word-boundary handling for Go-regexp matches."},
	{Area: "Pattern", API: "Matcher.useAnchoringBounds", Status: StatusPartial, Notes: "Stores local bounds flag and toggles whether ^/$ bind to region edges or full input edges."},
	{Area: "Pattern", API: "Matcher.usePattern", Status: StatusPartial, Notes: "Swaps the local Go regexp Pattern and resets search state within the current region."},
	{Area: "Pattern", API: "Matcher.useTransparentBounds", Status: StatusPartial, Notes: "Stores local bounds flag and toggles whether word-boundary checks use opaque region edges or full input context."},
	{Area: "Pattern", API: "Matcher.start", Status: StatusPartial, Notes: "Go regexp-backed group start positions, including -1 for optional unmatched groups and stable invalid-group errors."},
	{Area: "Pattern", API: "Pattern.compile", Status: StatusPartial, Notes: "Go regexp syntax with stable UnsupportedFeature diagnostics for pinned Java-only regex features including lookaround, backreferences, named groups, possessive quantifiers, atomic groups, quote escapes, and previous-match boundaries."},
	{Area: "Pattern", API: "Pattern.matcher", Status: StatusPartial, Notes: "Creates a Go regexp-backed Matcher."},
	{Area: "Pattern", API: "Pattern.matches", Status: StatusPartial, Notes: "Whole-string Go regexp match with the same pinned Java-only syntax diagnostics as Pattern.compile."},
	{Area: "Pattern", API: "Pattern.pattern", Status: StatusPartial, Notes: "Returns stored Go regexp source."},
	{Area: "Pattern", API: "Pattern.quote", Status: StatusPartial, Notes: "Returns a Go regexp-escaped literal pattern for local Pattern/Matcher use."},
	{Area: "Pattern", API: "Pattern.split", Status: StatusPartial, Notes: "Go regexp-backed split with local limit semantics, pinned unsupported Java-only regex diagnostics, and nullable delimiter regexes fenced unsupported."},
	{Area: "RoundingMode", API: "RoundingMode.valueOf", Status: StatusPartial, Notes: "Constructs supported local Decimal rounding-mode tokens by exact name."},
	{Area: "Schema", API: "Schema.describeSObjects", Status: StatusPartial, Notes: "Object names and SObjectType tokens for local schema."},
	{Area: "Schema", API: "Schema.getGlobalDescribe", Status: StatusPartial, Notes: "Local schema-backed describe map."},
	{Area: "Schema", API: "DescribeFieldResult", Status: StatusPartial, Notes: "Common field metadata and access booleans."},
	{Area: "Schema", API: "DescribeSObjectResult", Status: StatusPartial, Notes: "Common object metadata, fields, record types, and child relationships."},
	{Area: "String", API: "String.abbreviate", Status: StatusSupported, Notes: "Apache-style abbreviation for one- and two-argument forms."},
	{Area: "String", API: "String.charAt", Status: StatusSupported, Notes: "Rune-indexed one-character String."},
	{Area: "String", API: "String.codePointAt", Status: StatusSupported, Notes: "Rune-indexed Unicode code point."},
	{Area: "String", API: "String.codePointBefore", Status: StatusSupported, Notes: "Rune-indexed previous Unicode code point."},
	{Area: "String", API: "String.codePointCount", Status: StatusSupported, Notes: "Counts runes between validated indexes."},
	{Area: "String", API: "String.commonPrefix", Status: StatusSupported, Notes: "Returns the shared rune prefix for two strings."},
	{Area: "String", API: "String.center", Status: StatusSupported, Notes: "Centers text to a requested rune width with space or supplied pad text."},
	{Area: "String", API: "String.compareTo", Status: StatusSupported, Notes: "Lexicographic comparison for local string values."},
	{Area: "String", API: "String.contains", Status: StatusSupported, Notes: "UTF-8 string contains."},
	{Area: "String", API: "String.containsAny", Status: StatusSupported, Notes: "Rune membership."},
	{Area: "String", API: "String.containsIgnoreCase", Status: StatusSupported, Notes: "Case-insensitive containment using local Unicode lowercasing."},
	{Area: "String", API: "String.containsNone", Status: StatusSupported, Notes: "Rune exclusion."},
	{Area: "String", API: "String.containsOnly", Status: StatusSupported, Notes: "Rune allow-list."},
	{Area: "String", API: "String.containsWhitespace", Status: StatusSupported, Notes: "Unicode whitespace."},
	{Area: "String", API: "String.countMatches", Status: StatusSupported, Notes: "Non-overlapping literal substring count."},
	{Area: "String", API: "String.difference", Status: StatusSupported, Notes: "Returns the differing suffix from the comparison string."},
	{Area: "String", API: "String.endsWith", Status: StatusSupported, Notes: "UTF-8 string suffix."},
	{Area: "String", API: "String.endsWithIgnoreCase", Status: StatusSupported, Notes: "Case-insensitive suffix check using local Unicode lowercasing."},
	{Area: "String", API: "String.equals", Status: StatusSupported, Notes: "Exact local string equality."},
	{Area: "String", API: "String.equalsIgnoreCase", Status: StatusSupported, Notes: "Unicode simple fold."},
	{Area: "String", API: "String.escapeCsv", Status: StatusSupported, Notes: "One-field RFC4180-style quoting for comma, quote, CR, and LF; doubles embedded quotes."},
	{Area: "String", API: "String.escapeEcmaScript", Status: StatusPartial, Notes: "JavaScript-style backslash, quote, slash, control, and UTF-16 Unicode escaping for deterministic cases."},
	{Area: "String", API: "String.escapeHtml3", Status: StatusPartial, Notes: "Deterministic core HTML entity escaping only; full named-entity coverage is not modeled."},
	{Area: "String", API: "String.escapeHtml4", Status: StatusPartial, Notes: "Deterministic core HTML entity escaping only; full named-entity coverage is not modeled."},
	{Area: "String", API: "String.escapeJava", Status: StatusPartial, Notes: "Java-style backslash, quote, control, and UTF-16 Unicode escaping for deterministic cases."},
	{Area: "String", API: "String.escapeSingleQuotes", Status: StatusSupported, Notes: "Escapes single quotes with backslashes."},
	{Area: "String", API: "String.escapeUnicode", Status: StatusPartial, Notes: "Escapes non-ASCII and control runes as UTF-16 Unicode escapes."},
	{Area: "String", API: "String.escapeXml", Status: StatusPartial, Notes: "Escapes XML core entities; XML version-specific validity is not modeled."},
	{Area: "String", API: "String.escapeXml10", Status: StatusPartial, Notes: "Escapes XML core entities, drops XML 1.0-invalid code points, and numeric-escapes restricted control ranges."},
	{Area: "String", API: "String.escapeXml11", Status: StatusPartial, Notes: "Escapes XML core entities, drops XML 1.1-invalid nulls, and numeric-escapes restricted control ranges."},
	{Area: "String", API: "String.format", Status: StatusPartial, Notes: "Deterministic {0}-style list substitution; full MessageFormat locale behavior is not modeled."},
	{Area: "String", API: "String.fromCharArray", Status: StatusSupported, Notes: "Builds a string from valid Unicode code point integers."},
	{Area: "String", API: "String.getChars", Status: StatusSupported, Notes: "Returns Unicode code point integers for each rune."},
	{Area: "String", API: "String.getCommonPrefix", Status: StatusSupported, Notes: "Returns the shared rune prefix for a list of strings."},
	{Area: "String", API: "String.getLevenshteinDistance", Status: StatusSupported, Notes: "Rune-based edit distance."},
	{Area: "String", API: "String.indexOf", Status: StatusSupported, Notes: "Rune-indexed literal search with optional start position and empty-search edge handling."},
	{Area: "String", API: "String.indexOfAny", Status: StatusSupported, Notes: "Returns the first rune index whose character appears in the search set."},
	{Area: "String", API: "String.indexOfAnyBut", Status: StatusSupported, Notes: "Returns the first rune index whose character is outside the search set."},
	{Area: "String", API: "String.isAllLowerCase", Status: StatusSupported, Notes: "All letters lowercase; non-letters ignored."},
	{Area: "String", API: "String.isAllUpperCase", Status: StatusSupported, Notes: "All letters uppercase; non-letters ignored."},
	{Area: "String", API: "String.isAlpha", Status: StatusSupported, Notes: "Unicode letters."},
	{Area: "String", API: "String.isAlphaSpace", Status: StatusSupported, Notes: "Unicode letters and space characters."},
	{Area: "String", API: "String.isAlphanumeric", Status: StatusSupported, Notes: "Unicode letters and decimal digits."},
	{Area: "String", API: "String.isAlphanumericSpace", Status: StatusSupported, Notes: "Unicode letters, decimal digits, and space characters."},
	{Area: "String", API: "String.isAsciiPrintable", Status: StatusSupported, Notes: "Checks ASCII printable range 0x20 through 0x7E."},
	{Area: "String", API: "String.isBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isEmpty", Status: StatusSupported, Notes: "Null and empty string."},
	{Area: "String", API: "String.isNotBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isNotEmpty", Status: StatusSupported, Notes: "Null and empty string."},
	{Area: "String", API: "String.isNumeric", Status: StatusSupported, Notes: "Unicode decimal digits."},
	{Area: "String", API: "String.isNumericSpace", Status: StatusSupported, Notes: "Unicode decimal digits and space characters."},
	{Area: "String", API: "String.isWhitespace", Status: StatusSupported, Notes: "Unicode whitespace; empty string is true."},
	{Area: "String", API: "String.join", Status: StatusSupported, Notes: "List values and separator."},
	{Area: "String", API: "String.hashCode", Status: StatusSupported, Notes: "Java-compatible UTF-16 code-unit string hash for local values."},
	{Area: "String", API: "String.lastIndexOf", Status: StatusSupported, Notes: "Rune-indexed reverse literal search with optional start position and empty-search edge handling."},
	{Area: "String", API: "String.lastIndexOfAny", Status: StatusSupported, Notes: "Returns the last rune index whose character appears in the search set."},
	{Area: "String", API: "String.lastOrdinalIndexOf", Status: StatusSupported, Notes: "Finds the nth occurrence from the end using rune indexes."},
	{Area: "String", API: "String.left", Status: StatusSupported, Notes: "Returns the leftmost requested rune count, clamped to string length."},
	{Area: "String", API: "String.leftPad", Status: StatusSupported, Notes: "Pads on the left to a requested rune width with space or supplied pad text."},
	{Area: "String", API: "String.length", Status: StatusSupported, Notes: "Counts runes."},
	{Area: "String", API: "String.mid", Status: StatusSupported, Notes: "Returns a clamped rune-indexed middle slice by start and length."},
	{Area: "String", API: "String.ordinalIndexOf", Status: StatusSupported, Notes: "Finds the nth occurrence from the start using rune indexes."},
	{Area: "String", API: "String.overlay", Status: StatusSupported, Notes: "Overlays text between clamped rune indexes."},
	{Area: "String", API: "String.replace", Status: StatusSupported, Notes: "Literal replacement; empty targets are a no-op."},
	{Area: "String", API: "String.replaceAll", Status: StatusPartial, Notes: "Go regexp-backed replacement with Java-style numeric capture parsing, escaped dollar/backslash handling, and pinned unsupported Java-only regex diagnostics."},
	{Area: "String", API: "String.replaceFirst", Status: StatusPartial, Notes: "Go regexp-backed first replacement with Java-style numeric capture parsing, escaped dollar/backslash handling, and pinned unsupported Java-only regex diagnostics."},
	{Area: "String", API: "String.replaceIgnoreCase", Status: StatusSupported, Notes: "Literal non-overlapping replacement with rune-wise case folding."},
	{Area: "String", API: "String.replaceOnce", Status: StatusSupported, Notes: "First literal replacement only."},
	{Area: "String", API: "String.remove", Status: StatusSupported, Notes: "Literal non-overlapping removal; empty targets are a no-op."},
	{Area: "String", API: "String.removeEnd", Status: StatusSupported, Notes: "Removes a literal suffix when present."},
	{Area: "String", API: "String.removeEndIgnoreCase", Status: StatusSupported, Notes: "Removes a literal suffix with rune-wise case folding when present."},
	{Area: "String", API: "String.removeIgnoreCase", Status: StatusSupported, Notes: "Literal non-overlapping removal with rune-wise case folding."},
	{Area: "String", API: "String.removeStart", Status: StatusSupported, Notes: "Removes a literal prefix when present."},
	{Area: "String", API: "String.removeStartIgnoreCase", Status: StatusSupported, Notes: "Removes a literal prefix with rune-wise case folding when present."},
	{Area: "String", API: "String.repeat", Status: StatusSupported, Notes: "Repeats a string with optional separator and non-negative count."},
	{Area: "String", API: "String.reverse", Status: StatusSupported, Notes: "Reverses rune order."},
	{Area: "String", API: "String.right", Status: StatusSupported, Notes: "Returns the rightmost requested rune count, clamped to string length."},
	{Area: "String", API: "String.rightPad", Status: StatusSupported, Notes: "Pads on the right to a requested rune width with space or supplied pad text."},
	{Area: "String", API: "String.rotate", Status: StatusSupported, Notes: "Rune-based rotation; positive shifts rotate right."},
	{Area: "String", API: "String.split", Status: StatusPartial, Notes: "Go regexp-backed split with Apex limit shape, pinned unsupported Java-only regex diagnostics, and nullable delimiter regexes fenced unsupported."},
	{Area: "String", API: "String.splitByCharacterType", Status: StatusSupported, Notes: "Splits on coarse Unicode upper/lower/digit/space/other groups."},
	{Area: "String", API: "String.splitByCharacterTypeCamelCase", Status: StatusSupported, Notes: "Splits character types with camel-case upper-to-lower adjustment."},
	{Area: "String", API: "String.startsWith", Status: StatusSupported, Notes: "UTF-8 string prefix."},
	{Area: "String", API: "String.startsWithIgnoreCase", Status: StatusSupported, Notes: "Case-insensitive prefix check using local Unicode lowercasing."},
	{Area: "String", API: "String.strip", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from both ends."},
	{Area: "String", API: "String.stripAll", Status: StatusSupported, Notes: "Strips each string in a list with optional strip-character set."},
	{Area: "String", API: "String.stripEnd", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from the end."},
	{Area: "String", API: "String.stripStart", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from the start."},
	{Area: "String", API: "String.stripToEmpty", Status: StatusSupported, Notes: "Strips whitespace and returns an empty string for all-blank values."},
	{Area: "String", API: "String.stripToNull", Status: StatusSupported, Notes: "Strips whitespace and returns null for all-blank values."},
	{Area: "String", API: "String.substring", Status: StatusSupported, Notes: "Rune-indexed substring."},
	{Area: "String", API: "String.substringAfter", Status: StatusSupported, Notes: "Returns text after the first literal separator, empty when absent."},
	{Area: "String", API: "String.substringAfterLast", Status: StatusSupported, Notes: "Returns text after the last literal separator, empty when absent."},
	{Area: "String", API: "String.substringBefore", Status: StatusSupported, Notes: "Returns text before the first literal separator, original text when absent."},
	{Area: "String", API: "String.substringBeforeLast", Status: StatusSupported, Notes: "Returns text before the last literal separator, original text when absent."},
	{Area: "String", API: "String.substringBetween", Status: StatusSupported, Notes: "Returns the first literal bracketed substring for one-tag and open/close forms, or null when absent."},
	{Area: "String", API: "String.swapCase", Status: StatusSupported, Notes: "Unicode upper/lower rune case swap."},
	{Area: "String", API: "String.toLowerCase", Status: StatusSupported, Notes: "Go Unicode lowercasing."},
	{Area: "String", API: "String.toUpperCase", Status: StatusSupported, Notes: "Go Unicode uppercasing."},
	{Area: "String", API: "String.trim", Status: StatusSupported, Notes: "Unicode whitespace trim."},
	{Area: "String", API: "String.unescapeCsv", Status: StatusSupported, Notes: "Unquotes one doubled-quote CSV field; plain strings are unchanged."},
	{Area: "String", API: "String.unescapeEcmaScript", Status: StatusPartial, Notes: "Unescapes common JavaScript-style backslash, octal, and UTF-16 Unicode escapes."},
	{Area: "String", API: "String.unescapeHtml3", Status: StatusPartial, Notes: "Unescapes core HTML entities, selected high-use HTML 3/4 named entities, and numeric references; remaining unknown named entities stay unchanged."},
	{Area: "String", API: "String.unescapeHtml4", Status: StatusPartial, Notes: "Unescapes core HTML entities, selected high-use HTML 3/4 named entities, and numeric references; remaining unknown named entities stay unchanged."},
	{Area: "String", API: "String.unescapeJava", Status: StatusPartial, Notes: "Unescapes common Java-style backslash, octal, and UTF-16 Unicode escapes."},
	{Area: "String", API: "String.unescapeUnicode", Status: StatusPartial, Notes: "Unescapes UTF-16 Unicode escape sequences."},
	{Area: "String", API: "String.unescapeXml", Status: StatusPartial, Notes: "Unescapes XML core entities and valid numeric references; malformed, null, out-of-range, and surrogate numeric entities stay unchanged."},
	{Area: "String", API: "String.unescapeXml10", Status: StatusPartial, Notes: "Alias of local XML core/numeric entity unescaping; malformed, null, out-of-range, and surrogate numeric entities stay unchanged."},
	{Area: "String", API: "String.unescapeXml11", Status: StatusPartial, Notes: "Alias of local XML core/numeric entity unescaping; malformed, null, out-of-range, and surrogate numeric entities stay unchanged."},
	{Area: "String", API: "String.valueOf", Status: StatusSupported, Notes: "Local value string conversion."},
	{Area: "System", API: "System.assert", Status: StatusSupported, Notes: "Assertion failure returns runtime error; Object and null message values use deterministic local string conversion."},
	{Area: "System", API: "System.assertEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error with deterministic local expected/actual text and Object/null message conversion."},
	{Area: "System", API: "System.assertNotEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error with deterministic local value text and Object/null message conversion."},
	{Area: "System", API: "System.asyncScheduling", Status: StatusPartial, Notes: "System.abortJob removes queued local Queueable and Schedulable jobs before Test.stopTest; completed and unknown aborts plus scheduleBatch return explicit unsupported diagnostics. Broader async lifecycle control is not modeled."},
	{Area: "System", API: "System.currentTimeMillis", Status: StatusPartial, Notes: "Returns deterministic VM-clock epoch milliseconds."},
	{Area: "System", API: "System.debug", Status: StatusSupported, Notes: "One-argument and LoggingLevel overloads are collected in result debug output; null, LoggingLevel, and modeled Exception values use deterministic string forms; log framework text parity is not claimed."},
	{Area: "System", API: "System.isBatch", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isFuture", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isQueueable", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isScheduled", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.now", Status: StatusPartial, Notes: "Returns deterministic VM-clock Datetime."},
	{Area: "System", API: "System.today", Status: StatusPartial, Notes: "Returns deterministic VM-clock Date."},
	{Area: "Test", API: "Test.clearApexPageMessages", Status: StatusSupported, Notes: "Clears VM-local ApexPages messages in test context."},
	{Area: "Test", API: "Test.createSoqlStub", Status: StatusUnsupported, Notes: "SOQL stub creation is not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.createStub", Status: StatusUnsupported, Notes: "Dynamic stub creation is not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.getStandardPricebookId", Status: StatusPartial, Notes: "Deterministic test-context-only ID."},
	{Area: "Test", API: "Test.isRunningTest", Status: StatusSupported, Notes: "Reflects local test context."},
	{Area: "Test", API: "Test.setFixedSearchResults", Status: StatusUnsupported, Notes: "Fixed SOSL search results are deferred with the local search surface; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.setMock", Status: StatusPartial, Notes: "HttpCalloutMock support for local tests; other mock interfaces return explicit unsupported diagnostics."},
	{Area: "Test", API: "Test.startTest", Status: StatusPartial, Notes: "Governor-window reset/restore for supported counters."},
	{Area: "Test", API: "Test.stopTest", Status: StatusPartial, Notes: "Drains supported async work."},
	{Area: "Time", API: "Time.addHours", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addMilliseconds", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addMinutes", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addSeconds", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.hour", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.millisecond", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.minute", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.newInstance", Status: StatusSupported, Notes: "Validates time parts including optional millisecond."},
	{Area: "Time", API: "Time.second", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.valueOf", Status: StatusSupported, Notes: "Parses strict HH:mm:ss and HH:mm:ss.SSS strings with stable invalid-input errors."},
	{Area: "TimeZone", API: "TimeZone.getDisplayName", Status: StatusPartial, Notes: "Returns deterministic ID text for UTC, fixed GMT offsets, and the modeled named-zone table; the daylight Boolean overload returns modeled abbreviations, while locale/style overloads remain unsupported."},
	{Area: "TimeZone", API: "TimeZone.getID", Status: StatusPartial, Notes: "Returns canonical UTC, fixed GMT offset ID, or a modeled named-zone ID."},
	{Area: "TimeZone", API: "TimeZone.getOffset", Status: StatusPartial, Notes: "Returns fixed offset milliseconds for the deterministic offset slice and modeled DST decisions for US, Europe, and Sydney rules; other named zones are unsupported."},
	{Area: "TimeZone", API: "TimeZone.getTimeZone", Status: StatusPartial, Notes: "Supports UTC/GMT, fixed GMT/UTC offsets through ±14:00, and America/Los_Angeles, America/New_York, America/Chicago, America/Denver, Europe/London, Europe/Berlin, Asia/Tokyo, and Australia/Sydney; other named zones and trimmed/invalid IDs are unsupported."},
	{Area: "Type", API: "Type.forName", Status: StatusPartial, Notes: "Local class/type token lookup, common local SObjects, built-in and generic collection type strings, and null for null/blank/unknown local names."},
	{Area: "Type", API: "Type.equals", Status: StatusSupported, Notes: "Compares local Type tokens by type name."},
	{Area: "Type", API: "Type.getName", Status: StatusSupported, Notes: "Returns local type token name."},
	{Area: "Type", API: "Type.hashCode", Status: StatusSupported, Notes: "Matches the local String.hashCode of the type name."},
	{Area: "Type", API: "Type.isAssignableFrom", Status: StatusPartial, Notes: "Uses the local class/interface and built-in exception hierarchy."},
	{Area: "Type", API: "Type.newInstance", Status: StatusPartial, Notes: "Constructs local values and dispatches zero-arg constructors for registered classes; unbacked namespace/package tokens return explicit unsupported errors."},
	{Area: "Type", API: "Type.toString", Status: StatusSupported, Notes: "Returns the local type token name."},
	{Area: "URL", API: "URL", Status: StatusPartial, Notes: "Constructors for deterministic absolute URL specs, context/spec resolution, and protocol/host/file forms with stable malformed input errors."},
	{Area: "URL", API: "URL.getAuthority", Status: StatusSupported, Notes: "Returns parsed authority for local URL values."},
	{Area: "URL", API: "URL.getDefaultPort", Status: StatusSupported, Notes: "Returns HTTP/HTTPS defaults or -1."},
	{Area: "URL", API: "URL.getFile", Status: StatusSupported, Notes: "Returns path plus query for local URL values."},
	{Area: "URL", API: "URL.getHost", Status: StatusSupported, Notes: "Returns parsed hostname for local URL values."},
	{Area: "URL", API: "URL.getCurrentRequestUrl", Status: StatusUnsupported, Notes: "Cloud request context is not modeled; returns an explicit unsupported current-request URL error."},
	{Area: "URL", API: "URL.getOrgDomainUrl", Status: StatusPartial, Notes: "Deterministic local org URL."},
	{Area: "URL", API: "URL.getPath", Status: StatusSupported, Notes: "Returns parsed path for local URL values."},
	{Area: "URL", API: "URL.getPort", Status: StatusSupported, Notes: "Returns explicit port or -1."},
	{Area: "URL", API: "URL.getProtocol", Status: StatusSupported, Notes: "Returns parsed scheme for local URL values."},
	{Area: "URL", API: "URL.getQuery", Status: StatusSupported, Notes: "Returns parsed query for local URL values."},
	{Area: "URL", API: "URL.getRef", Status: StatusSupported, Notes: "Returns parsed fragment for local URL values."},
	{Area: "URL", API: "URL.getSalesforceBaseUrl", Status: StatusPartial, Notes: "Deterministic local base URL."},
	{Area: "URL", API: "URL.toExternalForm", Status: StatusSupported, Notes: "Returns the stored local URL string."},
	{Area: "Unsupported", API: "unimplemented platform/stdlib calls", Status: StatusSupported, Notes: "Typed UnsupportedFeature errors with stable message text."},
	{Area: "UserInfo", API: "UserInfo.getFirstName", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user FirstName with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getLanguage", Status: StatusSupported, Notes: "Returns the current runAs/server user LanguageLocaleKey or deterministic en_US default; it does not enable locale-sensitive formatting."},
	{Area: "UserInfo", API: "UserInfo.getLastName", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user LastName with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getLocale", Status: StatusSupported, Notes: "Returns the current runAs/server user LocaleSidKey or deterministic en_US default; it does not enable locale-sensitive formatting."},
	{Area: "UserInfo", API: "UserInfo.getName", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user Name with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getOrganizationId", Status: StatusSupported, Notes: "Returns the deterministic local org ID."},
	{Area: "UserInfo", API: "UserInfo.getProfileId", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user ProfileId with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getSessionId", Status: StatusSupported, Notes: "Returns the deterministic empty local session ID."},
	{Area: "UserInfo", API: "UserInfo.getTimeZone", Status: StatusPartial, Notes: "Returns a TimeZone object for the current user TimeZoneSidKey in the modeled UTC/fixed-offset/named-zone slice; broader Salesforce zone and locale behavior is unsupported."},
	{Area: "UserInfo", API: "UserInfo.getUserEmail", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user Email with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getUserId", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user ID with deterministic fallback."},
	{Area: "UserInfo", API: "UserInfo.getUserName", Status: StatusSupported, Notes: "Returns the current runAs, server, or default local user Username, falling back to the user ID."},
}
