package capability

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
)

type StdlibEntry struct {
	Area   string `json:"area"`
	API    string `json:"api"`
	Status Status `json:"status"`
	Notes  string `json:"notes,omitempty"`
}

func StdlibMatrix() []StdlibEntry {
	entries := append([]StdlibEntry(nil), stdlibEntries...)
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Area == entries[j].Area {
			return entries[i].API < entries[j].API
		}
		return entries[i].Area < entries[j].Area
	})
	return entries
}

func WriteStdlibJSON(w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(StdlibMatrix())
}

func WriteStdlibMarkdown(w io.Writer) error {
	if _, err := fmt.Fprintln(w, "# Standard Library Coverage"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nGenerated from `internal/capability`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\nStatus values match the compatibility dashboard: `supported`, `partial`, `stub`, `unsupported`, and `unknown`."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "\n| Area | API | Status | Notes |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, entry := range StdlibMatrix() {
		if _, err := fmt.Fprintf(w, "| %s | `%s` | `%s` | %s |\n", entry.Area, entry.API, entry.Status, entry.Notes); err != nil {
			return err
		}
	}
	return nil
}

var stdlibEntries = []StdlibEntry{
	{Area: "Async", API: "AsyncApexJob / CronTrigger local records", Status: StatusPartial, Notes: "Test-context enqueue/drain creates deterministic local AsyncApexJob rows and CronTrigger rows for supported future, queueable, batch, and scheduled jobs; broader platform lifecycle fields are not modeled."},
	{Area: "Async", API: "AsyncInfo / AsyncOptions / finalizers", Status: StatusUnsupported, Notes: "Queueable stack metadata, AsyncOptions mutators/accessors and enqueue overloads, and queueable finalizers return explicit UnsupportedFeature diagnostics."},
	{Area: "Async", API: "BatchableContext.getJobId", Status: StatusPartial, Notes: "Returns the deterministic local AsyncApexJob Id while supported batch start/execute/finish methods drain under Test.stopTest."},
	{Area: "Async", API: "QueueableContext.getJobId", Status: StatusPartial, Notes: "Returns the deterministic local AsyncApexJob Id while supported queueables drain under Test.stopTest."},
	{Area: "Async", API: "SchedulableContext.getTriggerId", Status: StatusPartial, Notes: "Returns the deterministic local CronTrigger Id while supported scheduled jobs drain under Test.stopTest."},
	{Area: "ApexPages", API: "ApexPages.addMessage", Status: StatusSupported, Notes: "Stores page messages on the VM instance."},
	{Area: "ApexPages", API: "ApexPages.currentPage", Status: StatusSupported, Notes: "Returns a deterministic local PageReference."},
	{Area: "ApexPages", API: "ApexPages.getMessages", Status: StatusSupported, Notes: "Returns VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.hasMessages", Status: StatusSupported, Notes: "Checks VM-local page messages."},
	{Area: "ApexPages", API: "ApexPages.Message", Status: StatusPartial, Notes: "Constructor plus severity, summary, and detail getters; no Visualforce rendering lifecycle."},
	{Area: "Approval", API: "Approval process APIs", Status: StatusUnsupported, Notes: "Approval.process and approval lock helpers return explicit UnsupportedFeature diagnostics; approval workflow side effects are not locally modeled."},
	{Area: "Auth", API: "token/cloud APIs", Status: StatusUnsupported, Notes: "Auth namespace token and session/cloud calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Blob", API: "Blob.size", Status: StatusSupported, Notes: "Returns local Blob byte length."},
	{Area: "Blob", API: "Blob.toString", Status: StatusSupported, Notes: "Returns UTF-8 local Blob bytes as a string and rejects invalid UTF-8 data."},
	{Area: "Blob", API: "Blob.valueOf", Status: StatusSupported, Notes: "Stores the string bytes in a local Blob value."},
	{Area: "Crypto", API: "Crypto.areEqualConstantTime", Status: StatusSupported, Notes: "Constant-time local Blob equality comparison."},
	{Area: "Crypto", API: "Crypto.encrypt/decrypt/sign/verify", Status: StatusUnsupported, Notes: "Org key, certificate, encryption, and random key-generation surfaces return explicit unsupported errors."},
	{Area: "Crypto", API: "Crypto.generateDigest", Status: StatusSupported, Notes: "MD5, SHA1, SHA-256, SHA-512, SHA3-256/384/512, with conservative algorithm normalization."},
	{Area: "Crypto", API: "Crypto.generateMac", Status: StatusSupported, Notes: "HMAC MD5, SHA1, SHA256, and SHA512 with local Blob keys and conservative algorithm normalization."},
	{Area: "Canvas", API: "Canvas namespace", Status: StatusUnsupported, Notes: "Canvas app integration calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Continuation", API: "Continuation", Status: StatusUnsupported, Notes: "Continuation construction and callback/response calls return explicit UnsupportedFeature diagnostics."},
	{Area: "List", API: "List.add", Status: StatusSupported, Notes: "Adds typed local values, including indexed insertion."},
	{Area: "List", API: "List.addAll", Status: StatusSupported, Notes: "Appends typed values from local List or Set values."},
	{Area: "List", API: "List.clear", Status: StatusSupported, Notes: "Removes all local list elements."},
	{Area: "List", API: "List.clone", Status: StatusSupported, Notes: "Copies the local list container; elements keep local value identity."},
	{Area: "List", API: "List.contains", Status: StatusSupported, Notes: "Checks local values, including null, using local value equality."},
	{Area: "List", API: "List.copyConstructor", Status: StatusSupported, Notes: "Copies values from a local List or Set constructor argument."},
	{Area: "List", API: "List.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "List", API: "List.get", Status: StatusSupported, Notes: "Indexed lookup with stable bounds errors."},
	{Area: "List", API: "List.indexOf", Status: StatusSupported, Notes: "Local equality search, including null elements, with -1 for misses."},
	{Area: "List", API: "List.isEmpty", Status: StatusSupported, Notes: "Checks local list length."},
	{Area: "List", API: "List.iterator", Status: StatusSupported, Notes: "Returns a deterministic snapshot Iterator for local List values."},
	{Area: "List", API: "List.remove", Status: StatusSupported, Notes: "Indexed removal returns the removed value."},
	{Area: "List", API: "List.set", Status: StatusSupported, Notes: "Indexed replacement with typed value coercion."},
	{Area: "List", API: "List.size", Status: StatusSupported, Notes: "Returns local list length."},
	{Area: "List", API: "List.sort", Status: StatusPartial, Notes: "Deterministic sort for local primitive comparable values; object/Comparable sorting returns an explicit unsupported error."},
	{Area: "LoggingLevel", API: "LoggingLevel.name", Status: StatusSupported, Notes: "Returns deterministic built-in enum member text."},
	{Area: "LoggingLevel", API: "LoggingLevel.ordinal", Status: StatusSupported, Notes: "Returns deterministic built-in enum order for the local logging level set."},
	{Area: "LoggingLevel", API: "LoggingLevel.toString", Status: StatusSupported, Notes: "Returns deterministic built-in enum member text."},
	{Area: "LoggingLevel", API: "LoggingLevel.values", Status: StatusSupported, Notes: "Returns NONE, ERROR, WARN, INFO, DEBUG, FINE, FINER, FINEST in deterministic order."},
	{Area: "Map", API: "Map.clear", Status: StatusSupported, Notes: "Removes all local map entries."},
	{Area: "Map", API: "Map.clone", Status: StatusSupported, Notes: "Copies the local map container; values keep local identity."},
	{Area: "Map", API: "Map.containsKey", Status: StatusSupported, Notes: "Checks local keys, including null keys, using deterministic key encoding."},
	{Area: "Map", API: "Map.containsValue", Status: StatusSupported, Notes: "Checks local values, including null values, using local value equality."},
	{Area: "Map", API: "Map.copyConstructor", Status: StatusSupported, Notes: "Copies entries from a local Map and supports Map<Id,SObject> construction from List<SObject> with non-null unique Ids."},
	{Area: "Map", API: "Map.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "Map", API: "Map.get", Status: StatusSupported, Notes: "Returns local value or null for missing keys."},
	{Area: "Map", API: "Map.isEmpty", Status: StatusSupported, Notes: "Checks local map size."},
	{Area: "Map", API: "Map.keySet", Status: StatusSupported, Notes: "Returns deterministic local key Set, preserving null keys."},
	{Area: "Map", API: "Map.put", Status: StatusSupported, Notes: "Stores typed local entries and returns the previous value."},
	{Area: "Map", API: "Map.putAll", Status: StatusSupported, Notes: "Copies local entries from another Map or SObject rows into Map<Id,SObject> by non-null unique Id."},
	{Area: "Map", API: "Map.remove", Status: StatusSupported, Notes: "Removes a key and returns its previous local value or null."},
	{Area: "Map", API: "Map.size", Status: StatusSupported, Notes: "Returns local map size."},
	{Area: "Map", API: "Map.toString", Status: StatusPartial, Notes: "Deterministic local entry string form; exact platform formatting may differ."},
	{Area: "Map", API: "Map.values", Status: StatusSupported, Notes: "Returns deterministic local values List."},
	{Area: "Set", API: "Set.add", Status: StatusSupported, Notes: "Adds typed local values and reports whether the Set changed."},
	{Area: "Set", API: "Set.addAll", Status: StatusSupported, Notes: "Adds typed values from local List or Set values."},
	{Area: "Set", API: "Set.clear", Status: StatusSupported, Notes: "Removes all local set elements."},
	{Area: "Set", API: "Set.clone", Status: StatusSupported, Notes: "Copies the local set container; elements keep local value identity."},
	{Area: "Set", API: "Set.contains", Status: StatusSupported, Notes: "Checks local values, including null, using local value equality."},
	{Area: "Set", API: "Set.containsAll", Status: StatusSupported, Notes: "Checks local List or Set membership."},
	{Area: "Set", API: "Set.copyConstructor", Status: StatusSupported, Notes: "Copies unique values from a local List or Set constructor argument."},
	{Area: "Set", API: "Set.deepClone", Status: StatusPartial, Notes: "No-argument local recursive clone; SObject preserve-option overloads are unsupported."},
	{Area: "Set", API: "Set.isEmpty", Status: StatusSupported, Notes: "Checks local set length."},
	{Area: "Set", API: "Set.iterator", Status: StatusSupported, Notes: "Returns a deterministic snapshot Iterator for local Set values."},
	{Area: "Set", API: "Set.remove", Status: StatusSupported, Notes: "Removes a local value, including null, and reports whether the Set changed."},
	{Area: "Set", API: "Set.removeAll", Status: StatusSupported, Notes: "Removes local List or Set members."},
	{Area: "Set", API: "Set.retainAll", Status: StatusSupported, Notes: "Retains only local List or Set members."},
	{Area: "Set", API: "Set.size", Status: StatusSupported, Notes: "Returns local set length."},
	{Area: "Search", API: "Search.* / SOSL FIND", Status: StatusUnsupported, Notes: "Cloud search and SOSL execution are not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "REST", API: "RestContext.request / RestContext.response", Status: StatusPartial, Notes: "VM-local static slots support RestRequest assignment and lazy RestResponse creation; no platform request lifecycle dispatch is modeled."},
	{Area: "REST", API: "RestRequest / RestResponse object shapes", Status: StatusPartial, Notes: "Local request/response objects expose URI/path/method/address, params, headers, Blob body, status, and add/get helper methods covered by compatibility fixtures; broader platform lifecycle remains unsupported."},
	{Area: "REST", API: "@RestResource local server dispatch", Status: StatusUnsupported, Notes: "Custom Apex REST dispatch returns a stable unsupported error from the local server."},
	{Area: "Database", API: "Database.convertLead", Status: StatusUnsupported, Notes: "Lead conversion returns an explicit UnsupportedFeature diagnostic until local lead/account/contact/opportunity side effects are modeled."},
	{Area: "Database", API: "Database.delete", Status: StatusSupported, Notes: "DML pipeline with result/error shapes for supported SObjects."},
	{Area: "Database", API: "Database.emptyRecycleBin", Status: StatusPartial, Notes: "Permanently removes already-deleted local rows and returns EmptyRecycleBinResult-shaped objects; retention policy and related platform recycle-bin behavior are not modeled."},
	{Area: "Database", API: "Database.getQueryLocator", Status: StatusPartial, Notes: "Supported SOQL only; executes eagerly for local batch scopes and exposes getQuery()/iterator() over the local snapshot."},
	{Area: "Database", API: "Database.insert", Status: StatusSupported, Notes: "DML pipeline with result/error shapes for supported SObjects."},
	{Area: "Database", API: "Database.lock / Database.unlock", Status: StatusPartial, Notes: "Toggles local storage row lock state and returns LockResult/UnlockResult-shaped objects; ownership, wait timing, and transaction-scoped lock release are not modeled."},
	{Area: "Database", API: "Database.merge", Status: StatusPartial, Notes: "Local merge behavior for supported account/contact-style data."},
	{Area: "Database", API: "Database.rollback", Status: StatusPartial, Notes: "Local org-state savepoint rollback; no external side effects."},
	{Area: "Database", API: "Database.setSavepoint", Status: StatusPartial, Notes: "Local org-state snapshots with later-savepoint invalidation."},
	{Area: "Database", API: "Database.undelete", Status: StatusPartial, Notes: "Soft-delete restoration for supported local records with ENTITY_IS_NOT_DELETED SaveResult errors for active rows."},
	{Area: "Database", API: "Database.update", Status: StatusSupported, Notes: "DML pipeline with result/error shapes for supported SObjects."},
	{Area: "Database", API: "Database.upsert", Status: StatusPartial, Notes: "Schema-backed external-ID matching for supported local records."},
	{Area: "Data", API: "Custom metadata/custom settings getAll/getInstance", Status: StatusPartial, Notes: "Fixture-backed local __mdt and list custom setting static access supports namespace-stripped object/field names and read-only returned records; hierarchy merge behavior and Metadata API mutation are not modeled."},
	{Area: "Date", API: "Date.addDays", Status: StatusSupported, Notes: "Local Gregorian date arithmetic."},
	{Area: "Date", API: "Date.addMonths", Status: StatusPartial, Notes: "Local Gregorian arithmetic with month-end clamp; full Salesforce edge-case parity incomplete."},
	{Area: "Date", API: "Date.addYears", Status: StatusPartial, Notes: "Local Gregorian arithmetic with leap-day clamp; full Salesforce edge-case parity incomplete."},
	{Area: "Date", API: "Date.day", Status: StatusSupported, Notes: "Returns Gregorian day of month."},
	{Area: "Date", API: "Date.daysBetween", Status: StatusSupported, Notes: "Returns whole calendar days between local Date values."},
	{Area: "Date", API: "Date.month", Status: StatusSupported, Notes: "Returns Gregorian month number."},
	{Area: "Date", API: "Date.newInstance", Status: StatusSupported, Notes: "Validates date parts in the local year 1-9999 Gregorian slice."},
	{Area: "Date", API: "Date.today", Status: StatusPartial, Notes: "Deterministic VM clock date in UTC."},
	{Area: "Date", API: "Date.toEndOfMonth", Status: StatusSupported, Notes: "Returns last day of the Date value's month."},
	{Area: "Date", API: "Date.toStartOfMonth", Status: StatusSupported, Notes: "Returns first day of the Date value's month."},
	{Area: "Date", API: "Date.valueOf", Status: StatusSupported, Notes: "Parses strict yyyy-MM-dd strings plus yyyy-MM-dd time forms into local Date values with stable invalid-input errors."},
	{Area: "Date", API: "Date.year", Status: StatusSupported, Notes: "Returns Gregorian year."},
	{Area: "Datetime", API: "Datetime.addDays", Status: StatusPartial, Notes: "UTC-local arithmetic; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.addHours", Status: StatusPartial, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMilliseconds", Status: StatusPartial, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMinutes", Status: StatusPartial, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addMonths", Status: StatusPartial, Notes: "UTC-local arithmetic with month-end clamp; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.addSeconds", Status: StatusPartial, Notes: "UTC-local arithmetic."},
	{Area: "Datetime", API: "Datetime.addYears", Status: StatusPartial, Notes: "UTC-local arithmetic with leap-day clamp; no user timezone or DST model."},
	{Area: "Datetime", API: "Datetime.date", Status: StatusPartial, Notes: "Returns UTC-modeled Date component; no user timezone model."},
	{Area: "Datetime", API: "Datetime.dateGmt", Status: StatusSupported, Notes: "Returns the UTC Date component."},
	{Area: "Datetime", API: "Datetime.day", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.format", Status: StatusPartial, Notes: "Deterministic UTC/fixed-offset Java-pattern slice plus America/Los_Angeles DST formatting; user locale and user timezone are unsupported."},
	{Area: "Datetime", API: "Datetime.formatGmt", Status: StatusPartial, Notes: "Deterministic UTC Java-pattern slice with stable token errors; locale patterns are not modeled beyond pinned English names."},
	{Area: "Datetime", API: "Datetime.hour", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.millisecond", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.minute", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.month", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.newInstance", Status: StatusSupported, Notes: "Validates date and time parts in the local year 1-9999 UTC-modeled slice."},
	{Area: "Datetime", API: "Datetime.newInstanceGmt", Status: StatusSupported, Notes: "Constructs a UTC-modeled Datetime."},
	{Area: "Datetime", API: "Datetime.now", Status: StatusPartial, Notes: "Deterministic VM clock timestamp in UTC."},
	{Area: "Datetime", API: "Datetime.second", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Datetime", API: "Datetime.timeGmt", Status: StatusSupported, Notes: "Returns the UTC Time component."},
	{Area: "Datetime", API: "Datetime.valueOf", Status: StatusSupported, Notes: "Parses supported strict datetime strings with stable invalid-input errors."},
	{Area: "Datetime", API: "Datetime.valueOfGmt", Status: StatusSupported, Notes: "Parses supported strict UTC/RFC3339 datetime strings with stable invalid-input errors."},
	{Area: "Datetime", API: "Datetime.year", Status: StatusPartial, Notes: "UTC-modeled component getter."},
	{Area: "Decimal", API: "Decimal.abs", Status: StatusSupported, Notes: "Absolute value for local Decimal values."},
	{Area: "Decimal", API: "Decimal.doubleValue", Status: StatusSupported, Notes: "Returns local Decimal value."},
	{Area: "Decimal", API: "Decimal.format", Status: StatusPartial, Notes: "Simple deterministic finite numeric formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Decimal", API: "Decimal.intValue", Status: StatusSupported, Notes: "Truncates to 32-bit Integer with overflow checks."},
	{Area: "Decimal", API: "Decimal.longValue", Status: StatusSupported, Notes: "Truncates to local Long representation with overflow checks."},
	{Area: "Decimal", API: "Decimal.pow", Status: StatusSupported, Notes: "Power with Integer exponent for finite local Decimal results."},
	{Area: "Decimal", API: "Decimal.round", Status: StatusPartial, Notes: "Default half-up plus local RoundingMode subset; exact Decimal scale parity is not modeled."},
	{Area: "Decimal", API: "Decimal.setScale", Status: StatusPartial, Notes: "Supports local scale 0-15 with UP, DOWN, CEILING, FLOOR, HALF_UP, HALF_DOWN, HALF_EVEN, and UNNECESSARY."},
	{Area: "Decimal", API: "Decimal.valueOf", Status: StatusSupported, Notes: "Parses finite decimal strings and numeric values, including trimmed signed strings."},
	{Area: "Double", API: "Double.format", Status: StatusPartial, Notes: "Simple deterministic finite numeric formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Double", API: "Double.valueOf", Status: StatusSupported, Notes: "Parses finite decimal strings and numeric values into the local numeric representation, including trimmed signed strings."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Decode", Status: StatusSupported, Notes: "Blob-shaped local value with stable invalid-input errors."},
	{Area: "EncodingUtil", API: "EncodingUtil.base64Encode", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertFromHex", Status: StatusSupported, Notes: "Blob-shaped local value with stable odd-length and invalid-input errors."},
	{Area: "EncodingUtil", API: "EncodingUtil.convertToHex", Status: StatusSupported, Notes: "Blob-shaped local value."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlDecode", Status: StatusPartial, Notes: "Uses query unescape with UTF-8/utf8/UTF_8 charset validation only; other charsets return UnsupportedFeature."},
	{Area: "EncodingUtil", API: "EncodingUtil.urlEncode", Status: StatusPartial, Notes: "Uses query escape with UTF-8/utf8/UTF_8 charset validation only; other charsets return UnsupportedFeature."},
	{Area: "Exception", API: "Exception.getCause", Status: StatusPartial, Notes: "Returns the locally initialized cause value; repeat/self-cause platform edge rules are not modeled."},
	{Area: "Exception", API: "Built-in exception types", Status: StatusPartial, Notes: "Known public built-in exception tokens construct message-bearing local exceptions and assign to Exception; exact platform class catalog, line numbers, and stack text remain partial."},
	{Area: "Exception", API: "Exception.getLineNumber", Status: StatusPartial, Notes: "Returns deterministic local throw-site line metadata when available; otherwise 0."},
	{Area: "Exception", API: "Exception.getMessage", Status: StatusSupported, Notes: "Returns the local exception message."},
	{Area: "Exception", API: "Exception.getStackTraceString", Status: StatusPartial, Notes: "Returns the local VM stack trace captured at throw time when available."},
	{Area: "Exception", API: "Exception.getTypeName", Status: StatusSupported, Notes: "Returns the local exception type name without System namespace prefix."},
	{Area: "Exception", API: "Exception.initCause", Status: StatusPartial, Notes: "Stores a local Exception cause or null for later getCause calls."},
	{Area: "Exception", API: "Exception.toString", Status: StatusPartial, Notes: "Returns System-prefixed built-in exception text for local exception values."},
	{Area: "EventBus", API: "EventBus.publish", Status: StatusUnsupported, Notes: "Platform event publish calls return explicit UnsupportedFeature diagnostics."},
	{Area: "FeatureManagement", API: "FeatureManagement.checkPermission", Status: StatusPartial, Notes: "Checks local runAs permission-list state."},
	{Area: "HTTP", API: "Http.send", Status: StatusPartial, Notes: "Mock-first local callouts with request validation and callout accounting; real network transport unsupported."},
	{Area: "HTTP", API: "HttpRequest", Status: StatusPartial, Notes: "Endpoint, method, case-insensitive headers, timeout validation/defaults, body, and blob body accessors."},
	{Area: "HTTP", API: "HttpResponse", Status: StatusPartial, Notes: "Status, status code, case-insensitive headers, body, and blob body accessors."},
	{Area: "JSON", API: "JSON.createGenerator", Status: StatusSupported, Notes: "Creates deterministic local JSONGenerator instances."},
	{Area: "JSON", API: "JSON.createParser", Status: StatusPartial, Notes: "Creates deterministic local JSONParser token streams for valid JSON strings."},
	{Area: "JSON", API: "JSON.deserialize", Status: StatusPartial, Notes: "Primitive, platform scalar, List, Map<String,Object/value>, SObject, and class shapes for the supported local subset; stable mapping errors for mismatched typed shapes and unsupported local object targets."},
	{Area: "JSON", API: "JSON.deserializeStrict", Status: StatusPartial, Notes: "Rejects unknown fields for supported schema/class targets; otherwise shares the bounded typed local mapping subset."},
	{Area: "JSON", API: "JSON.deserializeUntyped", Status: StatusPartial, Notes: "Maps JSON into local primitive/list/map values with deterministic null and number handling."},
	{Area: "JSON", API: "JSONGenerator", Status: StatusPartial, Notes: "Object/array boundaries, field names, scalar string/number/Boolean/null, Date/Datetime/Time/Id/Blob, Object and validated raw value writers, getAsString, close, isClosed, and stable invalid-order errors."},
	{Area: "JSON", API: "JSONParser", Status: StatusPartial, Notes: "Token navigation, current token/name/text, integer/long/decimal/double/Boolean/date/datetime/time/id/blob accessors, nextValue, skipChildren current-name state, and clearCurrentToken for deterministic local JSON."},
	{Area: "JSON", API: "JSONToken", Status: StatusPartial, Notes: "Common parser token constants for object, array, field, string, number, Boolean, and null tokens."},
	{Area: "JSON", API: "JSON.serialize", Status: StatusPartial, Notes: "Includes suppressApexObjectNulls overload for supported object fields; map/list nulls are preserved for supported values."},
	{Area: "JSON", API: "JSON.serializePretty", Status: StatusPartial, Notes: "Pretty output for supported values with object-field null suppression and map/list null preservation."},
	{Area: "Iterator", API: "Iterator.hasNext", Status: StatusSupported, Notes: "Checks remaining elements in a local collection snapshot."},
	{Area: "Iterator", API: "Iterator.next", Status: StatusSupported, Notes: "Returns the next element from a local collection snapshot and raises NoSuchElementException when exhausted."},
	{Area: "Iterator", API: "Iterator.remove", Status: StatusUnsupported, Notes: "Returns an explicit unsupported error; mutating collection iterators are not modeled."},
	{Area: "Id", API: "Id.getSObjectType", Status: StatusPartial, Notes: "Resolves local schema key prefixes and a bounded common standard prefix table to Schema.SObjectType tokens; unknown shape-valid prefixes return a stable error."},
	{Area: "Id", API: "Id.to15", Status: StatusSupported, Notes: "Converts validated 18-character IDs to their 15-character prefix."},
	{Area: "Id", API: "Id.to18", Status: StatusSupported, Notes: "Adds or preserves the documented 3-character checksum for validated IDs."},
	{Area: "Id", API: "Id.valueOf", Status: StatusSupported, Notes: "Validates 15-character IDs and strict 18-character checksum suffixes; restoreCasing rebuilds casing from checksum suffixes."},
	{Area: "Integer", API: "Integer.MAX_VALUE", Status: StatusSupported, Notes: "Exposes the public 32-bit Integer maximum constant."},
	{Area: "Integer", API: "Integer.MIN_VALUE", Status: StatusSupported, Notes: "Exposes the public 32-bit Integer minimum constant."},
	{Area: "Integer", API: "Integer.doubleValue", Status: StatusSupported, Notes: "Converts local Integer values to the local numeric representation."},
	{Area: "Integer", API: "Integer.format", Status: StatusPartial, Notes: "Simple deterministic base-10 formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Integer", API: "Integer.valueOf", Status: StatusSupported, Notes: "Parses integer strings and numeric values with 32-bit overflow checks, including trimmed signed strings."},
	{Area: "Limits", API: "Limits.get*", Status: StatusPartial, Notes: "SOQL, DML, heap, CPU, async, callout, and email counters; unmodeled documented getters return explicit unsupported diagnostics."},
	{Area: "Long", API: "Long.MAX_VALUE", Status: StatusSupported, Notes: "Exposes the public 64-bit Long maximum constant."},
	{Area: "Long", API: "Long.MIN_VALUE", Status: StatusSupported, Notes: "Exposes the public 64-bit Long minimum constant."},
	{Area: "Long", API: "Long.format", Status: StatusPartial, Notes: "Simple deterministic base-10 formatting; locale and pattern overloads return explicit unsupported errors."},
	{Area: "Long", API: "Long.valueOf", Status: StatusSupported, Notes: "Parses integer strings and numeric values with overflow checks, including trimmed signed strings."},
	{Area: "Math", API: "Math.E", Status: StatusSupported, Notes: "Euler's number from Go's deterministic math constant."},
	{Area: "Math", API: "Math.PI", Status: StatusSupported, Notes: "Pi from Go's deterministic math constant."},
	{Area: "Math", API: "Math.abs", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.acos", Status: StatusSupported, Notes: "Finite deterministic result for inputs in [-1, 1]."},
	{Area: "Math", API: "Math.asin", Status: StatusSupported, Notes: "Finite deterministic result for inputs in [-1, 1]."},
	{Area: "Math", API: "Math.atan", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.atan2", Status: StatusSupported, Notes: "Finite deterministic result for two numeric values."},
	{Area: "Math", API: "Math.ceil", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.cos", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.exp", Status: StatusSupported, Notes: "Finite deterministic result; overflow is reported."},
	{Area: "Math", API: "Math.floor", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.log", Status: StatusSupported, Notes: "Finite deterministic result for positive numeric values."},
	{Area: "Math", API: "Math.log10", Status: StatusSupported, Notes: "Finite deterministic result for positive numeric values."},
	{Area: "Math", API: "Math.max", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.min", Status: StatusSupported, Notes: "Integer and Decimal values."},
	{Area: "Math", API: "Math.mod", Status: StatusSupported, Notes: "Integer remainder and Decimal modulus with zero-divisor errors."},
	{Area: "Math", API: "Math.pow", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.round", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.roundToLong", Status: StatusSupported, Notes: "Rounds to local Long representation with overflow checks."},
	{Area: "Math", API: "Math.signum", Status: StatusSupported, Notes: "Returns -1, 0, or 1 for local numeric values."},
	{Area: "Math", API: "Math.sin", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Math", API: "Math.sqrt", Status: StatusSupported, Notes: "Numeric values."},
	{Area: "Math", API: "Math.tan", Status: StatusSupported, Notes: "Finite deterministic result for numeric values."},
	{Area: "Messaging", API: "Messaging.SingleEmailMessage", Status: StatusPartial, Notes: "Common setters only; no delivery transport."},
	{Area: "Messaging", API: "Messaging.SendEmailResult", Status: StatusPartial, Notes: "Local success result exposes isSuccess and getErrors getters."},
	{Area: "Messaging", API: "Messaging.sendEmail", Status: StatusPartial, Notes: "Single-list overload returns local SendEmailResult and increments email limits; transport/options/template surfaces are unsupported."},
	{Area: "Object", API: "Object.equals", Status: StatusSupported, Notes: "Uses local value equality for primitives, collections, platform scalars, and object identity."},
	{Area: "Object", API: "Object.hashCode", Status: StatusSupported, Notes: "Deterministic within local value equality; object identity hashes are request-local."},
	{Area: "Object", API: "Object.toString", Status: StatusSupported, Notes: "Returns local string forms for primitives, collections, platform scalars, and objects."},
	{Area: "PageReference", API: "PageReference", Status: StatusPartial, Notes: "Constructor, URL, redirect, parameters, headers, and string conversion basics."},
	{Area: "QuickAction", API: "QuickAction namespace", Status: StatusUnsupported, Notes: "Quick action UI calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Pattern", API: "Matcher.end", Status: StatusPartial, Notes: "Go regexp-backed group end positions."},
	{Area: "Pattern", API: "Matcher.find", Status: StatusPartial, Notes: "Go regexp-backed matching with captured groups."},
	{Area: "Pattern", API: "Matcher.group", Status: StatusPartial, Notes: "Go regexp-backed group access."},
	{Area: "Pattern", API: "Matcher.groupCount", Status: StatusPartial, Notes: "Capturing group count from Go regexp."},
	{Area: "Pattern", API: "Matcher.lookingAt", Status: StatusPartial, Notes: "Beginning-of-input Go regexp match."},
	{Area: "Pattern", API: "Matcher.matches", Status: StatusPartial, Notes: "Whole-input Go regexp match."},
	{Area: "Pattern", API: "Matcher.region", Status: StatusPartial, Notes: "Bounds matching to a local rune-indexed region; exact Java anchoring/transparent bounds interaction remains partial."},
	{Area: "Pattern", API: "Matcher.regionStart/regionEnd", Status: StatusPartial, Notes: "Returns local rune-indexed region bounds."},
	{Area: "Pattern", API: "Matcher.replaceAll", Status: StatusPartial, Notes: "Go regexp-backed replacement with capture references, region bounds, and basic Java escaped-dollar handling."},
	{Area: "Pattern", API: "Matcher.replaceFirst", Status: StatusPartial, Notes: "Go regexp-backed first replacement with capture references, region bounds, and basic Java escaped-dollar handling."},
	{Area: "Pattern", API: "Matcher.reset", Status: StatusPartial, Notes: "Clears local match state, resets the region to full input, and optionally replaces input."},
	{Area: "Pattern", API: "Matcher.appendReplacement/appendTail", Status: StatusUnsupported, Notes: "Java StringBuffer append-position semantics return explicit unsupported errors."},
	{Area: "Pattern", API: "Matcher.hasAnchoringBounds", Status: StatusPartial, Notes: "Local bounds flag defaults to true; exact region-anchor interaction remains partial."},
	{Area: "Pattern", API: "Matcher.hasTransparentBounds", Status: StatusPartial, Notes: "Local bounds flag defaults to false; exact transparent-bound matching remains partial."},
	{Area: "Pattern", API: "Matcher.useAnchoringBounds", Status: StatusPartial, Notes: "Stores local bounds flag; exact region-anchor interaction remains partial."},
	{Area: "Pattern", API: "Matcher.usePattern", Status: StatusPartial, Notes: "Swaps the local Go regexp Pattern and resets search state within the current region."},
	{Area: "Pattern", API: "Matcher.useTransparentBounds", Status: StatusPartial, Notes: "Stores local bounds flag; exact transparent-bound matching remains partial."},
	{Area: "Pattern", API: "Matcher.start", Status: StatusPartial, Notes: "Go regexp-backed group start positions."},
	{Area: "Pattern", API: "Pattern.compile", Status: StatusPartial, Notes: "Go regexp syntax, not full Java Pattern syntax."},
	{Area: "Pattern", API: "Pattern.matcher", Status: StatusPartial, Notes: "Creates a Go regexp-backed Matcher."},
	{Area: "Pattern", API: "Pattern.matches", Status: StatusPartial, Notes: "Whole-string Go regexp match."},
	{Area: "Pattern", API: "Pattern.pattern", Status: StatusPartial, Notes: "Returns stored Go regexp source."},
	{Area: "Pattern", API: "Pattern.split", Status: StatusPartial, Notes: "Go regexp-backed split with local limit semantics."},
	{Area: "RoundingMode", API: "RoundingMode.valueOf", Status: StatusPartial, Notes: "Constructs supported local Decimal rounding-mode tokens by exact name."},
	{Area: "Schema", API: "Schema.describeSObjects", Status: StatusPartial, Notes: "Object names and SObjectType tokens for local schema."},
	{Area: "Schema", API: "Schema.getGlobalDescribe", Status: StatusPartial, Notes: "Local schema-backed describe map."},
	{Area: "Schema", API: "DescribeFieldResult", Status: StatusPartial, Notes: "Common field metadata and access booleans."},
	{Area: "Schema", API: "DescribeSObjectResult", Status: StatusPartial, Notes: "Common object metadata, fields, record types, and child relationships."},
	{Area: "String", API: "String.abbreviate", Status: StatusSupported, Notes: "Apache-style abbreviation for one- and two-argument forms."},
	{Area: "String", API: "String.charAt", Status: StatusSupported, Notes: "Rune-indexed one-character String."},
	{Area: "String", API: "String.codePointAt", Status: StatusSupported, Notes: "Rune-indexed Unicode code point."},
	{Area: "String", API: "String.codePointBefore", Status: StatusSupported, Notes: "Rune-indexed previous Unicode code point."},
	{Area: "String", API: "String.codePointCount", Status: StatusSupported, Notes: "Counts runes between validated indexes."},
	{Area: "String", API: "String.commonPrefix", Status: StatusSupported, Notes: "Returns the shared rune prefix for two strings."},
	{Area: "String", API: "String.contains", Status: StatusSupported, Notes: "UTF-8 string contains."},
	{Area: "String", API: "String.containsAny", Status: StatusSupported, Notes: "Rune membership."},
	{Area: "String", API: "String.containsNone", Status: StatusSupported, Notes: "Rune exclusion."},
	{Area: "String", API: "String.containsOnly", Status: StatusSupported, Notes: "Rune allow-list."},
	{Area: "String", API: "String.containsWhitespace", Status: StatusSupported, Notes: "Unicode whitespace."},
	{Area: "String", API: "String.countMatches", Status: StatusSupported, Notes: "Non-overlapping literal substring count."},
	{Area: "String", API: "String.difference", Status: StatusSupported, Notes: "Returns the differing suffix from the comparison string."},
	{Area: "String", API: "String.endsWith", Status: StatusSupported, Notes: "UTF-8 string suffix."},
	{Area: "String", API: "String.equalsIgnoreCase", Status: StatusSupported, Notes: "Unicode simple fold."},
	{Area: "String", API: "String.escapeCsv", Status: StatusSupported, Notes: "RFC4180-style quoting and doubled quotes for local strings."},
	{Area: "String", API: "String.escapeEcmaScript", Status: StatusPartial, Notes: "JavaScript-style backslash escaping for common deterministic cases."},
	{Area: "String", API: "String.escapeHtml3", Status: StatusPartial, Notes: "Deterministic core HTML entity escaping only; full named-entity coverage is not modeled."},
	{Area: "String", API: "String.escapeHtml4", Status: StatusPartial, Notes: "Deterministic core HTML entity escaping only; full named-entity coverage is not modeled."},
	{Area: "String", API: "String.escapeJava", Status: StatusPartial, Notes: "Java-style backslash and Unicode escaping for deterministic core cases."},
	{Area: "String", API: "String.escapeSingleQuotes", Status: StatusSupported, Notes: "Escapes single quotes with backslashes."},
	{Area: "String", API: "String.escapeUnicode", Status: StatusPartial, Notes: "Escapes non-ASCII and control runes as UTF-16 Unicode escapes."},
	{Area: "String", API: "String.escapeXml", Status: StatusPartial, Notes: "Escapes XML core entities; XML version-specific validity is not modeled."},
	{Area: "String", API: "String.escapeXml10", Status: StatusPartial, Notes: "Alias of local XML core entity escaping; XML 1.0 character validity is not modeled."},
	{Area: "String", API: "String.escapeXml11", Status: StatusPartial, Notes: "Alias of local XML core entity escaping; XML 1.1 character validity is not modeled."},
	{Area: "String", API: "String.format", Status: StatusPartial, Notes: "Deterministic {0}-style list substitution; full MessageFormat locale behavior is not modeled."},
	{Area: "String", API: "String.fromCharArray", Status: StatusSupported, Notes: "Builds a string from valid Unicode code point integers."},
	{Area: "String", API: "String.getChars", Status: StatusSupported, Notes: "Returns Unicode code point integers for each rune."},
	{Area: "String", API: "String.getCommonPrefix", Status: StatusSupported, Notes: "Returns the shared rune prefix for a list of strings."},
	{Area: "String", API: "String.getLevenshteinDistance", Status: StatusSupported, Notes: "Rune-based edit distance."},
	{Area: "String", API: "String.indexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.indexOfAny", Status: StatusSupported, Notes: "Returns the first rune index whose character appears in the search set."},
	{Area: "String", API: "String.indexOfAnyBut", Status: StatusSupported, Notes: "Returns the first rune index whose character is outside the search set."},
	{Area: "String", API: "String.isAllLowerCase", Status: StatusSupported, Notes: "All letters lowercase; non-letters ignored."},
	{Area: "String", API: "String.isAllUpperCase", Status: StatusSupported, Notes: "All letters uppercase; non-letters ignored."},
	{Area: "String", API: "String.isAlpha", Status: StatusSupported, Notes: "Unicode letters."},
	{Area: "String", API: "String.isAlphaSpace", Status: StatusSupported, Notes: "Unicode letters and space characters."},
	{Area: "String", API: "String.isAlphanumeric", Status: StatusSupported, Notes: "Unicode letters and decimal digits."},
	{Area: "String", API: "String.isAlphanumericSpace", Status: StatusSupported, Notes: "Unicode letters, decimal digits, and space characters."},
	{Area: "String", API: "String.isBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isNotBlank", Status: StatusSupported, Notes: "Null and whitespace."},
	{Area: "String", API: "String.isAsciiPrintable", Status: StatusSupported, Notes: "Checks ASCII printable range 0x20 through 0x7E."},
	{Area: "String", API: "String.isNumeric", Status: StatusSupported, Notes: "Unicode decimal digits."},
	{Area: "String", API: "String.isNumericSpace", Status: StatusSupported, Notes: "Unicode decimal digits and space characters."},
	{Area: "String", API: "String.isWhitespace", Status: StatusSupported, Notes: "Unicode whitespace; empty string is true."},
	{Area: "String", API: "String.join", Status: StatusSupported, Notes: "List values and separator."},
	{Area: "String", API: "String.hashCode", Status: StatusSupported, Notes: "Java-compatible UTF-16 code-unit string hash for local values."},
	{Area: "String", API: "String.lastIndexOf", Status: StatusSupported, Notes: "UTF-8 byte index behavior from Go strings."},
	{Area: "String", API: "String.lastIndexOfAny", Status: StatusSupported, Notes: "Returns the last rune index whose character appears in the search set."},
	{Area: "String", API: "String.lastOrdinalIndexOf", Status: StatusSupported, Notes: "Finds the nth occurrence from the end using rune indexes."},
	{Area: "String", API: "String.length", Status: StatusSupported, Notes: "Counts runes."},
	{Area: "String", API: "String.ordinalIndexOf", Status: StatusSupported, Notes: "Finds the nth occurrence from the start using rune indexes."},
	{Area: "String", API: "String.overlay", Status: StatusSupported, Notes: "Overlays text between clamped rune indexes."},
	{Area: "String", API: "String.replace", Status: StatusSupported, Notes: "Literal replacement; empty targets are a no-op."},
	{Area: "String", API: "String.replaceAll", Status: StatusPartial, Notes: "Go regexp-backed replacement."},
	{Area: "String", API: "String.replaceFirst", Status: StatusPartial, Notes: "Go regexp-backed first replacement."},
	{Area: "String", API: "String.replaceIgnoreCase", Status: StatusSupported, Notes: "Literal non-overlapping replacement with rune-wise case folding."},
	{Area: "String", API: "String.replaceOnce", Status: StatusSupported, Notes: "First literal replacement only."},
	{Area: "String", API: "String.remove", Status: StatusSupported, Notes: "Literal non-overlapping removal; empty targets are a no-op."},
	{Area: "String", API: "String.removeEnd", Status: StatusSupported, Notes: "Removes a literal suffix when present."},
	{Area: "String", API: "String.removeEndIgnoreCase", Status: StatusSupported, Notes: "Removes a literal suffix with rune-wise case folding when present."},
	{Area: "String", API: "String.removeIgnoreCase", Status: StatusSupported, Notes: "Literal non-overlapping removal with rune-wise case folding."},
	{Area: "String", API: "String.removeStart", Status: StatusSupported, Notes: "Removes a literal prefix when present."},
	{Area: "String", API: "String.removeStartIgnoreCase", Status: StatusSupported, Notes: "Removes a literal prefix with rune-wise case folding when present."},
	{Area: "String", API: "String.rotate", Status: StatusSupported, Notes: "Rune-based rotation; positive shifts rotate right."},
	{Area: "String", API: "String.split", Status: StatusPartial, Notes: "Go regexp-backed split with Apex limit shape."},
	{Area: "String", API: "String.splitByCharacterType", Status: StatusSupported, Notes: "Splits on coarse Unicode upper/lower/digit/space/other groups."},
	{Area: "String", API: "String.splitByCharacterTypeCamelCase", Status: StatusSupported, Notes: "Splits character types with camel-case upper-to-lower adjustment."},
	{Area: "String", API: "String.startsWith", Status: StatusSupported, Notes: "UTF-8 string prefix."},
	{Area: "String", API: "String.strip", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from both ends."},
	{Area: "String", API: "String.stripAll", Status: StatusSupported, Notes: "Strips each string in a list with optional strip-character set."},
	{Area: "String", API: "String.stripEnd", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from the end."},
	{Area: "String", API: "String.stripStart", Status: StatusSupported, Notes: "Strips Unicode whitespace or a supplied rune set from the start."},
	{Area: "String", API: "String.stripToEmpty", Status: StatusSupported, Notes: "Strips whitespace and returns an empty string for all-blank values."},
	{Area: "String", API: "String.stripToNull", Status: StatusSupported, Notes: "Strips whitespace and returns null for all-blank values."},
	{Area: "String", API: "String.substring", Status: StatusSupported, Notes: "Rune-indexed substring."},
	{Area: "String", API: "String.swapCase", Status: StatusSupported, Notes: "Unicode upper/lower rune case swap."},
	{Area: "String", API: "String.toLowerCase", Status: StatusSupported, Notes: "Go Unicode lowercasing."},
	{Area: "String", API: "String.toUpperCase", Status: StatusSupported, Notes: "Go Unicode uppercasing."},
	{Area: "String", API: "String.trim", Status: StatusSupported, Notes: "Unicode whitespace trim."},
	{Area: "String", API: "String.unescapeCsv", Status: StatusSupported, Notes: "Unquotes doubled-quote CSV fields."},
	{Area: "String", API: "String.unescapeEcmaScript", Status: StatusPartial, Notes: "Unescapes common JavaScript-style backslash and Unicode escapes."},
	{Area: "String", API: "String.unescapeHtml3", Status: StatusPartial, Notes: "Unescapes core HTML entities, selected high-use HTML 3/4 named entities, and numeric references; remaining unknown named entities stay unchanged."},
	{Area: "String", API: "String.unescapeHtml4", Status: StatusPartial, Notes: "Unescapes core HTML entities, selected high-use HTML 3/4 named entities, and numeric references; remaining unknown named entities stay unchanged."},
	{Area: "String", API: "String.unescapeJava", Status: StatusPartial, Notes: "Unescapes common Java-style backslash and Unicode escapes."},
	{Area: "String", API: "String.unescapeUnicode", Status: StatusPartial, Notes: "Unescapes UTF-16 Unicode escape sequences."},
	{Area: "String", API: "String.unescapeXml", Status: StatusPartial, Notes: "Unescapes XML core entities and numeric references; XML version-specific validity is not modeled."},
	{Area: "String", API: "String.unescapeXml10", Status: StatusPartial, Notes: "Alias of local XML core/numeric entity unescaping; XML 1.0 validity is not modeled."},
	{Area: "String", API: "String.unescapeXml11", Status: StatusPartial, Notes: "Alias of local XML core/numeric entity unescaping; XML 1.1 validity is not modeled."},
	{Area: "String", API: "String.valueOf", Status: StatusSupported, Notes: "Local value string conversion."},
	{Area: "System", API: "System.assert", Status: StatusSupported, Notes: "Assertion failure returns runtime error; Object and null message values use deterministic local string conversion."},
	{Area: "System", API: "System.assertEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error with deterministic local expected/actual text and Object/null message conversion."},
	{Area: "System", API: "System.assertNotEquals", Status: StatusSupported, Notes: "Assertion failure returns runtime error with deterministic local value text and Object/null message conversion."},
	{Area: "System", API: "System.asyncScheduling", Status: StatusUnsupported, Notes: "System.abortJob and scheduleBatch return explicit unsupported diagnostics; broader local async lifecycle control is not modeled."},
	{Area: "System", API: "System.currentTimeMillis", Status: StatusPartial, Notes: "Returns deterministic VM-clock epoch milliseconds."},
	{Area: "System", API: "System.debug", Status: StatusSupported, Notes: "One-argument and LoggingLevel overloads are collected in result debug output; null, LoggingLevel, and modeled Exception values use deterministic string forms; log framework text parity is not claimed."},
	{Area: "System", API: "System.isBatch", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isFuture", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isQueueable", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.isScheduled", Status: StatusPartial, Notes: "Returns false in the local non-async VM context."},
	{Area: "System", API: "System.now", Status: StatusPartial, Notes: "Returns deterministic VM-clock Datetime."},
	{Area: "System", API: "System.today", Status: StatusPartial, Notes: "Returns deterministic VM-clock Date."},
	{Area: "Test", API: "Test.clearApexPageMessages", Status: StatusSupported, Notes: "Clears VM-local ApexPages messages in test context."},
	{Area: "Test", API: "Test.createSoqlStub", Status: StatusUnsupported, Notes: "SOQL stub creation is not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.createStub", Status: StatusUnsupported, Notes: "Dynamic stub creation is not locally modeled; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.getStandardPricebookId", Status: StatusPartial, Notes: "Deterministic test-context-only ID."},
	{Area: "Test", API: "Test.isRunningTest", Status: StatusSupported, Notes: "Reflects local test context."},
	{Area: "Test", API: "Test.setFixedSearchResults", Status: StatusUnsupported, Notes: "Fixed SOSL search results are deferred with the local search surface; calls return explicit UnsupportedFeature diagnostics."},
	{Area: "Test", API: "Test.setMock", Status: StatusPartial, Notes: "HttpCalloutMock support for local tests; other mock interfaces return explicit unsupported diagnostics."},
	{Area: "Test", API: "Test.startTest", Status: StatusPartial, Notes: "Governor-window reset/restore for supported counters."},
	{Area: "Test", API: "Test.stopTest", Status: StatusPartial, Notes: "Drains supported async work."},
	{Area: "Time", API: "Time.addHours", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addMilliseconds", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addMinutes", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.addSeconds", Status: StatusSupported, Notes: "Local time arithmetic with 24-hour wrap."},
	{Area: "Time", API: "Time.hour", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.millisecond", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.minute", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.newInstance", Status: StatusSupported, Notes: "Validates time parts including optional millisecond."},
	{Area: "Time", API: "Time.second", Status: StatusSupported, Notes: "Local time component."},
	{Area: "Time", API: "Time.valueOf", Status: StatusSupported, Notes: "Parses strict HH:mm:ss and HH:mm:ss.SSS strings with stable invalid-input errors."},
	{Area: "TimeZone", API: "TimeZone.getDisplayName", Status: StatusPartial, Notes: "Returns deterministic ID text for UTC, fixed GMT offsets, and America/Los_Angeles; DST/locale overloads are unsupported."},
	{Area: "TimeZone", API: "TimeZone.getID", Status: StatusPartial, Notes: "Returns canonical UTC, fixed GMT offset ID, or the supported America/Los_Angeles named zone."},
	{Area: "TimeZone", API: "TimeZone.getOffset", Status: StatusPartial, Notes: "Returns fixed offset milliseconds for the deterministic offset slice and America/Los_Angeles DST decisions; other named zones are unsupported."},
	{Area: "TimeZone", API: "TimeZone.getTimeZone", Status: StatusPartial, Notes: "Supports UTC/GMT, fixed GMT/UTC offsets through ±14:00, and America/Los_Angeles; other named zones and trimmed/invalid IDs are unsupported."},
	{Area: "Type", API: "Type.forName", Status: StatusPartial, Notes: "Local class/type token lookup, common local SObjects, built-in and generic collection type strings, and null for null/blank/unknown local names."},
	{Area: "Type", API: "Type.equals", Status: StatusSupported, Notes: "Compares local Type tokens by type name."},
	{Area: "Type", API: "Type.getName", Status: StatusSupported, Notes: "Returns local type token name."},
	{Area: "Type", API: "Type.hashCode", Status: StatusSupported, Notes: "Matches the local String.hashCode of the type name."},
	{Area: "Type", API: "Type.isAssignableFrom", Status: StatusPartial, Notes: "Uses the local class/interface and built-in exception hierarchy."},
	{Area: "Type", API: "Type.newInstance", Status: StatusPartial, Notes: "Constructs local values and dispatches zero-arg constructors for registered classes; unbacked namespace/package tokens return explicit unsupported errors."},
	{Area: "Type", API: "Type.toString", Status: StatusSupported, Notes: "Returns the local type token name."},
	{Area: "URL", API: "URL", Status: StatusPartial, Notes: "Constructors for deterministic absolute URL specs, context/spec resolution, and protocol/host/file forms with stable malformed input errors."},
	{Area: "URL", API: "URL.getAuthority", Status: StatusSupported, Notes: "Returns parsed authority for local URL values."},
	{Area: "URL", API: "URL.getDefaultPort", Status: StatusSupported, Notes: "Returns HTTP/HTTPS defaults or -1."},
	{Area: "URL", API: "URL.getFile", Status: StatusSupported, Notes: "Returns path plus query for local URL values."},
	{Area: "URL", API: "URL.getHost", Status: StatusSupported, Notes: "Returns parsed hostname for local URL values."},
	{Area: "URL", API: "URL.getCurrentRequestUrl", Status: StatusUnsupported, Notes: "Cloud request context is not modeled; returns an explicit unsupported error."},
	{Area: "URL", API: "URL.getOrgDomainUrl", Status: StatusPartial, Notes: "Deterministic local org URL."},
	{Area: "URL", API: "URL.getPath", Status: StatusSupported, Notes: "Returns parsed path for local URL values."},
	{Area: "URL", API: "URL.getPort", Status: StatusSupported, Notes: "Returns explicit port or -1."},
	{Area: "URL", API: "URL.getProtocol", Status: StatusSupported, Notes: "Returns parsed scheme for local URL values."},
	{Area: "URL", API: "URL.getQuery", Status: StatusSupported, Notes: "Returns parsed query for local URL values."},
	{Area: "URL", API: "URL.getRef", Status: StatusSupported, Notes: "Returns parsed fragment for local URL values."},
	{Area: "URL", API: "URL.getSalesforceBaseUrl", Status: StatusPartial, Notes: "Deterministic local base URL."},
	{Area: "URL", API: "URL.toExternalForm", Status: StatusSupported, Notes: "Returns the stored local URL string."},
	{Area: "Unsupported", API: "unimplemented platform/stdlib calls", Status: StatusSupported, Notes: "Typed UnsupportedFeature errors with stable message text."},
	{Area: "UserInfo", API: "UserInfo.getFirstName", Status: StatusPartial, Notes: "Current runAs/server/default user."},
	{Area: "UserInfo", API: "UserInfo.getLanguage", Status: StatusPartial, Notes: "Deterministic local value."},
	{Area: "UserInfo", API: "UserInfo.getLastName", Status: StatusPartial, Notes: "Current runAs/server/default user."},
	{Area: "UserInfo", API: "UserInfo.getLocale", Status: StatusPartial, Notes: "Deterministic local value."},
	{Area: "UserInfo", API: "UserInfo.getName", Status: StatusPartial, Notes: "Current runAs/server/default user."},
	{Area: "UserInfo", API: "UserInfo.getOrganizationId", Status: StatusPartial, Notes: "Local org identity."},
	{Area: "UserInfo", API: "UserInfo.getProfileId", Status: StatusPartial, Notes: "Current runAs/server/default user."},
	{Area: "UserInfo", API: "UserInfo.getSessionId", Status: StatusPartial, Notes: "Empty local session value."},
	{Area: "UserInfo", API: "UserInfo.getTimeZone", Status: StatusPartial, Notes: "Deterministic UTC value."},
	{Area: "UserInfo", API: "UserInfo.getUserEmail", Status: StatusPartial, Notes: "Current runAs/server/default user."},
	{Area: "UserInfo", API: "UserInfo.getUserId", Status: StatusPartial, Notes: "Current runAs/server/default user."},
}
