package capability

import "testing"

func TestBuildStubBehaviorReportUsesStdlibEvidence(t *testing.T) {
	report := BuildStubBehaviorReport()
	if report.SchemaVersion != StubBehaviorSchemaVersion {
		t.Fatalf("schema version = %d", report.SchemaVersion)
	}
	if report.Totals.Entries == 0 || report.Totals.Members == 0 || report.Totals.Types == 0 {
		t.Fatalf("empty report totals: %+v", report.Totals)
	}
	if report.Totals.ByStatus[string(StubBehaviorImplemented)] == 0 || report.Totals.ByStatus[string(StubBehaviorPassiveDefault)] == 0 {
		t.Fatalf("missing expected status totals: %+v", report.Totals)
	}
	if report.Totals.ByStatus[string(StubBehaviorUnknown)] != 0 {
		t.Fatalf("unexpected unknown behavior entries: %+v", report.Totals)
	}

	entries := map[string]StubBehaviorEntry{}
	for _, entry := range report.Entries {
		entries[entry.ID] = entry
	}
	stringTrim := findStubBehaviorEntry(entries, "String.trim(")
	if stringTrim == nil {
		t.Fatalf("missing String.trim entry")
	}
	if stringTrim.Status != StubBehaviorImplemented {
		t.Fatalf("String.trim status = %q", stringTrim.Status)
	}
	if len(stringTrim.Evidence) == 0 {
		t.Fatalf("String.trim missing evidence")
	}
	searchFind := findStubBehaviorEntry(entries, "Search.find(")
	if searchFind == nil {
		t.Fatalf("missing Search.find entry")
	}
	if searchFind.Status != StubBehaviorImplemented {
		t.Fatalf("Search.find status = %q", searchFind.Status)
	}
	pageCtor := findStubBehaviorEntry(entries, "PageReference.<init>(")
	if pageCtor == nil {
		t.Fatalf("missing PageReference constructor")
	}
	if pageCtor.Status != StubBehaviorImplemented {
		t.Fatalf("PageReference constructor status = %q", pageCtor.Status)
	}
}

func TestStubBehaviorSeparatesServiceMethodsFromPassiveDTOs(t *testing.T) {
	report := BuildStubBehaviorReport()
	entries := map[string]StubBehaviorEntry{}
	for _, entry := range report.Entries {
		entries[entry.ID] = entry
	}

	assertStubBehaviorPrefix(t, entries, "ConnectApi.Organization.getSettings(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterUsers.getFollowings(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterFeeds.setTestGetFeedElementsFromFeed(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterUsers.getFollowers(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterFeeds.getFeed(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterFeeds.getFeedElementsFromFeed(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterGroups.searchGroups(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Recommendations.getRecommendationsForUser(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ManagedContent.getAllManagedContent(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ManagedContentDelivery.getChannels(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ManagedTopics.getManagedTopics(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ManagedContentSpaces.getManagedContentSpaces(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Announcements.getAnnouncements(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterFavorites.getFavorites(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommerceCatalog.getGiftWrapProducts(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommerceSearch.getSortRules(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.NamedCredentials.getNamedCredentials(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.NavigationMenu.getCommunityNavigationMenu(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpQuery.getAllMetadata(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpQuery.querySql(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpQuery.querySqlStatus(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpQuery.cancelQuerySql(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpCalculatedInsight.getCalculatedInsights(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpCalculatedInsight.runCalculatedInsight(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpCatalog.getLineage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpOptimizationConnectApi.postDataModelObjectQueryCount(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpSegment.getSegments()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpQuickAttributes.getQuickAttributes(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CdpMachineLearning.predict(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.EinsteinLLM.getPromptTemplates(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.EinsteinLLM.generateMessages(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Personalization.getAudiences(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Personalization.updateAudience(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.SmartDataDiscovery.getAIModels(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.SmartDataDiscovery.predict(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Communities.getCommunities(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommunityModeration.getFlagsOnComment(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.RecordAlert.getRecordAlerts(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Records.getMotif(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.RecordUi.getPicklistValuesByRecordType(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Sharing.getRecordAccessDetail(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.UserProfiles.getUserProfile(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommerceCart.getCartSummary(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommerceCart.getOrCreateActiveCartSummary(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.CommerceWishlist.getWishlistSummaries(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.Billing.generateInvoices(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ChatterFeeds.postFeedElement(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ManagedContent.publish(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.RecordAlert.performRecordAlertAction(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.UserProfiles.setPhoto(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.NamedCredentials.getOAuthCredentialAuthUrl(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Social.DefaultInboundSocialPostHandler.handleInboundSocialPost(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Social.DefaultInboundSocialPostHandler.createPersonaParent(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Social.InboundSocialPostHandlerImpl.handleInboundSocialPost(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Social.InboundSocialPostHandlerImpl.getPostTagsThatCreateCase()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Process.SparkPlugApi.describePlugins()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "TrailblazerIdentity.getUserOrgInfo(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "TxnSecurity.EventCondition.evaluate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "workflow.Action.invoke(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "eventbus.EventPublishSuccessCallback.onSuccess(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Ideas.findSimilar(SObject)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Ideas.getAllRecentReplies(String,String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Ideas.getReadRecentReplies(String,String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Ideas.getUnreadRecentReplies(String,String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Ideas.markRead(String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.ABnExperimentActionEnum.Start()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.FeedElement.getBuildVersion(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.FeedElement.body(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Schema.describeDataCategoryGroups(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.describeDataCategoryGroupStructures(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.DataCategoryGroupSobjectTypePair.setSobject(String)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Schema.DataCategoryGroupSobjectTypePair.getDataCategoryGroupName()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.DataCategory.getChildCategories()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Flow.Interview.createInterview(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Flow.Interview.start(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Flow.Interview.getVariableValue(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cache.OrgPartition.get(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cache.Org.get(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cache.OrgPartition.createFullyQualifiedKey(String,String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cache.Org.getMissRate()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "cache.SecondaryKeyApi.putImmediate(String,Object,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "cache.SecondaryKeyApi.scanForKeyValues(String,String,Integer)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Continuation.addHttpRequest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Http.send(HttpRequest)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Http.send(Object)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "HttpRequest.setClientCertificate(String,String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "HttpRequest.setClientCertificateName(String)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Search.query(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Search.find(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.describeTabs(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.getAppDescribe(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schema.getModuleDescribe(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Formula.builder()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Formula.recalculateFormulas(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DataWeave.Script.createScript(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DataWeave.Script.execute(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Datacloud.FindDuplicates.findDuplicates(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Datacloud.FindDuplicatesByIds.findDuplicatesByIds(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DomainParser.parse(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DomainParser.parse(Url)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FeatureManagement.changeProtection(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "NLPPredictions.FAQPrediction.predict(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "NLPPredictions.PredictionHandler.handlePredictionRequest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "NLPPredictions.PredictionHandler.handlePredictionResponse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Metadata.Operations.enqueueDeployment(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Metadata.Operations.checkDeployStatus(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Metadata.Operations.retrieve(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "OrgInstrumentationOperation.start(OrgMetricPublishTypeEnum)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "OrgInstrumentationContext.startTime()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "OrgInstrumentationContext.end()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "OrgInstrumentationService.propagateContext(HttpRequest)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "reports.ReportManager.describeReport(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "reports.ReportManager.getDatatypeFilterOperatorMap(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "reports.ReportManager.runReport(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "reports.ReportManager.runAsyncReport(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "IsvPartners.AppAnalytics.logCustomInteraction(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.UserProvisioningLog.log(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "pref_center.TokenUtility.generateToken(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "pref_center.TokenUtility.generateTokens(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Packaging.getCurrentPackageId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApptBooking.WaitlistController.call(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApptBooking.WaitlistController.invokeMethod(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "BcpProvisionService.enableC2C()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DistributedLedgerService.enableC2C()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "BusRuleDtMig.DecisionTableMigrationService.migrateDecisionTables(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "BusinessRule.CalculationMatrixMigrationService.migrate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "BusinessRule.CalculationProcedureMigrationService.migrate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "BusinessRule.DecisionMatrixRowMigratorService.migrate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.isCoreAllowed()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.isLibraryInUse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Aura.redirect(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ChatterAnswers.AccountCreator.createAccount(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LiveAgent.LiveAgentRealTimeSystem.routeChatRequests(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LiveAgent.LiveChatRouter.doRouting(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RichMessaging.ProcessFormHandler.processFormRequest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RichMessaging.ProcessPaymentHandler.processPaymentRequest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Site.UrlRewriter.generateUrlFor(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Site.createPersonAccountPortalUser(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Network.createExternalUserAsync(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Support.EinsteinBots.sendMessageToBot(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Support.EmailTemplateSelector.getDefaultEmailTemplateId(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Support.LifeScienceAttendees.parse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.runMask(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.getJobs(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.getRunLogResponse(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "data_mask.DataMaskIntegrationUtil.cancelJob(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "PushUpgradeCustomizationRepository.create(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "PushUpgradeCustomizationRepository.getCustomUpgradeAllowedForId(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "PushUpgradeCustomizationRepository.getCustomUpgradeTypeForIndex(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "PushUpgradeCustomizationRepository.setCustomUpgradeAllowedForIndex(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "PushUpgradeCustomizationRepository.deleteById(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.LoginFormController.getUsernamePasswordSelfRegEnabled()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.LoginFormController.login(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.SelfRegisterController.getExtraFields(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.SelfRegisterController.selfRegister(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "applauncher.SocialLoginController.getAuthProviders()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.SocialLoginController.getSsoUrl(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "fschousehold.FSCFinancialAccountService.call(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "fscwmgen.RecordAlertProvider.getAlertsByWhatId(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "fscwmgen.RecordAlertProvider.dismissAlert(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.AppointmentBookingInterop.findSlots(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.AppointmentBookingInterop.bookAppointment(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.IntegratedCareManagementApexUtil.checkCreateAccess(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "id_verification.IdentityVerificationExt.search(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ind_docgen_api.OpenInterface.invokeMethod(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "industries_docgen.DocumentTemplate.Call(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "service_cloud_voice.GroupSetup.listGroups(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "service_cloud_voice.GroupSetup.createGroup(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "UserManagement.initPasswordlessLogin(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserManagement.verifyPasswordlessLogin(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserManagement.sendAsyncEmailConfirmation(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.CommittingBatchable.start(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.DeletingBatchable.execute(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.FlowProvisionBase.hasFlow()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.UserProvisioningPlugin.describe()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.UserProvisioningProcessHandler.invoke(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FormulaRecalcResult.isSuccess()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FormulaRecalcResult.getSObject()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FormulaRecalcResult.getErrors()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FormulaRecalcFieldError.getFieldName()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FormulaRecalcFieldError.getFieldError()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SObjectAccessDecision.getRecords()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SObjectAccessDecision.getRemovedFields()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SObjectAccessDecision.getModifiedIndexes()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "InstallContext.previousVersion()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "InstallContext.installerId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SandboxContext.organizationId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SandboxContext.sandboxId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SandboxContext.sandboxName()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RequestImpl.getCurrent()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UIRequest.getCurrent()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UIRequest.getRequestHeader(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QueueableContext.getJobId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SchedulableContext.getTriggerId()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.Batchable.start(Database.BatchableContext)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.Batchable.execute(Database.BatchableContext,List<Object>)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.Batchable.finish(Database.BatchableContext)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Queueable.execute(QueueableContext)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Finalizer.execute(FinalizerContext)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Metadata.DeployCallback.handleResult(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Process.Plugin.describe()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Process.Plugin.invoke(Process.PluginRequest)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.UserProvisioningPlugin.invoke(Process.PluginRequest)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.QuickActionDefaultsHandler.onInitDefaults(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RestResponse.addHeader(String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Iterable.iterator()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Iterator.hasNext()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "VisualEditor.DataRow.isSelected()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "VisualEditor.DataRow.compareTo(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Search.SuggestionOption.setFilter(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Search.SuggestionOption.setLimit(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.executeBatch(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.convertLead(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Database.treeSave(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Callable.call(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "StubProvider.handleMethodCall(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RestRequest.addHeader(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RestRequest.addParameter(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.createSoqlStub(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.invokeContinuationMethod(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.setContinuationResponse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.testNotificationActionHandler(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.renderEmailTemplate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.sendEmailMessage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.extractInboundEmail(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.InboundEmailHandler.handleInboundEmail(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.NotificationActionHandler.executeAction(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.CustomNotification.send(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.PushNotification.send(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Messaging.PushNotificationPayload.apple(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.testSandboxPostCopyScript(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SandboxPostCopy.runApexClass(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Schedulable.execute(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Assert.isInstanceOfType(Object,Type)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Assert.isNotInstanceOfType(Object,Type)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Apex.Stack.push(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Apex.Stack.pop()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApexPages.addMessages(Object)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApexPages.Action.getExpression()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApexPages.Action.invoke()", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ApexPages.Component.getComponentById(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApexPages.StandardSetController.getListViewOptions()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ApexPages.StandardSetController.setPageNumber(Integer)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "AsyncInfo.getCurrentQueueableStackDepth()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "AsyncInfo.getMaximumQueueableStackDepth()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "AsyncInfo.getMinimumQueueableDelayInMinutes()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CURRENCY.newInstance(Decimal,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CURRENCY.format()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cases.generateThreadingMessageId(Id)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cases.getCaseIdFromEmailThreadId(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Cases.reparentFeedToCaseId(Id,Id,Id)", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "EmailMessages.getFormattedThreadingToken(Id)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "EmailMessages.getRecordIdFromEmail(String,String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Collator.getInstance()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Collator.compare(String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SObject.getQuickActionName()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.describeAvailableQuickActions(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.describeQuickActions(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.retrieveQuickActionTemplate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.retrieveQuickActionTemplates(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "QuickAction.performQuickAction(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.newSendEmailQuickActionDefaults(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Datacloud.FindDuplicates.findDuplicates(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Datacloud.FindDuplicatesByIds.findDuplicatesByIds(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "DomainParser.parse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FeatureManagement.changeProtection(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.publishArticle(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.editOnlineArticle(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.deleteArchivedArticle(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.deleteArchivedArticleVersion(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.deleteDraftArticle(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "KbManagement.PublishingService.deleteDraftTranslation(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Packaging.getCurrentPackageId(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "RemoteObjectController.retrieve(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SupportPredictiveService.findSimilarCases(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "FlexQueue.moveJobToFront(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "System.pauseJobById(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "System.purgeOldAsyncJobs(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "System.changeOwnPassword(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "System.movePassword(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "System.process(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "System.resetPassword(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "System.resetPasswordWithEmailTemplate(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "System.submit(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.AppointmentBookingSelfService.findProviders(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.AppointmentBookingSelfService.bookSelfServiceAppointment(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "healthcloudext.IntegratedCareManagementApexHelper.checkObjectCreationAccess(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LoyaltyManagement.LoyaltyResources.getPointsBalance(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LoyaltyManagement.LoyaltyResources.creditPoints(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "LoyaltyManagement.WidgetVisibility.checkVisibility(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "industries_docgen.DocGenPermsAndAccessChecksService.hasDocGenOrgPerm(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "inventorypricing.GetInventoryPricing.getInventory(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ime_mrm.EventManagementBudgetApi.getMngEventBudgets(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ime_mrm.EventManagementBudgetApi.createMngEventBudget(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "RevSalesTrxn.PlaceSalesTransactionExecutor.execute(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "SObject.getValues(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LIST.addToRelationship(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LIST.getAddedToRelationship()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LIST.getMarkedForDeletion()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "LIST.markForDelete(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Map.containsKey(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Map.keySet()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Map.values()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Type.isAssignableFrom(Type)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Matcher.hitEnd()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Matcher.pattern()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Matcher.quoteReplacement(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Matcher.requireEnd()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UUID.fromString(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Version.major()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Version.minor()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Version.patch()", StubBehaviorImplemented)
	for _, typeName := range []string{"Boolean", "Date", "Datetime", "Decimal", "Double", "Id", "Integer", "Long", "String", "Time"} {
		assertStubBehaviorPrefix(t, entries, typeName+".addError(String)", StubBehaviorImplemented)
		assertStubBehaviorPrefix(t, entries, typeName+".addError(Exception)", StubBehaviorImplemented)
	}
	assertStubBehaviorPrefix(t, entries, "QueueableDuplicateSignature.Builder.addString(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Builder.addString(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Process.InputParameter.<init>(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.Builder.withDeliverToCity(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.add(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.clear()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.get(Integer)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.indexOf(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.isEmpty()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.iterator()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.remove(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartAdjustmentBasisList.size()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "CartExtension.OptionalCartItem.empty()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.OptionalCartItem.of(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.OptionalCartItem.isPresent()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.OptionalCartItem.get()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartTestUtil.createCart()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartTestUtil.getCart(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.CartCalculateExecutorMock.calculate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.PricingCartCalculator.calculate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.SplitShipmentService.arrangeItems(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CartExtension.SplitShipmentServiceMock.arrangeItems(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "CommerceDxSampleapp.CommerceDx_Inventory.calculateInventoryLevel(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "WebStoreContext.getCommerceContext()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "commercepayments.ClientSidePaymentAdapter.getClientComponentName()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "commerce_ordermanagement.ProductExpandService.returnReasons(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "pref_center.LoadFormData.addOption(String,String,String)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "pref_center.LoadFormData.setTextValue(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlTester.setMockRows(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlTester.clearMocks()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlRowIterator.hasNext()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlRowIterator.next()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlStatement.execute()", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "commercestorepricing.PricingRequestItemCollection.size()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "commercestorepricing.PricingRequestItemCollection.get(Integer)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "commercestorepricing.PricingService.processPrice(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "commercestoretax.ProductIdCollection.getFromList(Integer)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "commercestoretax.GetStoreTaxesInfoResponse.addTaxesInfo(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "commercestoretax.TaxService.processCalculateTaxes(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "SF_Archive.ArchiverAccessor.performArchiverGlobalSearch(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SF_Archive.ArchiverAccessor.maskArchivedRecords(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "ime_mrm.EventManagementBudgetApi.invokeMethod(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ime_mrm.EventManagementBudgetApi.createMngEventBudget(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "wavetemplate.Access.integUserHasAccessToSObjectField(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wavetemplate.Answers.put(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wave.Dags.getDags(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wave.NodeType.valueOf(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wave.ProjectionType.ordinal()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wave.QueryNode.execute(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "applauncher.AppLauncherSetupReordererController.getModel()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "applauncher.ChangePasswordController.changePassword(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "setup_service_livemessage.MessagingChannelAppleDomainController.getApplePayDomain(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "setup_service_livemessage.MessagingChannelAppleDomainController.uploadDomainVerificationCertificate(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "pref_center.PreferenceCenterApexHandler.load(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "formulaeval.FormulaInstance.getReferencedFields()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "aiaccelerator.CustomFeatureExtractor.extractFeatures(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfdc_enablement.LearningItemSerializeDeserializer.serialize(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "omnichannel.RouteWorkApexController.search(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "omnichannel.RouteWorkApexController.routeWork(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "mapslite.MapsLiteUtils.userHasMaps()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "mapslite.MapsLiteUtils.falconGeocodeRecords(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "mlplatform.PredictionServiceClient.predictions(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "industries_clm.OpenInterface.invokeMethod(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "embeddedMessaging.EmbeddedMessagingSessionHandler.handleRequestWithSfdcSession(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "YubiAuthForAloha.validateYubiKeyLogin(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "OrgMonitorFramework.executeBlackTabRequest(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "RevSignaling.SignalingApexProcessor.execute(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Slack.ChatPostMessageRequest.builder()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Slack.ChatPostMessageRequest.Builder.channel(String)", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Slack.Message.getText()", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Slack.Message.canBeSeenByUser(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.Button.click()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.Channel.sendMessage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.Checkbox.toggleValue()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.CheckboxGroup.toggleValue(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.ExternalSelect.query(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.Modal.submit()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.Overflow.clickOption(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.authTest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.usersInfo(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.bookmarksList(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.reactionsGet(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.conversationsListConnectInvites(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.chatPostMessage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.chatUpdate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.viewsOpen(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.viewsPublish(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClient.bookmarksAdd(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "Slack.AppClient.authTest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClientMock.authTest(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Slack.BotClientMock.chatPostMessage(", StubBehaviorPassiveDefault)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.apiTest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.teamInfo(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.searchAll(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.teamAccessLogs(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.usersIdentity(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.chatPostEphemeral(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.chatScheduleMessage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.viewsOpen(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserClient.viewsUpdate(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserSession.openChannel(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserSession.postMessage(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserSession.getMessageCount()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserSession.getMessages()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserSession.executeSlashCommand(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.ActionDispatcher.allowUnauthenticatedUsers()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.EventDispatcher.invoke(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserProvisioningProvider.importUsers(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.UserMappingUrlServiceProvider.generateSlackAuthorizationUrl(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Slack.RunnableHandler.run()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Canvas.Test.mockRenderContext(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "eventbus.TestBroker.deliver()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "eventbus.TestEventService.publishEvent(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "HttpCalloutMock.respond(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "WebServiceMock.doInvoke(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "WebServiceCallout.invoke(Object,Object,Map,List)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "WebServiceCallout.invoke(Object,Object,Map<String,Object>,List<String>)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "WebServiceCallout.beginInvoke(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "WebServiceCallout.endInvoke(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "SoqlStubProvider.handleSoqlQuery(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ExternalServiceTest.sendCallback(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "TestAsyncHttp.executeHttpRequest(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "functions.FunctionInvokeMock.respond(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "functions.MockFunctionInvocationFactory.createSuccessResponse(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "functions.Function.get(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "functions.Function.invoke(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "functions.FunctionCallback.handleResponse(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "functions.FunctionInvocable.invoke(", StubBehaviorUnsupported)
	assertStubBehaviorPrefix(t, entries, "CommerceExtension.ResolutionStrategy.resolve()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Readiness.ProductEvaluator.evaluateReadiness(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Readiness.ProductEvaluator.isActive()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "SubMgmt.Test.create(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "UserProvisioning.ConnectorTestUtil.createConnectedApp(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.getExternalService()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Test.invokePage(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Canvas.CanvasLifecycleHandler.excludeContextTypes()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.BaseEndpointExtension.beforeGet(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "ConnectApi.BaseEndpointExtension.afterGet(", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "sfsqlquery.SqlQueueable.getRows()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "wave.Templates.getTemplates()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "XmlStreamReader.<init>(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "XmlStreamReader.next()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "XmlStreamReader.getAttributeValue(String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "XmlStreamReader.toString()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.Document.load(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.Document.createRootElement(String,String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.Document.getRootElement()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.Document.toXmlString()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.XmlNode.addChildElement(String,String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.XmlNode.getChildElements()", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.XmlNode.getNamespaceFor(String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "dom.XmlNode.removeAttribute(String,String)", StubBehaviorImplemented)
	assertStubBehaviorPrefix(t, entries, "Exception.getInaccessibleFields()", StubBehaviorImplemented)
}

func assertStubBehaviorPrefix(t *testing.T, entries map[string]StubBehaviorEntry, prefix string, want StubBehaviorStatus) {
	t.Helper()
	entry := findStubBehaviorEntry(entries, prefix)
	if entry == nil {
		t.Fatalf("missing stub behavior entry with prefix %q", prefix)
	}
	if entry.Status != want {
		t.Fatalf("%s status = %q, want %q", entry.ID, entry.Status, want)
	}
}

func findStubBehaviorEntry(entries map[string]StubBehaviorEntry, prefix string) *StubBehaviorEntry {
	for id, entry := range entries {
		if len(id) >= len(prefix) && id[:len(prefix)] == prefix {
			found := entry
			return &found
		}
	}
	return nil
}
