// Code generated by glade-tools salesforce release; DO NOT EDIT.

package server

import "github.com/glade-sh/glade/internal/apexversion"

var generatedToolingObjectAvailability = map[string]apexversion.Range{
	"CustomNotifActionDef":          {Since: 66},
	"CustomNotificationActionGroup": {Since: 66},
	"ExtConvParticipantIntegDef":    {Since: 66},
	"SandboxProcessStage":           {Since: 66},
}
