// Code generated by glade-tools salesforce release; DO NOT EDIT.

package compile

import "github.com/glade-sh/glade/internal/apexversion"

var generatedLWCModuleAvailability = map[string]apexversion.Range{
	"experience/blockBuilderApi": {Since: 66},
}
