import { expect, test } from '@playwright/test'

test('approved hero retains pending edits, cancels stale runs, and supports keyboard tabs', async ({ page }) => {
 const errors: string[] = []
 page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
 page.on('pageerror', error => errors.push(error.message))
 await page.goto('/#install-cmd')
 await expect(page.locator('#install-cmd')).toContainText('curl -fsSL https://glade.sh/install.sh | sh')
 const output = page.locator('#demo-output')
 await expect(output).toContainText('1 test executed · 1 passed · 0 failed')
 await page.locator('#demo-change').click()
 await expect(output).toContainText('Run the example')
 await page.locator('#demo-tab-debug').click()
 await expect(output).toContainText('acc.Name = "Acme"')
 await page.locator('#demo-tab-tests').click()
 await expect(output).toContainText('Run the example')
 await expect(output).not.toContainText('Passed')
 await page.locator('#run-demo').click()
 await expect(output).toContainText('Expected: Other, Actual: Acme')
 await page.locator('#demo-tab-tests').press('End')
 await expect(page.locator('#demo-tab-check')).toBeFocused()
 await expect(output).toContainText('Cannot resolve variable acountName')
 await page.locator('#demo-change').click()
 await expect(output).toContainText('Run the check')
 await page.locator('#run-demo').click()
 await page.locator('#demo-tab-debug').click()
 await page.waitForTimeout(850)
 await expect(output).toContainText('Paused at breakpoint')
 await page.locator('#run-demo').click()
 await expect(output).toContainText('Local debug session completed')
 await page.locator('#run-demo').click()
 await expect(output).toContainText('Paused at breakpoint')
 await page.locator('#tool-terminal').click()
 await expect(page.locator('#panel-terminal')).toBeVisible()
 await expect(page.locator('#panel-vscode')).toBeHidden()
 await expect(page.locator('#demo-tab-debug')).toHaveAttribute('aria-selected', 'true')
 await page.locator('#tool-terminal').press('End')
 await expect(page.locator('#panel-agent')).toBeVisible()
 expect(errors).toEqual([])
})

test('home copy denial offers manual copying and mobile menu restores focus', async ({ page }) => {
 await page.setViewportSize({ width: 390, height: 844 })
 await page.goto('/')
 const menu = page.locator('#menu-toggle')
 await menu.click()
 await expect(page.locator('#mobile-nav')).toBeVisible()
 await page.locator('#mobile-nav a').first().focus()
 await page.keyboard.press('Escape')
 await expect(menu).toBeFocused()
 await expect(menu).toHaveAttribute('aria-expanded', 'false')
 await menu.click()
 await page.locator('#mobile-nav a[href="#workflow"]').click()
 await expect(page.locator('#workflow')).toBeFocused()
 await expect(page.locator('#mobile-nav')).toBeHidden()
 await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('denied') } } }) })
 await page.locator('#copy-install').click()
 await expect(page.locator('#toast')).toContainText('Command selected')
 expect(await page.evaluate(() => window.getSelection()?.toString())).toBe('curl -fsSL https://glade.sh/install.sh | sh')
 await expect(page.locator('#copy-install')).not.toHaveAttribute('aria-label', 'Install command copied')
})

test('home serves useful content without JavaScript', async ({ browser }) => {
 const context = await browser.newContext({ javaScriptEnabled: false })
 const page = await context.newPage()
 await page.goto('/')
 await expect(page.locator('#demo-code')).toContainText('AccountServiceTest')
 await expect(page.locator('#demo-output')).toContainText('1 test executed · 1 passed · 0 failed')
 await expect(page.locator('#install-command')).toHaveText('curl -fsSL https://glade.sh/install.sh | sh')
 await expect(page.locator('#run-demo')).toBeDisabled()
 await expect(page.locator('.site-footer').getByRole('link', { name: 'Docs', exact: true })).toBeVisible()
 await context.close()
})
