import { expect, test } from '@playwright/test'

test('sealed assurance preserves its rows, filters, empty feedback, and reading appearance', async ({ page }) => {
  await page.goto('/guide/support-map')
  await page.evaluate(() => localStorage.setItem('vitepress-theme-appearance', 'light'))
  await page.goto('/private-corpus-assurance.html')
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  await expect(page.getByRole('link', { name: 'Glade home' })).toBeVisible()
  await expect(page.getByRole('main')).toBeVisible()
  await expect(page.locator('#namespace')).toHaveCSS('appearance', 'auto')
  const data = await page.locator('#assurance-data').evaluate(element => JSON.parse(element.textContent!))
  await expect(page.locator('#rows tr')).toHaveCount(data.rows.length)
  await expect(page.locator('#repository-rows tr')).toHaveCount(data.repositorySurfaceRows.length)
  await expect(page.locator('#repository-summaries tr')).toHaveCount(data.repositorySummaries.length)
  expect(await page.locator('#rows tr td:first-child').allTextContents()).toEqual(data.rows.map((row: { surfaceId: string }) => row.surfaceId))

  await page.getByRole('combobox', { name: 'Namespace', exact: true }).selectOption(data.rows[0].namespace)
  const filtered = data.rows.filter((row: { namespace: string }) => row.namespace === data.rows[0].namespace)
  await expect(page.locator('#rows tr')).toHaveCount(filtered.length)
  await expect(page.getByRole('status')).toContainText(`${filtered.length} matching sealed surface rows`)
  await page.getByLabel('Search', { exact: true }).fill('no-such-sealed-surface')
  await expect(page.getByRole('status')).toContainText('No sealed rows match')
  await expect(page.locator('#rows')).toHaveText('No sealed rows match these filters.')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(page.getByLabel('Search', { exact: true })).toBeFocused()
  await expect(page.locator('#rows tr')).toHaveCount(data.rows.length)
  await expect(page.getByRole('status')).toHaveText('All sealed surface rows are shown.')
  await page.getByRole('button', { name: 'Switch to dark appearance' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  expect(await page.evaluate(() => localStorage.getItem('vitepress-theme-appearance'))).toBe('dark')
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(11, 17, 25)')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'What runs locally', exact: true }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
})
