import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

test('every capability row is reachable and pagination survives reload and history', async ({ page }) => {
  await page.goto('/guide/support-map')
  const results = page.locator('.support-explorer-result')
  const rows = page.locator('.support-explorer-list > li')
  const next = page.getByRole('button', { name: 'Next', exact: true })
  await expect(rows).toHaveCount(25)
  const seen: string[] = []
  const catalog = JSON.parse(readFileSync(new URL('../../docs-src/public/data/editor-support.json', import.meta.url), 'utf8'))
  const expected = catalog.rows.map((row: { api: string }) => row.api)
  let total = 0
  do {
    for (const label of await rows.locator(':scope > div > code').allTextContents()) { seen.push(label); total++ }
    if (await next.isDisabled()) break
    await next.click()
  } while (true)
  expect(total).toBeGreaterThan(50)
  expect(seen.sort()).toEqual(expected.sort())
  await expect(results).toContainText(`${total} matching rows of ${total}`)
  const lastURL = page.url()
  await page.reload()
  await expect(next).toBeDisabled()
  expect(page.url()).toBe(lastURL)
  await page.goBack()
  await expect(next).toBeEnabled()
  await page.getByRole('button', { name: 'First', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled()
  await expect(page).not.toHaveURL(/page=/)
})

test('capability raw statuses, query restoration, empty recovery, and model limits stay distinct', async ({ page }) => {
  await page.goto('/guide/support-map?q=Answers.findSimilar&status=supported&page=999')
  const results = page.locator('.support-explorer-result')
  await expect(page.getByRole('searchbox', { name: 'Search APIs' })).toHaveValue('Answers.findSimilar')
  await expect(results).toContainText('1 matching row')
  await expect(page.locator('.support-explorer-list')).toContainText(/deterministic empty.*List<Id>/)
  await expect(page.locator('.support-explorer-list')).toContainText('Execution classification')
  await expect(page.locator('.support-explorer-list')).toContainText('does not attach a live Salesforce parity receipt')
  const status = page.getByRole('combobox', { name: 'Status', exact: true })
  for (const value of ['partial', 'stub', 'unknown', 'unsupported']) {
    await status.selectOption(value)
    await expect(results).toContainText('0 matching rows')
    await expect(page).toHaveURL(new RegExp(`status=${value}`))
  }
  await page.reload()
  await expect(status).toHaveValue('unsupported')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(page.getByRole('searchbox', { name: 'Search APIs' })).toHaveValue('')
  await expect(status).toHaveValue('all')
  await expect(page.locator('.support-explorer-list > li')).toHaveCount(25)
})

test('command lookup searches actual flags and preserves complete reference anchors', async ({ page }) => {
  await page.goto('/reference/cli')
  const search = page.locator('[data-command-lookup]')
  await expect(search).toBeInViewport()
  await search.fill('--shard-count')
  const matches = page.locator('.docs-command-lookup-results')
  await expect(matches).toContainText('glade test')
  await expect(matches).toContainText('--shard-count')
  await expect(page.locator('#glade-test')).toBeAttached()
  await expect(page.locator('#glade-version')).toBeAttached()
  const link = matches.getByRole('link', { name: 'glade test', exact: true })
  await link.click()
  await expect(page).toHaveURL(/#glade-test$/)
  await search.fill('--project')
  expect(await matches.locator('li').count()).toBeGreaterThan(20)
  expect((await matches.boundingBox())!.height).toBeLessThanOrEqual(450)
  await matches.focus()
  await page.keyboard.press('ControlOrMeta+End')
  await matches.locator('a').last().focus()
  await expect(matches.locator('a').last()).toBeInViewport()
  await matches.locator('a').last().press('Enter')
  const target = new URL(page.url()).hash
  await expect(page.locator(target)).toBeInViewport()
  await search.fill('not-a-real-flag-98347')
  await expect(page.locator('[data-command-lookup-status]')).toContainText('0 reference sections')
  await expect(matches.locator('li')).toHaveCount(0)
})

test('workbench replay is disclosed, keyboard-operable, and cleans up on navigation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/guide/workbench')
  await expect(page.getByText('Edits stay in this browser.', { exact: false })).toBeVisible()
  await expect(page.getByText('This is a scripted illustration:', { exact: false })).toBeVisible()
  await expect(page.locator('a[href="/reference/cli#glade-playground"]')).toBeVisible()
  const tabs = page.getByRole('tablist', { name: 'Demo workflows' }).getByRole('tab')
  await tabs.first().focus()
  await page.keyboard.press('End')
  await expect(tabs.last()).toBeFocused()
  await expect(tabs.last()).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('button', { name: 'Replay scenario', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Replay again', exact: true })).toBeVisible()
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  const command = await page.locator('#workbench-command').innerText()
  await page.getByRole('button', { name: 'Copy workbench command', exact: true }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(command)
  await page.locator('[data-scenario-id="check"]').click()
  await page.getByRole('button', { name: 'Replay scenario', exact: true }).click()
  await page.locator('.glade-cm-head a[href="/guide/support-map"]').click()
  await expect(page.locator('.support-explorer')).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Replay scenario', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})


test('capability controls are near the top and editor jump links reach their tools', async ({ page }) => {
  await page.goto('/guide/support-map')
  await expect(page.getByRole('searchbox', { name: 'Search APIs' })).toBeInViewport()
  await page.goto('/guide/workbench')
  const editorLink = page.getByRole('link', { name: 'Try the capability editor', exact: true })
  await expect(editorLink).toBeInViewport()
  await editorLink.click()
  await expect(page.locator('#apex-editor-heading')).toBeInViewport()
  await page.getByRole('link', { name: 'Replay a workflow', exact: true }).click()
  await expect(page).toHaveURL(/#local-apex-workbench$/)
  await expect(page.getByRole('heading', { name: 'Replay an illustrative workflow.' })).toBeInViewport()
})
