package typesys

import "github.com/glade-sh/glade/internal/apexast"

var dataSourcePlatformSymbolOverlays = []StandardSymbolSpec{
	{
		Name:       "DataSource.AuthenticationCapability",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.AuthenticationCapability", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.AuthenticationCapability>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "ANONYMOUS", Type: "DataSource.AuthenticationCapability", Static: true},
			{Name: "BASIC", Type: "DataSource.AuthenticationCapability", Static: true},
			{Name: "CERTIFICATE", Type: "DataSource.AuthenticationCapability", Static: true},
			{Name: "OAUTH", Type: "DataSource.AuthenticationCapability", Static: true},
		},
	},
	{
		Name:       "DataSource.AuthenticationProtocol",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.AuthenticationProtocol", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.AuthenticationProtocol>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "NONE", Type: "DataSource.AuthenticationProtocol", Static: true},
			{Name: "OAUTH", Type: "DataSource.AuthenticationProtocol", Static: true},
			{Name: "PASSWORD", Type: "DataSource.AuthenticationProtocol", Static: true},
		},
	},
	{
		Name:       "DataSource.Capability",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.Capability", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.Capability>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "MULTI_PICKLIST", Type: "DataSource.Capability", Static: true},
			{Name: "PICKLIST", Type: "DataSource.Capability", Static: true},
			{Name: "QUERY_PAGINATION_SERVER_DRIVEN", Type: "DataSource.Capability", Static: true},
			{Name: "QUERY_TOTAL_SIZE", Type: "DataSource.Capability", Static: true},
			{Name: "REQUIRE_ENDPOINT", Type: "DataSource.Capability", Static: true},
			{Name: "REQUIRE_HTTPS", Type: "DataSource.Capability", Static: true},
			{Name: "ROW_CREATE", Type: "DataSource.Capability", Static: true},
			{Name: "ROW_DELETE", Type: "DataSource.Capability", Static: true},
			{Name: "ROW_QUERY", Type: "DataSource.Capability", Static: true},
			{Name: "ROW_UPDATE", Type: "DataSource.Capability", Static: true},
			{Name: "SEARCH", Type: "DataSource.Capability", Static: true},
		},
	},
	{
		Name:       "DataSource.Column",
		SuperClass: "DataSource.DataSourceUtil",
		Methods: []StandardMethodSpec{
			{Name: "boolean", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "currency", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}}, Static: true},
			{Name: "date", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "datetime", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "email", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "externalLookup", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "domain", Type: "String"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "label", Type: "String"}, {Name: "description", Type: "String"}, {Name: "isSortable", Type: "Boolean"}, {Name: "isFilterable", Type: "Boolean"}, {Name: "type", Type: "DataSource.DataType"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}, {Name: "referenceTo", Type: "String"}, {Name: "referenceTargetField", Type: "String"}, {Name: "picklistValuesObj", Type: "Object"}, {Name: "isPicklistAlphabeticallySorted", Type: "Boolean"}, {Name: "isPicklistRestricted", Type: "Boolean"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "label", Type: "String"}, {Name: "description", Type: "String"}, {Name: "isSortable", Type: "Boolean"}, {Name: "isFilterable", Type: "Boolean"}, {Name: "type", Type: "DataSource.DataType"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}, {Name: "referenceTo", Type: "String"}, {Name: "referenceTargetField", Type: "String"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "label", Type: "String"}, {Name: "description", Type: "String"}, {Name: "isSortable", Type: "Boolean"}, {Name: "isFilterable", Type: "Boolean"}, {Name: "type", Type: "DataSource.DataType"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "label", Type: "String"}, {Name: "description", Type: "String"}, {Name: "isSortable", Type: "Boolean"}, {Name: "isFilterable", Type: "Boolean"}, {Name: "type", Type: "DataSource.DataType"}, {Name: "length", Type: "Integer"}}, Static: true},
			{Name: "indirectLookup", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "domain", Type: "String"}, {Name: "targetField", Type: "String"}}, Static: true},
			{Name: "integer", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}}, Static: true},
			{Name: "lookup", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "domain", Type: "String"}}, Static: true},
			{Name: "multipicklist", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "picklistValues", Type: "List<Map<String,String>>"}, {Name: "isPicklistAlphabeticallySorted", Type: "Boolean"}, {Name: "isPicklistRestricted", Type: "Boolean"}}, Static: true},
			{Name: "multipicklist", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "picklistValues", Type: "List<Map<String,String>>"}}, Static: true},
			{Name: "number", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}}, Static: true},
			{Name: "percent", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}, {Name: "decimalPlaces", Type: "Integer"}}, Static: true},
			{Name: "phone", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "picklist", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "picklistValues", Type: "List<Map<String,String>>"}, {Name: "isPicklistAlphabeticallySorted", Type: "Boolean"}, {Name: "isPicklistRestricted", Type: "Boolean"}}, Static: true},
			{Name: "picklist", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "picklistValues", Type: "List<Map<String,String>>"}}, Static: true},
			{Name: "text", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}}, Static: true},
			{Name: "text", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "label", Type: "String"}, {Name: "length", Type: "Integer"}}, Static: true},
			{Name: "text", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "textarea", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "time", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
			{Name: "url", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "length", Type: "Integer"}}, Static: true},
			{Name: "url", ReturnType: "DataSource.Column", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "decimalPlaces", Type: "Integer"},
			{Name: "description", Type: "String"},
			{Name: "filterable", Type: "Boolean"},
			{Name: "isPicklistAlphabeticallySorted", Type: "Boolean"},
			{Name: "isPicklistRestricted", Type: "Boolean"},
			{Name: "label", Type: "String"},
			{Name: "length", Type: "Integer"},
			{Name: "name", Type: "String"},
			{Name: "picklistValues", Type: "List<Map<String,String>>"},
			{Name: "referenceTargetField", Type: "String"},
			{Name: "referenceTo", Type: "String"},
			{Name: "sortable", Type: "Boolean"},
			{Name: "type", Type: "DataSource.DataType"},
		},
	},
	{
		Name:       "DataSource.ColumnSelection",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "aggregation", Type: "DataSource.QueryAggregation"},
			{Name: "columnName", Type: "String"},
			{Name: "tableName", Type: "String"},
		},
	},
	{
		Name:       "DataSource.Connection",
		SuperClass: "DataSource.DataSourceUtil",
		Methods: []StandardMethodSpec{
			{Name: "deleteRows", ReturnType: "List<DataSource.DeleteResult>", ParameterSpecs: []StandardParameterSpec{{Name: "deleteContext", Type: "DataSource.DeleteContext"}}},
			{Name: "query", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}}},
			{Name: "search", ReturnType: "List<DataSource.TableResult>", ParameterSpecs: []StandardParameterSpec{{Name: "searchContext", Type: "DataSource.SearchContext"}}},
			{Name: "sync", ReturnType: "List<DataSource.Table>"},
			{Name: "upsertRows", ReturnType: "List<DataSource.UpsertResult>", ParameterSpecs: []StandardParameterSpec{{Name: "upsertContext", Type: "DataSource.UpsertContext"}}},
		},
	},
	{
		Name:       "DataSource.ConnectionParams",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "certificateName", Type: "String"},
			{Name: "endpoint", Type: "String"},
			{Name: "oauthToken", Type: "String"},
			{Name: "password", Type: "String"},
			{Name: "principalType", Type: "DataSource.IdentityType"},
			{Name: "protocol", Type: "DataSource.AuthenticationProtocol"},
			{Name: "repository", Type: "String"},
			{Name: "username", Type: "String"},
		},
	},
	{
		Name:       "DataSource.DataSourceUtil",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "logWarning", ReturnType: "void", ParameterSpecs: []StandardParameterSpec{{Name: "message", Type: "String"}}},
			{Name: "throwException", ReturnType: "void", ParameterSpecs: []StandardParameterSpec{{Name: "message", Type: "String"}}},
		},
	},
	{
		Name:       "DataSource.DataType",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.DataType", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.DataType>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "BOOLEAN_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "CURRENCY_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "DATE_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "DATETIME_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "EMAIL_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "EXTERNAL_LOOKUP_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "INDIRECT_LOOKUP_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "LOOKUP_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "NUMBER_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "PERCENT_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "PHONE_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "PICKLIST_MULTISELECT_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "PICKLIST_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "STRING_LONG_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "STRING_SHORT_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "TIME_TYPE", Type: "DataSource.DataType", Static: true},
			{Name: "URL_TYPE", Type: "DataSource.DataType", Static: true},
		},
	},
	{
		Name:       "DataSource.DeleteContext",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "externalIds", Type: "List<String>"},
			{Name: "tableSelected", Type: "String"},
		},
	},
	{
		Name:       "DataSource.DeleteResult",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "failure", ReturnType: "DataSource.DeleteResult", ParameterSpecs: []StandardParameterSpec{{Name: "externalId", Type: "String"}, {Name: "errorMessage", Type: "String"}}, Static: true},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "success", ReturnType: "DataSource.DeleteResult", ParameterSpecs: []StandardParameterSpec{{Name: "externalId", Type: "String"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "errorMessage", Type: "String"},
			{Name: "externalId", Type: "String"},
			{Name: "success", Type: "Boolean"},
		},
	},
	{
		Name:       "DataSource.Filter",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "columnName", Type: "String"},
			{Name: "columnValue", Type: "Object"},
			{Name: "subfilters", Type: "List<DataSource.Filter>"},
			{Name: "tableName", Type: "String"},
			{Name: "type", Type: "DataSource.FilterType"},
		},
	},
	{
		Name:       "DataSource.FilterType",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.FilterType", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.FilterType>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "AND_", Type: "DataSource.FilterType", Static: true},
			{Name: "CONTAINS", Type: "DataSource.FilterType", Static: true},
			{Name: "ENDS_WITH", Type: "DataSource.FilterType", Static: true},
			{Name: "EQUALS", Type: "DataSource.FilterType", Static: true},
			{Name: "GREATER_THAN_OR_EQUAL_TO", Type: "DataSource.FilterType", Static: true},
			{Name: "GREATER_THAN", Type: "DataSource.FilterType", Static: true},
			{Name: "LESS_THAN_OR_EQUAL_TO", Type: "DataSource.FilterType", Static: true},
			{Name: "LESS_THAN", Type: "DataSource.FilterType", Static: true},
			{Name: "LIKE_", Type: "DataSource.FilterType", Static: true},
			{Name: "NOT_", Type: "DataSource.FilterType", Static: true},
			{Name: "NOT_EQUALS", Type: "DataSource.FilterType", Static: true},
			{Name: "OR_", Type: "DataSource.FilterType", Static: true},
			{Name: "STARTS_WITH", Type: "DataSource.FilterType", Static: true},
		},
	},
	{
		Name:       "DataSource.IdentityType",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.IdentityType", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.IdentityType>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "ANONYMOUS", Type: "DataSource.IdentityType", Static: true},
			{Name: "NAMED_USER", Type: "DataSource.IdentityType", Static: true},
			{Name: "PER_USER", Type: "DataSource.IdentityType", Static: true},
		},
	},
	{
		Name:       "DataSource.Order",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "get", ReturnType: "DataSource.Order", ParameterSpecs: []StandardParameterSpec{{Name: "tableName", Type: "String"}, {Name: "columnName", Type: "String"}, {Name: "direction", Type: "DataSource.OrderDirection"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "columnName", Type: "String"},
			{Name: "direction", Type: "DataSource.OrderDirection"},
			{Name: "tableName", Type: "String"},
		},
	},
	{
		Name:       "DataSource.OrderDirection",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.OrderDirection", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.OrderDirection>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "ASCENDING", Type: "DataSource.OrderDirection", Static: true},
			{Name: "DESCENDING", Type: "DataSource.OrderDirection", Static: true},
		},
	},
	{
		Name:       "DataSource.Provider",
		SuperClass: "DataSource.DataSourceUtil",
		Methods: []StandardMethodSpec{
			{Name: "getAuthenticationCapabilities", ReturnType: "List<DataSource.AuthenticationCapability>"},
			{Name: "getCapabilities", ReturnType: "List<DataSource.Capability>"},
			{Name: "getConnection", ReturnType: "DataSource.Connection", ParameterSpecs: []StandardParameterSpec{{Name: "connectionParams", Type: "DataSource.ConnectionParams"}}},
		},
	},
	{
		Name:       "DataSource.QueryAggregation",
		Kind:       apexast.DeclarationEnum,
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "ordinal", ReturnType: "Integer"},
			{Name: "valueOf", ReturnType: "DataSource.QueryAggregation", ParameterSpecs: []StandardParameterSpec{{Name: "str", Type: "String"}}, Static: true},
			{Name: "values", ReturnType: "List<DataSource.QueryAggregation>", Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "AVG", Type: "DataSource.QueryAggregation", Static: true},
			{Name: "COUNT", Type: "DataSource.QueryAggregation", Static: true},
			{Name: "MAX", Type: "DataSource.QueryAggregation", Static: true},
			{Name: "MIN", Type: "DataSource.QueryAggregation", Static: true},
			{Name: "NONE", Type: "DataSource.QueryAggregation", Static: true},
			{Name: "SUM", Type: "DataSource.QueryAggregation", Static: true},
		},
	},
	{
		Name:       "DataSource.QueryContext",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "get", ReturnType: "DataSource.QueryContext", ParameterSpecs: []StandardParameterSpec{{Name: "metadata", Type: "List<DataSource.Table>"}, {Name: "offset", Type: "Integer"}, {Name: "maxResults", Type: "Integer"}, {Name: "tableSelection", Type: "DataSource.TableSelection"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "queryMoreToken", Type: "String"},
			{Name: "tableSelection", Type: "DataSource.TableSelection"},
		},
	},
	{
		Name:       "DataSource.QueryUtils",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "applyLimitAndOffset", ReturnType: "List<Map<String,Object>>", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
			{Name: "filter", ReturnType: "List<Map<String,Object>>", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
			{Name: "process", ReturnType: "List<Map<String,Object>>", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
			{Name: "sort", ReturnType: "List<Map<String,Object>>", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
		},
	},
	{
		Name:       "DataSource.ReadContext",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "maxResults", Type: "Integer"},
			{Name: "metadata", Type: "List<DataSource.Table>"},
			{Name: "offset", Type: "Integer"},
		},
	},
	{
		Name:       "DataSource.SearchContext",
		SuperClass: "DataSource.ReadContext",
		ConstructorSpecs: []StandardConstructorSpec{
			{Parameters: []StandardParameterSpec{}},
			{Parameters: []StandardParameterSpec{{Name: "metadata", Type: "List<DataSource.Table>"}, {Name: "offset", Type: "Integer"}, {Name: "maxResults", Type: "Integer"}, {Name: "tableSelections", Type: "List<DataSource.TableSelection>"}, {Name: "searchPhrase", Type: "String"}}},
		},
		Properties: []StandardPropertySpec{
			{Name: "searchPhrase", Type: "String"},
			{Name: "tableSelections", Type: "List<DataSource.TableSelection>"},
		},
	},
	{
		Name:       "DataSource.SearchUtils",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "searchByName", ReturnType: "List<DataSource.TableResult>", ParameterSpecs: []StandardParameterSpec{{Name: "searchContext", Type: "DataSource.SearchContext"}, {Name: "connection", Type: "DataSource.Connection"}}, Static: true},
		},
	},
	{
		Name:       "DataSource.Table",
		SuperClass: "DataSource.DataSourceUtil",
		Methods: []StandardMethodSpec{
			{Name: "get", ReturnType: "DataSource.Table", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "nameColumn", Type: "String"}, {Name: "columns", Type: "List<DataSource.Column>"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.Table", ParameterSpecs: []StandardParameterSpec{{Name: "name", Type: "String"}, {Name: "labelSingular", Type: "String"}, {Name: "labelPlural", Type: "String"}, {Name: "description", Type: "String"}, {Name: "nameColumn", Type: "String"}, {Name: "columns", Type: "List<DataSource.Column>"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "columns", Type: "List<DataSource.Column>"},
			{Name: "description", Type: "String"},
			{Name: "labelPlural", Type: "String"},
			{Name: "labelSingular", Type: "String"},
			{Name: "name", Type: "String"},
			{Name: "nameColumn", Type: "String"},
		},
	},
	{
		Name:       "DataSource.TableResult",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "error", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "errorMessage", Type: "String"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "success", Type: "Boolean"}, {Name: "errorMessage", Type: "String"}, {Name: "tableName", Type: "String"}, {Name: "rows", Type: "List<Map<String,Object>>"}, {Name: "totalSize", Type: "Integer"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "success", Type: "Boolean"}, {Name: "errorMessage", Type: "String"}, {Name: "tableName", Type: "String"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "queryContext", Type: "DataSource.QueryContext"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
			{Name: "get", ReturnType: "DataSource.TableResult", ParameterSpecs: []StandardParameterSpec{{Name: "tableSelection", Type: "DataSource.TableSelection"}, {Name: "rows", Type: "List<Map<String,Object>>"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "errorMessage", Type: "String"},
			{Name: "queryMoreToken", Type: "String"},
			{Name: "rows", Type: "List<Map<String,Object>>"},
			{Name: "success", Type: "Boolean"},
			{Name: "tableName", Type: "String"},
			{Name: "totalSize", Type: "Integer"},
		},
	},
	{
		Name:       "DataSource.TableSelection",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "columnsSelected", Type: "List<DataSource.ColumnSelection>"},
			{Name: "filter", Type: "DataSource.Filter"},
			{Name: "order", Type: "List<DataSource.Order>"},
			{Name: "tableSelected", Type: "String"},
		},
	},
	{
		Name:       "DataSource.UpsertContext",
		SuperClass: "Object",
		Properties: []StandardPropertySpec{
			{Name: "rows", Type: "List<Map<String,Object>>"},
			{Name: "tableSelected", Type: "String"},
		},
	},
	{
		Name:       "DataSource.UpsertResult",
		SuperClass: "Object",
		Methods: []StandardMethodSpec{
			{Name: "equals", ReturnType: "Boolean", ParameterSpecs: []StandardParameterSpec{{Name: "obj", Type: "Object"}}},
			{Name: "failure", ReturnType: "DataSource.UpsertResult", ParameterSpecs: []StandardParameterSpec{{Name: "externalId", Type: "String"}, {Name: "errorMessage", Type: "String"}}, Static: true},
			{Name: "hashCode", ReturnType: "Integer"},
			{Name: "success", ReturnType: "DataSource.UpsertResult", ParameterSpecs: []StandardParameterSpec{{Name: "externalId", Type: "String"}}, Static: true},
		},
		Properties: []StandardPropertySpec{
			{Name: "errorMessage", Type: "String"},
			{Name: "externalId", Type: "String"},
			{Name: "success", Type: "Boolean"},
		},
	},
}
