import esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.join(__dirname, "src");

await esbuild.build({
  entryPoints: [path.join(srcDir, "glade.out.mjs")],
  bundle: false,
  format: "esm",
  outfile: path.join(__dirname, "../internal/lwcruntime/embed/glade.out.js"),
  platform: "browser",
});

await esbuild.build({
  entryPoints: [
    path.join(srcDir, "shell/app.mjs"),
    path.join(srcDir, "shell/community-host.mjs"),
    path.join(srcDir, "shell/router.mjs"),
    path.join(srcDir, "shell/context-panel.mjs"),
    path.join(srcDir, "shell/diagnostics.mjs"),
    path.join(srcDir, "slds/slds-loader.mjs"),
    path.join(srcDir, "shims/community.mjs"),
    path.join(srcDir, "shims/site.mjs"),
    path.join(srcDir, "lightning/button.mjs"),
    path.join(srcDir, "lightning/buttonIcon.mjs"),
    path.join(srcDir, "lightning/card.mjs"),
    path.join(srcDir, "lightning/input.mjs"),
    path.join(srcDir, "lightning/textarea.mjs"),
    path.join(srcDir, "lightning/combobox.mjs"),
    path.join(srcDir, "lightning/layout.mjs"),
    path.join(srcDir, "lightning/layoutItem.mjs"),
    path.join(srcDir, "lightning/tabset.mjs"),
    path.join(srcDir, "lightning/tab.mjs"),
    path.join(srcDir, "lightning/spinner.mjs"),
    path.join(srcDir, "lightning/icon.mjs"),
    path.join(srcDir, "lightning/datatable.mjs"),
    path.join(srcDir, "lightning/recordForm.mjs"),
    path.join(srcDir, "lightning/recordViewForm.mjs"),
    path.join(srcDir, "lightning/recordEditForm.mjs"),
    path.join(srcDir, "lightning/outputField.mjs"),
    path.join(srcDir, "lightning/inputField.mjs"),
    path.join(srcDir, "lightning/messages.mjs"),
    path.join(srcDir, "lightning/modal.mjs"),
    path.join(srcDir, "lightning/accordion.mjs"),
    path.join(srcDir, "lightning/accordionSection.mjs"),
    path.join(srcDir, "lightning/avatar.mjs"),
    path.join(srcDir, "lightning/badge.mjs"),
    path.join(srcDir, "lightning/breadcrumb.mjs"),
    path.join(srcDir, "lightning/breadcrumbs.mjs"),
    path.join(srcDir, "lightning/buttonGroup.mjs"),
    path.join(srcDir, "lightning/buttonIconStateful.mjs"),
    path.join(srcDir, "lightning/buttonMenu.mjs"),
    path.join(srcDir, "lightning/buttonStateful.mjs"),
    path.join(srcDir, "lightning/carousel.mjs"),
    path.join(srcDir, "lightning/carouselImage.mjs"),
    path.join(srcDir, "lightning/checkboxGroup.mjs"),
    path.join(srcDir, "lightning/dualListbox.mjs"),
    path.join(srcDir, "lightning/fileUpload.mjs"),
    path.join(srcDir, "lightning/flow.mjs"),
    path.join(srcDir, "lightning/formattedAddress.mjs"),
    path.join(srcDir, "lightning/formattedDateTime.mjs"),
    path.join(srcDir, "lightning/formattedEmail.mjs"),
    path.join(srcDir, "lightning/formattedNumber.mjs"),
    path.join(srcDir, "lightning/formattedPhone.mjs"),
    path.join(srcDir, "lightning/formattedRichText.mjs"),
    path.join(srcDir, "lightning/formattedText.mjs"),
    path.join(srcDir, "lightning/formattedTime.mjs"),
    path.join(srcDir, "lightning/formattedUrl.mjs"),
    path.join(srcDir, "lightning/helptext.mjs"),
    path.join(srcDir, "lightning/inputAddress.mjs"),
    path.join(srcDir, "lightning/inputRichText.mjs"),
    path.join(srcDir, "lightning/map.mjs"),
    path.join(srcDir, "lightning/menuDivider.mjs"),
    path.join(srcDir, "lightning/menuItem.mjs"),
    path.join(srcDir, "lightning/menuSubheader.mjs"),
    path.join(srcDir, "lightning/pill.mjs"),
    path.join(srcDir, "lightning/pillContainer.mjs"),
    path.join(srcDir, "lightning/progressBar.mjs"),
    path.join(srcDir, "lightning/progressIndicator.mjs"),
    path.join(srcDir, "lightning/progressRing.mjs"),
    path.join(srcDir, "lightning/progressStep.mjs"),
    path.join(srcDir, "lightning/quickActionPanel.mjs"),
    path.join(srcDir, "lightning/radioGroup.mjs"),
    path.join(srcDir, "lightning/recordPicker.mjs"),
    path.join(srcDir, "lightning/select.mjs"),
    path.join(srcDir, "lightning/slider.mjs"),
    path.join(srcDir, "lightning/tile.mjs"),
    path.join(srcDir, "lightning/tree.mjs"),
    path.join(srcDir, "lightning/treeGrid.mjs"),
    path.join(srcDir, "lightning/verticalNavigation.mjs"),
    path.join(srcDir, "lightning/verticalNavigationItem.mjs"),
    path.join(srcDir, "lightning/verticalNavigationSection.mjs"),
  ],
  bundle: false,
  format: "esm",
  outdir: path.join(__dirname, ".esbuild-check"),
  platform: "browser",
  write: false,
});

console.log("built internal/lwcruntime/embed/glade.out.js");
