// Local replay of the owned record forms native fixture. No native answers are supplied.
import fs from "node:fs";
import { randomUUID } from "node:crypto";
import { createRequire } from "node:module";
import { observeDOM, actDOM, mountDOM, observeInspector } from "./l19_native_dom.mjs";
import { observeInteractionDOM, selectInteractionPicklist, editInteractionDate } from "./l19_interaction_dom.mjs";

const config = JSON.parse(fs.readFileSync(0, "utf8"));
const fixturePath = "/services/data/v" + config.fixtureApi;
const { chromium } = createRequire(import.meta.url)(config.playwrightModule);
const browser = await chromium.launch({
  headless: true,
  ...(config.executablePath ? { executablePath: config.executablePath } : {}),
  timeout: 15000,
});
const values = {}, errors = {};
let environmentError = "";
async function deadline(work, ms, reason) {
  let timer;
  try {
    return await Promise.race([work, new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error(reason)), ms);
    })]);
  } finally { clearTimeout(timer); }
}

// Same fixture preparation as the native REST composite, through Glade's REST
// server. This supplies inputs only; assertions never read an oracle/mock DTO.
async function rest(path, method = "GET", body) {
  const response = await fetch(new URL(path, config.url), {
    method,
    headers: { "Content-Type": "application/json" },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    signal: AbortSignal.timeout(15000),
  });
  const text = await response.text();
  if (!response.ok) throw new Error("owned fixture REST " + response.status + ": " + text);
  return text ? JSON.parse(text) : null;
}

async function prepare(spec) {
  const marker = "L19-" + randomUUID().replaceAll("-", "");
  const account = {
    Name: marker + " PRIMARY", Phone: "415-555-0100", Website: "https://example.invalid/owned",
    AnnualRevenue: 123.45, NumberOfEmployees: 7, Description: "OWNED DESCRIPTION", AccountNumber: marker,
  };
  const contact = {
    LastName: marker + " CONTACT", Email: "owned@example.invalid", Birthdate: "2001-02-03",
    Description: "OWNED DESCRIPTION", Department: marker,
  };
  if (spec.fixtureField && !["Name", "IsDeleted"].includes(spec.fixtureField) && spec.fixtureValue !== "$ACCOUNT") {
    (spec.object === "Account" ? account : contact)[spec.fixtureField] = spec.fixtureValue;
  }
  if (spec.fixtureField === "Name" && spec.object === "Account" && spec.fixtureValue !== null) {
    account.Name = spec.fixtureValue;
  }
  if (!(spec.fixtureField === "AccountId" && spec.fixtureValue === null)) contact.AccountId = "@{primary.id}";
  const path = fixturePath;
  const secondName = marker + " SECOND";
  const result = await rest(path + "/composite", "POST", {
    allOrNone: true,
    compositeRequest: [
      { method: "POST", url: path + "/sobjects/Account", referenceId: "primary", body: account },
      { method: "POST", url: path + "/sobjects/Account", referenceId: "secondary", body: { Name: secondName, AccountNumber: marker } },
      { method: "POST", url: path + "/sobjects/Contact", referenceId: "contact", body: contact },
    ],
  });
  const records = result?.compositeResponse;
  if (!Array.isArray(records) || records.length !== 3 ||
      records.some(row => row.httpStatusCode !== 201 || row.body?.success !== true)) {
    throw new Error("owned fixture composite failed: " + JSON.stringify(result));
  }
  const ids = Object.fromEntries(records.map(row => [row.referenceId, row.body.id]));
  if (!ids.primary || !ids.secondary || !ids.contact) throw new Error("owned fixture IDs missing");
  return {
    account: ids.primary, second: ids.secondary, contact: ids.contact, name: account.Name,
    marker, secondName, contactName: contact.LastName,
  };
}

async function cleanup(fixtures) {
  const path = fixturePath;
  // Includes records created by submit. The marker is generated by this replay.
  const found = [];
  for (const [object, field] of [["Contact", "Department"], ["Account", "AccountNumber"]]) {
    const query = "SELECT Id FROM " + object + " WHERE " + field + " = '" + fixtures.marker + "'";
    const result = await rest(path + "/query?q=" + encodeURIComponent(query));
    if (!Array.isArray(result?.records)) throw new Error("owned cleanup query missing records");
    for (const record of result.records) found.push([object, record.Id]);
  }
  for (const [object, id] of found) await rest(path + "/sobjects/" + object + "/" + id, "DELETE");
}

// Native capture substitutes only owned fixture identifiers/names and created
// record IDs. It preserves raw null, omitted fields, array order and all text.
function normalize(value, fixtures) {
  const symbols = [
    [fixtures.account, "$ACCOUNT"], [fixtures.second, "$SECOND"], [fixtures.contact, "$CONTACT"],
    [fixtures.name, "$PRIMARY_NAME"], [fixtures.secondName, "$SECOND_NAME"],
    [fixtures.contactName, "$CONTACT_NAME"], [fixtures.marker, "$OWNERSHIP_MARKER"],
  ].sort((a, b) => b[0].length - a[0].length);
  function visit(node) {
    if (Array.isArray(node)) return node.map(visit);
    if (node !== null && typeof node === "object") {
      return Object.fromEntries(Object.entries(node).map(([key, item]) => [visit(key), visit(item)]));
    }
    if (typeof node === "string") {
      for (const [original, replacement] of symbols) {
        node = node.replaceAll(original, replacement);
        if (/^(001|003)/.test(original)) node = node.replaceAll(original.slice(0, 15), replacement);
      }
      return node.replace(/\b(?:001|003)[A-Za-z0-9]{12}(?:[A-Za-z0-9]{3})?\b/g, "$CREATED_RECORD");
    }
    return node;
  }
  return visit(value);
}

const hostSelector = "[data-l19-host]:visible";
const markerSelector = hostSelector + " [data-result]";
const nativeSelector = hostSelector + " [data-native]";

function createPageSession() {
  let page, assetErrors = [], pageErrors = [];

  async function openPage() {
    if (page) await deadline(page.close(), 5000, "local page close timeout");
    page = await browser.newPage();
    assetErrors = []; pageErrors = [];
    page.on("pageerror", error => pageErrors.push(error.name + ": " + error.message));
    page.on("response", response => {
      const path = new URL(response.url()).pathname;
      if (response.status() >= 400 && /\.(?:m?js|css)$/.test(path)) assetErrors.push(response.status() + " " + path);
    });
    const response = await page.goto(config.url, { waitUntil: "domcontentloaded", timeout: 30000 });
    if (!response?.ok()) throw new Error("local fixture page unavailable");
    try {
      await page.locator(hostSelector + " [data-page-ready]").waitFor({ state: "visible", timeout: 30000 });
    } catch (error) {
      const startup = await page.evaluate(() => window.__l19Error).catch(() => null);
      if (assetErrors.length) environmentError = "local browser assets unavailable: " + assetErrors.join("; ");
      throw new Error("local page initialization: " + error.message + "; " + JSON.stringify(startup) + "; " + pageErrors.slice(0, 4).join("; "));
    }
    if (assetErrors.length) {
      environmentError = "local browser assets unavailable: " + assetErrors.join("; ");
      throw new Error(environmentError);
    }
  }

  async function acknowledgement(id, stage) {
    // Matching native fixture acknowledgement, never a synthesized null/timeout.
    const value = await deadline(page.locator(markerSelector).evaluate((node, wanted) => new Promise((resolve, reject) => {
      let observer, timer;
      const read = () => {
        let value;
        try { value = JSON.parse(node.textContent); } catch { return; }
        if (value?.id === wanted.id && value.stage === wanted.stage) {
          observer?.disconnect(); clearTimeout(timer); resolve(value); return true;
        }
      };
      if (read()) return;
      observer = new MutationObserver(read);
      timer = setTimeout(() => { observer.disconnect(); reject(new Error("owned acknowledgement timeout")); }, 20000);
      observer.observe(node, { subtree: true, childList: true, characterData: true });
    }), { id, stage }), 25000, "local acknowledgement RPC timeout");
    if (assetErrors.length) {
      environmentError = "local browser assets unavailable: " + assetErrors.join("; ");
      throw new Error(environmentError);
    }
    return value;
  }

  async function clickFixtureCommand(selector) {
    const command = page.locator(hostSelector + " " + selector);
    // These fixture commands are outside the observed data-native subtree.
    // Keep them reachable above open product menus while retaining the native
    // pointer click, including its focus/blur behavior. Do not change the menu.
    await command.evaluate(node => {
      node.style.position = "relative";
      node.style.zIndex = "2147483647";
    });
    await command.click({ timeout: 15000 });
  }

  async function captureDOM(spec, state, fixtures) {
    await page.locator(hostSelector).evaluate(mountDOM, state);
    await acknowledgement(spec.id, "ready");
    const interaction = ["picklist-select", "date-edit"].includes(spec.operation);
    const snapshot = interaction ? observeInteractionDOM : observeDOM;
    const before = await page.locator(nativeSelector).evaluate(snapshot);
    const actionObserver = spec.operation === "picklist-select" ? selectInteractionPicklist :
      spec.operation === "date-edit" ? editInteractionDate : actDOM;
    const action = await page.locator(nativeSelector).evaluate(actionObserver, {
      inputText: spec.control_input,
      operation: spec.operation, name: fixtures.name,
      noMatch: fixtures.name + (Object.hasOwn(spec.props, "searchSuffix") ? spec.props.searchSuffix :
        Object.hasOwn(spec.props, "filter") ? "" : " NO MATCH"),
    });
    if (["button-submit", "prevent-submit", "override-submit"].includes(spec.operation)) {
      await page.locator(hostSelector + " [data-submit] button").click({ timeout: 15000 });
    } else {
      await clickFixtureCommand("[data-run]");
    }
    // Match the native in-page observation window before reading the after DOM.
    await page.evaluate(async () => { await new Promise(resolve => setTimeout(resolve, 5000)); });
    const after = await page.locator(nativeSelector).evaluate(snapshot);
    await clickFixtureCommand("[data-finish]");
    const done = await acknowledgement(spec.id, "done");
    const published = { ...done };
    if (config.controlProject) {
      // Added native-control provenance/timing is retained in the oracle. The
      // original semantic DOM projection has neither of these extra fields.
      delete published.sourceApi;
      delete published.eventTrace;
    }
    const observation = { ...published, before, action, after, observationWindowMs: 5000 };
    if (!done.events.some(event => ["load", "ready", "error"].includes(event.type))) observation.noLoadReadyOrErrorWithinMs = 5000;
    if (["submit", "submit-deleted", "button-submit", "override-submit"].includes(spec.operation) &&
        !done.events.some(event => ["success", "error"].includes(event.type))) observation.noSubmitSuccessOrErrorWithinMs = 5000;
    const eventDetails = done.eventTrace?.map(({ index, type, detailKeys, recordIds }) => ({ index, type, detailKeys, recordIds }));
    if (interaction) observation.eventDetails = eventDetails;
    return { observation, eventDetails };
  }

  return {
    openPage, captureDOM,
    inspect: (state, operation) => observeInspector(page, state, operation),
    close: async () => { if (page) await deadline(page.close(), 5000, "local page close timeout"); },
  };
}

// Each page owns disjoint records. Six bounded pages preserve the native
// fifteen-row batches and all five/eight-second observation windows.
const pageCount = 6;

async function replayPage(worker) {
  const session = createPageSession();
  let ordinaryRows = 0, resetPage = true;
  try {
    for (let batch = worker * 15; batch < config.cases.length; batch += pageCount * 15) {
      resetPage = true;
      process.stderr.write(`L19 API ${config.api} page ${worker} batch ${batch} starting\n`);
      for (const { id, spec, observer, cachePhase, projection } of config.cases.slice(batch, batch + 15)) {
        if (environmentError) return;
        let fixtures, observation, failure = "";
        try {
          fixtures = await prepare(spec);
          if (spec.operation === "submit-deleted") {
            await rest(fixturePath + "/sobjects/Account/" + fixtures.account, "DELETE");
          }
          if (cachePhase || resetPage || observer === "inspector" || ordinaryRows >= 15) {
            await session.openPage(); ordinaryRows = 0; resetPage = false;
          }
          const state = { c__case: spec.id };
          for (const key of ["account", "second", "contact", "name", "marker"]) state["c__" + key] = fixtures[key];
          if (observer === "inspector") {
            observation = await deadline(session.inspect(state, spec.operation), 40000, "local inspector RPC timeout");
            resetPage = true;
          } else {
            if (cachePhase === "same-page-remount") {
              // Real primer operation in this browser, using the same records.
              // The native paired control disconnects/remounts without reload.
              await deadline(session.captureDOM(spec, state, fixtures), 90000, "local cache primer RPC timeout");
            }
            const captured = await deadline(session.captureDOM(spec, state, fixtures), 90000, "local row RPC timeout");
            observation = projection === "event-details"
              ? { events: captured.observation.events, eventDetails: captured.eventDetails }
              : captured.observation;
            ordinaryRows++;
          }
        } catch (error) {
          failure = error.message;
          resetPage = true;
        } finally {
          if (fixtures) {
            try { await cleanup(fixtures); }
            catch (error) { failure += (failure ? "; " : "") + "owned cleanup: " + error.message; }
          }
        }
        if (failure) errors[id] = failure;
        else values[id] = normalize(observation, fixtures);
      }
    }
  } finally { await session.close(); }
}

try {
  // One Chromium process, disjoint owned fixtures, and unchanged row windows.
  await Promise.all(Array.from({ length: pageCount }, (_, index) => replayPage(index)));
  if (environmentError) {
    for (const { id } of config.cases) {
      if (!Object.hasOwn(values, id) && !Object.hasOwn(errors, id)) errors[id] = environmentError;
    }
  }
  process.stdout.write(JSON.stringify({ values, errors, environmentError }));
} finally {
  await deadline(browser.close(), 10000, "local browser close timeout");
}
